// apps/svelte/src/lib/components/layout/OnboardingGate.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { createQuery } from '@tanstack/svelte-query';
	import { getApiClient } from '$lib/api';
	import { queryKeys, unwrap } from '$lib/query';
	import AppLoadingOverlay from './AppLoadingOverlay.svelte';

	/**
	 * Client onboarding gate — the UX (loading-overlay) half. The authoritative redirect for un-onboarded
	 * `/app` users is the server gate in `hooks.server.ts` (no flash); this overlay covers the
	 * client-side window while the status query resolves and redirects if onboarding is incomplete.
	 * Query args wrapped in a function so TanStack Query stays reactive.
	 */
	let { children }: { children: Snippet } = $props();

	const api = getApiClient();
	const status = createQuery(() => ({
		queryKey: queryKeys.onboarding.status(),
		queryFn: async () => unwrap(await api.onboarding.status.get())
	}));

	const pathname = $derived(page.url.pathname);
	const inApp = $derived(pathname.startsWith('/app'));
	const needsOnboarding = $derived(
		inApp && !pathname.startsWith('/onboarding') && !!status.data && !status.data.completed
	);

	$effect(() => {
		if (needsOnboarding) {
			void goto(resolve('/onboarding'), { replaceState: true });
		}
	});
</script>

{#if inApp && status.isLoading}
	<AppLoadingOverlay label="Menyiapkan akun..." />
{:else if needsOnboarding}
	<AppLoadingOverlay label="Menyiapkan onboarding..." />
{:else}
	{@render children()}
{/if}

// apps/web-v2/components/onboarding-gate.tsx
"use client";

import { usePathname, useRouter } from "next/navigation";
import { useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import { AppLoadingOverlay } from "@/components/app-loading-overlay";
import { useApi } from "@/lib/api-client";
import { queryKeys, unwrap } from "@/lib/api-query";

export function OnboardingGate({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const router = useRouter();
  const api = useApi();
  const status = useQuery({
    queryKey: queryKeys.onboarding.status(),
    queryFn: async () => unwrap(await api.onboarding.status.get()),
  });

  const needsOnboarding =
    pathname.startsWith("/app") &&
    !pathname.startsWith("/onboarding") &&
    status.data &&
    !status.data.completed;

  useEffect(() => {
    if (needsOnboarding) {
      router.replace("/onboarding");
    }
  }, [needsOnboarding, router]);

  if (pathname.startsWith("/app") && status.isLoading) {
    return <AppLoadingOverlay label="Menyiapkan akun..." />;
  }

  if (needsOnboarding) {
    return <AppLoadingOverlay label="Menyiapkan onboarding..." />;
  }

  return children;
}
