// apps/web/features/threads/components/tokenized-prompt-input.tsx
"use client";

import {
  buildPaperMentionLabel,
  buildWorkspaceMentionLabel,
  type ContextRef,
  contextRefsSignature,
  countContextRefs,
  filterPromptCommandsBySlashQuery,
  MAX_CONTEXT_PAPERS,
  MAX_CONTEXT_WORKSPACES,
  type PromptCommand,
} from "@aqsha/chat-core";
import { type KeyboardEvent as ReactKeyboardEvent, useEffect, useRef, useState } from "react";
import { Popover, PopoverAnchor, PopoverContent } from "@/components/ui/popover";
import { cn } from "@/lib/utils";
import {
  createCommandChipElement,
  createContextChipElement,
  editorHasCommandChips,
  editorHasContextChips,
  extractCommandsFromEditor,
  extractContextRefsFromEditor,
  getMentionFilterQueryBeforeCursor,
  getSlashFilterQueryBeforeCursor,
  getTextBeforeCursor,
  insertNodeAtSelection,
  insertPlainTextAtSelection,
  moveCaretToEnd,
  removeCommandChipBeforeCursor,
  removeMentionTokenBeforeCursor,
  removeSlashTokenBeforeCursor,
  renderComposerEditorWithPinnedContext,
  serializeComposerEditor,
  serializeComposerEditorWithMarkers,
} from "../lib/composer-inline-editor";
import {
  ContextMentionPalette,
  type MentionItemOption,
  type MentionWorkspaceOption,
} from "./context-mention-palette";
import { SlashCommandPalette } from "./slash-command-palette";

const COLLAPSED_EDITOR_HEIGHT = 32;

const EMPTY_PINNED_REFS: ContextRef[] = [];

export type ContextWorkspaceOption = {
  workspaceId: string;
  name: string;
  emoji?: string;
};

export type ContextItemOption = {
  workspaceId: string;
  artifactId: string;
  title: string;
};

const EMPTY_CONTEXT_WORKSPACES: ContextWorkspaceOption[] = [];

function truncateLabel(value: string, max = 22) {
  const compact = value.replace(/\s+/g, " ").trim();
  return compact.length > max ? `${compact.slice(0, max - 1)}…` : compact;
}

export function TokenizedPromptInput({
  value,
  onValueChange,
  onCommandsChange,
  onSubmit,
  disabled,
  maxLength,
  placeholder,
  onHeightChange,
  className,
  isCollapsed = false,
  pinnedContextRefs = EMPTY_PINNED_REFS,
  onContextRefsChange,
  onRichValueChange,
  contextWorkspaces = EMPTY_CONTEXT_WORKSPACES,
  ambientWorkspaceId = null,
  workspaceItems,
  workspaceItemsLoading = false,
  onRequestWorkspaceItems,
}: {
  value: string;
  onValueChange: (value: string) => void;
  onCommandsChange: (commands: PromptCommand[]) => void;
  onSubmit: () => void;
  disabled?: boolean;
  maxLength: number;
  placeholder: string;
  onHeightChange?: (height: number) => void;
  className?: string;
  isCollapsed?: boolean;
  pinnedContextRefs?: ContextRef[];
  onContextRefsChange?: (refs: ContextRef[]) => void;
  onRichValueChange?: (rich: string) => void;
  contextWorkspaces?: ContextWorkspaceOption[];
  ambientWorkspaceId?: string | null;
  workspaceItems?: ContextItemOption[];
  workspaceItemsLoading?: boolean;
  onRequestWorkspaceItems?: (workspaceId: string | null) => void;
}) {
  const editorRef = useRef<HTMLDivElement | null>(null);
  const paletteDismissalRef = useRef({ value, dismissed: false });
  const lastContextSignatureRef = useRef<string | null>(null);
  const isPaletteDismissed = () =>
    paletteDismissalRef.current.value === value && paletteDismissalRef.current.dismissed;
  const setPaletteDismissed = (dismissed: boolean) => {
    paletteDismissalRef.current = { value, dismissed };
  };
  const [slashFilterQuery, setSlashFilterQuery] = useState<string | null>(null);
  const [mentionFilterQuery, setMentionFilterQuery] = useState<string | null>(null);
  const [drillWorkspaceId, setDrillWorkspaceId] = useState<string | null>(null);

  const slashOpen = slashFilterQuery !== null;
  const mentionOpen = mentionFilterQuery !== null;
  const paletteOpen = slashOpen || mentionOpen;
  const mentionMode: "workspace" | "item" = drillWorkspaceId ? "item" : "workspace";

  if (!mentionOpen && drillWorkspaceId !== null) {
    setDrillWorkspaceId(null);
  }

  const filteredCommands = slashOpen ? filterPromptCommandsBySlashQuery(slashFilterQuery) : [];

  const counts = countContextRefs(pinnedContextRefs);
  const pinnedWorkspaceIds = new Set(
    pinnedContextRefs.flatMap((ref) => (ref.kind === "workspace" ? [ref.workspaceId] : [])),
  );
  const pinnedArtifactIds = new Set(
    pinnedContextRefs.flatMap((ref) => (ref.kind === "paper" ? [ref.artifactId] : [])),
  );
  const workspaceCapReached = counts.workspaces >= MAX_CONTEXT_WORKSPACES;
  const paperCapReached = counts.papers >= MAX_CONTEXT_PAPERS;

  const drillWorkspace = drillWorkspaceId
    ? contextWorkspaces.find((workspace) => workspace.workspaceId === drillWorkspaceId)
    : undefined;
  const drillWorkspaceName = drillWorkspace?.name ?? "";

  const mentionQuery = (mentionFilterQuery ?? "").trim().toLowerCase();

  const workspaceOptions: MentionWorkspaceOption[] = !mentionOpen
    ? []
    : [...contextWorkspaces]
        .filter(
          (workspace) => mentionQuery === "" || workspace.name.toLowerCase().includes(mentionQuery),
        )
        .sort((a, b) => {
          const aAmbient = a.workspaceId === ambientWorkspaceId ? 0 : 1;
          const bAmbient = b.workspaceId === ambientWorkspaceId ? 0 : 1;
          if (aAmbient !== bAmbient) {
            return aAmbient - bAmbient;
          }
          return a.name.localeCompare(b.name);
        })
        .map((workspace) => {
          const pinned = pinnedWorkspaceIds.has(workspace.workspaceId);
          return {
            type: "workspace" as const,
            workspaceId: workspace.workspaceId,
            name: workspace.name,
            emoji: workspace.emoji,
            isAmbient: workspace.workspaceId === ambientWorkspaceId,
            disabled: pinned || workspaceCapReached,
            disabledReason: pinned
              ? "sudah jadi konteks"
              : workspaceCapReached
                ? "batas tercapai"
                : undefined,
          };
        });

  const itemOptions: MentionItemOption[] =
    !mentionOpen || mentionMode !== "item"
      ? []
      : (workspaceItems ?? []).flatMap((item) => {
          if (mentionQuery !== "" && !item.title.toLowerCase().includes(mentionQuery)) {
            return [];
          }
          const pinned = pinnedArtifactIds.has(item.artifactId);
          return [
            {
              type: "item" as const,
              workspaceId: item.workspaceId,
              workspaceName: drillWorkspaceName,
              artifactId: item.artifactId,
              title: item.title,
              disabled: pinned || paperCapReached,
              disabledReason: pinned
                ? "sudah ditambahkan"
                : paperCapReached
                  ? `batas ${MAX_CONTEXT_PAPERS} paper`
                  : undefined,
            },
          ];
        });

  const activeLength = slashOpen
    ? filteredCommands.length
    : mentionMode === "item"
      ? itemOptions.length
      : workspaceOptions.length;

  const capNotice =
    mentionOpen && mentionMode === "workspace" && workspaceCapReached
      ? `Batas ${MAX_CONTEXT_WORKSPACES} workspace per percakapan.`
      : mentionOpen && mentionMode === "item" && paperCapReached
        ? `Batas ${MAX_CONTEXT_PAPERS} paper per percakapan.`
        : null;

  const highlightKey = `${slashOpen ? "command" : mentionMode}:${slashFilterQuery ?? ""}:${mentionFilterQuery ?? ""}:${drillWorkspaceId ?? ""}:${activeLength}`;
  const [highlightedState, setHighlightedState] = useState({ key: highlightKey, index: 0 });
  const highlightedIndex =
    highlightedState.key === highlightKey
      ? Math.min(highlightedState.index, Math.max(activeLength - 1, 0))
      : 0;
  const setHighlightedIndex = (nextIndex: number | ((currentIndex: number) => number)) => {
    setHighlightedState((current) => {
      const baseIndex = current.key === highlightKey ? current.index : 0;
      const index = typeof nextIndex === "function" ? nextIndex(baseIndex) : nextIndex;
      return { key: highlightKey, index };
    });
  };

  const syncEditorState = () => {
    const editor = editorRef.current;
    if (!editor) {
      return;
    }
    const serialized = serializeComposerEditor(editor).replace(/\u00a0/g, " ");
    onCommandsChange(extractCommandsFromEditor(editor));
    const contextRefs = extractContextRefsFromEditor(editor);
    const contextSignature = contextRefsSignature(contextRefs);
    if (contextSignature !== lastContextSignatureRef.current) {
      lastContextSignatureRef.current = contextSignature;
      onContextRefsChange?.(contextRefs);
    }
    onRichValueChange?.(serializeComposerEditorWithMarkers(editor));
    if (serialized !== value) {
      onValueChange(serialized);
    }
    if (onHeightChange) {
      onHeightChange(
        serialized.length === 0 && !editorHasCommandChips(editor) && !editorHasContextChips(editor)
          ? COLLAPSED_EDITOR_HEIGHT
          : editor.scrollHeight,
      );
    }
    if (!isPaletteDismissed()) {
      const before = getTextBeforeCursor(editor);
      const slash = getSlashFilterQueryBeforeCursor(before);
      setSlashFilterQuery(slash);
      setMentionFilterQuery(slash === null ? getMentionFilterQueryBeforeCursor(before) : null);
    } else {
      setSlashFilterQuery(null);
      setMentionFilterQuery(null);
    }
  };

  // biome-ignore lint/correctness/useExhaustiveDependencies: seed editor dari value + pinned pills (callback identitas tak relevan)
  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) {
      return;
    }
    const serialized = serializeComposerEditor(editor);
    const currentChipSignature = contextRefsSignature(extractContextRefsFromEditor(editor));
    const desiredChipSignature = contextRefsSignature(pinnedContextRefs);
    if (serialized === value && currentChipSignature === desiredChipSignature) {
      return;
    }
    if (document.activeElement === editor && value !== "") {
      return;
    }
    renderComposerEditorWithPinnedContext(editor, {
      pinnedRefs: pinnedContextRefs,
      visibleContent: value,
    });
    onCommandsChange(extractCommandsFromEditor(editor));
    if (document.activeElement === editor) {
      moveCaretToEnd(editor);
    }
    if (onHeightChange) {
      onHeightChange(
        value.length === 0 && !editorHasCommandChips(editor) && !editorHasContextChips(editor)
          ? COLLAPSED_EDITOR_HEIGHT
          : editor.scrollHeight,
      );
    }
  }, [onCommandsChange, onHeightChange, value, pinnedContextRefs]);

  useEffect(() => {
    if (!paletteOpen) {
      return;
    }
    const editor = editorRef.current;
    if (!editor || document.activeElement === editor) {
      return;
    }
    editor.focus();
  }, [paletteOpen]);

  const focusEditor = () => {
    window.requestAnimationFrame(() => {
      const editor = editorRef.current;
      if (!editor) return;
      editor.focus();
      moveCaretToEnd(editor);
    });
  };

  const handleSelectCommand = (selected: PromptCommand) => {
    const editor = editorRef.current;
    if (!editor) {
      return;
    }
    removeSlashTokenBeforeCursor(editor);
    insertNodeAtSelection(createCommandChipElement(selected));
    setPaletteDismissed(false);
    syncEditorState();
    focusEditor();
  };

  const handleSelectWholeWorkspace = (option: MentionWorkspaceOption) => {
    const editor = editorRef.current;
    if (!editor || option.disabled) {
      return;
    }
    removeMentionTokenBeforeCursor(editor);
    insertNodeAtSelection(
      createContextChipElement({
        kind: "workspace",
        workspaceId: option.workspaceId,
        label: buildWorkspaceMentionLabel(option.name),
      }),
    );
    setDrillWorkspaceId(null);
    onRequestWorkspaceItems?.(null);
    setPaletteDismissed(false);
    syncEditorState();
    focusEditor();
  };

  const handleDrillWorkspace = (option: MentionWorkspaceOption) => {
    const editor = editorRef.current;
    if (!editor) {
      return;
    }
    removeMentionTokenBeforeCursor(editor);
    insertPlainTextAtSelection("@");
    setDrillWorkspaceId(option.workspaceId);
    onRequestWorkspaceItems?.(option.workspaceId);
    setPaletteDismissed(false);
    syncEditorState();
    focusEditor();
  };

  const handleSelectItem = (option: MentionItemOption) => {
    const editor = editorRef.current;
    if (!editor || option.disabled) {
      return;
    }
    removeMentionTokenBeforeCursor(editor);
    insertNodeAtSelection(
      createContextChipElement({
        kind: "paper",
        workspaceId: option.workspaceId,
        artifactId: option.artifactId,
        label: buildPaperMentionLabel(
          truncateLabel(option.workspaceName, 16),
          truncateLabel(option.title, 20),
        ),
      }),
    );
    setDrillWorkspaceId(null);
    onRequestWorkspaceItems?.(null);
    setPaletteDismissed(false);
    syncEditorState();
    focusEditor();
  };

  const handleBackToWorkspaces = () => {
    setDrillWorkspaceId(null);
    onRequestWorkspaceItems?.(null);
    focusEditor();
  };

  const selectHighlightedOption = () => {
    if (slashOpen) {
      const command = filteredCommands[highlightedIndex];
      if (command) {
        handleSelectCommand(command);
      }
      return;
    }
    if (mentionMode === "item") {
      const option = itemOptions[highlightedIndex];
      if (option) {
        handleSelectItem(option);
      }
      return;
    }
    const option = workspaceOptions[highlightedIndex];
    if (option) {
      handleSelectWholeWorkspace(option);
    }
  };

  const updateEditorFromInput = () => {
    const editor = editorRef.current;
    if (!editor) {
      return;
    }
    const serialized = serializeComposerEditor(editor);
    if (serialized.length > maxLength) {
      renderComposerEditorWithPinnedContext(editor, {
        pinnedRefs: extractContextRefsFromEditor(editor),
        visibleContent: serialized.slice(0, maxLength),
      });
      moveCaretToEnd(editor);
    }
    syncEditorState();
  };

  const handleKeyDown = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    if (event.nativeEvent.isComposing) {
      return;
    }
    if ((event.metaKey || event.ctrlKey) && event.key === "Enter") {
      event.preventDefault();
      onSubmit();
      return;
    }

    if (paletteOpen && activeLength > 0) {
      if (event.key === "ArrowDown") {
        event.preventDefault();
        setHighlightedIndex((index) => (index + 1) % activeLength);
        return;
      }
      if (event.key === "ArrowUp") {
        event.preventDefault();
        setHighlightedIndex((index) => (index - 1 + activeLength) % activeLength);
        return;
      }
      if (event.key === "Tab" && !event.shiftKey) {
        event.preventDefault();
        selectHighlightedOption();
        return;
      }
      if (event.key === "Enter" && !event.shiftKey) {
        event.preventDefault();
        selectHighlightedOption();
        return;
      }
      if (mentionOpen && mentionMode === "workspace" && event.key === "ArrowRight") {
        const option = workspaceOptions[highlightedIndex];
        if (option) {
          event.preventDefault();
          handleDrillWorkspace(option);
          return;
        }
      }
      if (mentionOpen && mentionMode === "item" && event.key === "ArrowLeft") {
        event.preventDefault();
        handleBackToWorkspaces();
        return;
      }
    }

    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      onSubmit();
      return;
    }

    if (event.key === "Backspace") {
      const editor = editorRef.current;
      if (editor && removeCommandChipBeforeCursor(editor)) {
        event.preventDefault();
        syncEditorState();
        return;
      }
    }

    if (event.key === "Escape" && paletteOpen) {
      event.preventDefault();
      setPaletteDismissed(true);
      setSlashFilterQuery(null);
      setMentionFilterQuery(null);
      focusEditor();
    }
  };

  const handleChipClick = (event: React.MouseEvent<HTMLDivElement>) => {
    const target = event.target;
    if (!(target instanceof HTMLElement)) {
      return;
    }
    const chip = target.closest<HTMLElement>('[data-chip="command"],[data-chip="context"]');
    if (!chip || !editorRef.current?.contains(chip)) {
      return;
    }
    event.preventDefault();
    chip.remove();
    syncEditorState();
    focusEditor();
  };

  const isEditorEmpty = value.trim().length === 0 && pinnedContextRefs.length === 0;
  const showPlaceholder = isEditorEmpty;

  return (
    <Popover open={paletteOpen} modal={false}>
      <PopoverAnchor asChild>
        <div
          className={cn(
            "relative min-w-0 w-full text-[12.5px] text-foreground leading-[18px]",
            isCollapsed && "flex min-h-8 items-center",
            disabled && "opacity-100",
            className,
          )}
        >
          {showPlaceholder ? (
            <span
              className={cn(
                "pointer-events-none absolute left-0 font-normal text-[12.5px] text-muted-foreground",
                isCollapsed ? "inset-y-0 flex items-center" : "top-[3px]",
              )}
            >
              {placeholder}
            </span>
          ) : null}
          <div
            ref={editorRef}
            contentEditable={!disabled}
            role="textbox"
            aria-label="Pesan"
            aria-multiline="true"
            aria-controls={
              slashOpen
                ? "composer-slash-commands"
                : mentionOpen
                  ? "composer-context-mentions"
                  : undefined
            }
            className={cn(
              "max-h-36 w-full overflow-y-auto whitespace-pre-wrap break-words text-foreground caret-primary outline-none disabled:opacity-100",
              isCollapsed ? "min-h-8 py-[7px] leading-[18px]" : "min-h-6 py-1",
            )}
            onInput={updateEditorFromInput}
            onBlur={syncEditorState}
            onKeyDown={handleKeyDown}
            onClick={handleChipClick}
            tabIndex={0}
            suppressContentEditableWarning
          />
        </div>
      </PopoverAnchor>
      <PopoverContent
        align="start"
        side="bottom"
        sideOffset={12}
        className="w-[min(22.5rem,calc(100vw-2rem))] overflow-hidden rounded-xl p-0"
        onMouseDown={(event) => {
          event.preventDefault();
        }}
        onOpenAutoFocus={(event) => {
          event.preventDefault();
        }}
        onCloseAutoFocus={(event) => {
          event.preventDefault();
          focusEditor();
        }}
      >
        {slashOpen ? (
          <SlashCommandPalette
            commands={filteredCommands}
            highlightedIndex={highlightedIndex}
            onHighlight={setHighlightedIndex}
            onSelect={handleSelectCommand}
          />
        ) : (
          <ContextMentionPalette
            mode={mentionMode}
            workspaceOptions={workspaceOptions}
            itemOptions={itemOptions}
            itemsLoading={workspaceItemsLoading}
            drillWorkspaceName={drillWorkspaceName}
            highlightedIndex={highlightedIndex}
            capNotice={capNotice}
            onHighlight={setHighlightedIndex}
            onSelectWorkspace={handleSelectWholeWorkspace}
            onDrillWorkspace={handleDrillWorkspace}
            onSelectItem={handleSelectItem}
            onBack={handleBackToWorkspaces}
          />
        )}
      </PopoverContent>
    </Popover>
  );
}

// apps/svelte/src/lib/features/threads/components/composer/TokenizedPromptInput.svelte
<script lang="ts">
	import {
		buildPaperMentionLabel,
		buildWorkspaceMentionLabel,
		type ContextRef,
		contextRefsSignature,
		countContextRefs,
		filterPromptCommandsBySlashQuery,
		MAX_CONTEXT_PAPERS,
		MAX_CONTEXT_WORKSPACES,
		type PromptCommand
	} from '@aqsha/chat-core';
	import { Popover as PopoverPrimitive } from 'bits-ui';
	import { IsMobile } from '$lib/hooks/is-mobile.svelte';
	import { cn } from '$lib/utils';
	import {
		createCommandChipElement,
		createContextChipElement,
		editorHasCommandChips,
		editorHasContextChips,
		extractCommandsFromEditor,
		extractContextRefsFromEditor,
		getMentionFilterQueryBeforeCursor,
		getSlashFilterQueryBeforeCursor,
		getTextBeforeCursor,
		insertNodeAtSelection,
		insertPlainTextAtSelection,
		moveCaretToEnd,
		removeCommandChipBeforeCursor,
		removeMentionTokenBeforeCursor,
		removeSlashTokenBeforeCursor,
		renderComposerEditorWithPinnedContext,
		serializeComposerEditor,
		serializeComposerEditorWithMarkers
	} from '../../lib/composer-inline-editor';
	import ComposerChipTooltip from './ComposerChipTooltip.svelte';
	import ContextMentionPalette from './ContextMentionPalette.svelte';
	import SlashCommandPalette from './SlashCommandPalette.svelte';
	import type {
		ComposerPlaceholder,
		ContextItemOption,
		ContextWorkspaceOption,
		MentionItemOption,
		MentionWorkspaceOption
	} from './palette-types';

	const COLLAPSED_EDITOR_HEIGHT = 32;

	let {
		value,
		onValueChange,
		onCommandsChange,
		onSubmit,
		disabled = false,
		maxLength,
		placeholder,
		onHeightChange,
		class: className,
		isCollapsed = false,
		pinnedContextRefs = [],
		onContextRefsChange,
		onRichValueChange,
		contextWorkspaces = [],
		ambientWorkspaceId = null,
		workspaceItems,
		workspaceItemsLoading = false,
		onRequestWorkspaceItems,
		mobilePaletteAnchor = null
	}: {
		value: string;
		onValueChange: (value: string) => void;
		onCommandsChange: (commands: PromptCommand[]) => void;
		onSubmit: () => void;
		disabled?: boolean;
		maxLength: number;
		placeholder: ComposerPlaceholder;
		onHeightChange?: (height: number) => void;
		class?: string;
		isCollapsed?: boolean;
		pinnedContextRefs?: ContextRef[];
		onContextRefsChange?: (refs: ContextRef[]) => void;
		onRichValueChange?: (rich: string) => void;
		contextWorkspaces?: ContextWorkspaceOption[];
		ambientWorkspaceId?: string | null;
		workspaceItems?: ContextItemOption[];
		workspaceItemsLoading?: boolean;
		onRequestWorkspaceItems?: (workspaceId: string | null) => void;
		/** Palette anchor on mobile: the composer shell element so the popover is shell-width + centred. */
		mobilePaletteAnchor?: HTMLElement | null;
	} = $props();

	let editorEl = $state<HTMLDivElement | null>(null);
	let editorWrapperEl = $state<HTMLDivElement | null>(null);
	const isMobile = new IsMobile();
	const anchorToShell = $derived(isMobile.current && mobilePaletteAnchor != null);

	// Non-reactive dismissal + signature holders — never read reactively.
	// Starts undismissed; `setPaletteDismissed` snapshots the current `value` at dismissal time.
	let paletteDismissal: { value: string; dismissed: boolean } = { value: '', dismissed: false };
	let lastContextSignature: string | null = null;
	const isPaletteDismissed = () => paletteDismissal.value === value && paletteDismissal.dismissed;
	const setPaletteDismissed = (dismissed: boolean) => {
		paletteDismissal = { value, dismissed };
	};

	let slashFilterQuery = $state<string | null>(null);
	let mentionFilterQuery = $state<string | null>(null);
	let drillWorkspaceId = $state<string | null>(null);
	let hoveredChip = $state<HTMLElement | null>(null);

	const slashOpen = $derived(slashFilterQuery !== null);
	const mentionOpen = $derived(mentionFilterQuery !== null);
	const paletteOpen = $derived(slashOpen || mentionOpen);
	const mentionMode = $derived<'workspace' | 'item'>(drillWorkspaceId ? 'item' : 'workspace');

	const filteredCommands = $derived(
		slashOpen ? filterPromptCommandsBySlashQuery(slashFilterQuery!) : []
	);

	const counts = $derived(countContextRefs(pinnedContextRefs));
	const pinnedWorkspaceIds = $derived(
		new Set(pinnedContextRefs.flatMap((ref) => (ref.kind === 'workspace' ? [ref.workspaceId] : [])))
	);
	const pinnedArtifactIds = $derived(
		new Set(pinnedContextRefs.flatMap((ref) => (ref.kind === 'paper' ? [ref.artifactId] : [])))
	);
	const workspaceCapReached = $derived(counts.workspaces >= MAX_CONTEXT_WORKSPACES);
	// The paper budget covers every pinned source (workspace papers + ambient explore-paper/news).
	const paperCapReached = $derived(
		counts.papers + counts.explorePapers + counts.news >= MAX_CONTEXT_PAPERS
	);

	const drillWorkspace = $derived(
		drillWorkspaceId ? contextWorkspaces.find((w) => w.workspaceId === drillWorkspaceId) : undefined
	);
	const drillWorkspaceName = $derived(drillWorkspace?.name ?? '');
	const mentionQuery = $derived((mentionFilterQuery ?? '').trim().toLowerCase());

	const workspaceOptions = $derived<MentionWorkspaceOption[]>(
		!mentionOpen
			? []
			: [...contextWorkspaces]
					.filter((w) => mentionQuery === '' || w.name.toLowerCase().includes(mentionQuery))
					.sort((a, b) => {
						const aAmbient = a.workspaceId === ambientWorkspaceId ? 0 : 1;
						const bAmbient = b.workspaceId === ambientWorkspaceId ? 0 : 1;
						if (aAmbient !== bAmbient) return aAmbient - bAmbient;
						return a.name.localeCompare(b.name);
					})
					.map((w) => {
						const pinned = pinnedWorkspaceIds.has(w.workspaceId);
						return {
							type: 'workspace' as const,
							workspaceId: w.workspaceId,
							name: w.name,
							emoji: w.emoji,
							isAmbient: w.workspaceId === ambientWorkspaceId,
							disabled: pinned || workspaceCapReached,
							disabledReason: pinned
								? 'sudah jadi konteks'
								: workspaceCapReached
									? 'batas tercapai'
									: undefined
						};
					})
	);

	const itemOptions = $derived<MentionItemOption[]>(
		!mentionOpen || mentionMode !== 'item'
			? []
			: (workspaceItems ?? []).flatMap((item) => {
					if (mentionQuery !== '' && !item.title.toLowerCase().includes(mentionQuery)) return [];
					const pinned = pinnedArtifactIds.has(item.artifactId);
					return [
						{
							type: 'item' as const,
							workspaceId: item.workspaceId,
							workspaceName: drillWorkspaceName,
							artifactId: item.artifactId,
							title: item.title,
							disabled: pinned || paperCapReached,
							disabledReason: pinned
								? 'sudah ditambahkan'
								: paperCapReached
									? `batas ${MAX_CONTEXT_PAPERS} paper`
									: undefined
						}
					];
				})
	);

	const activeLength = $derived(
		slashOpen
			? filteredCommands.length
			: mentionMode === 'item'
				? itemOptions.length
				: workspaceOptions.length
	);

	const capNotice = $derived(
		mentionOpen && mentionMode === 'workspace' && workspaceCapReached
			? `Batas ${MAX_CONTEXT_WORKSPACES} workspace per percakapan.`
			: mentionOpen && mentionMode === 'item' && paperCapReached
				? `Batas ${MAX_CONTEXT_PAPERS} paper per percakapan.`
				: null
	);

	const highlightKey = $derived(
		`${slashOpen ? 'command' : mentionMode}:${slashFilterQuery ?? ''}:${mentionFilterQuery ?? ''}:${drillWorkspaceId ?? ''}:${activeLength}`
	);
	let highlightedState = $state({ key: '', index: 0 });
	const highlightedIndex = $derived(
		highlightedState.key === highlightKey
			? Math.min(highlightedState.index, Math.max(activeLength - 1, 0))
			: 0
	);
	function setHighlightedIndex(next: number | ((current: number) => number)): void {
		const baseIndex = highlightedState.key === highlightKey ? highlightedState.index : 0;
		const index = typeof next === 'function' ? next(baseIndex) : next;
		highlightedState = { key: highlightKey, index };
	}

	function computeHeight(editor: HTMLElement, serialized: string): number {
		return serialized.length === 0 &&
			!editorHasCommandChips(editor) &&
			!editorHasContextChips(editor)
			? COLLAPSED_EDITOR_HEIGHT
			: editor.scrollHeight;
	}

	function syncEditorState(): void {
		const editor = editorEl;
		if (!editor) return;
		const serialized = serializeComposerEditor(editor).replace(/\u00a0/g, ' ');
		onCommandsChange(extractCommandsFromEditor(editor));
		const contextRefs = extractContextRefsFromEditor(editor);
		const contextSignature = contextRefsSignature(contextRefs);
		if (contextSignature !== lastContextSignature) {
			lastContextSignature = contextSignature;
			onContextRefsChange?.(contextRefs);
		}
		onRichValueChange?.(serializeComposerEditorWithMarkers(editor));
		if (serialized !== value) onValueChange(serialized);
		onHeightChange?.(computeHeight(editor, serialized));
		if (!isPaletteDismissed()) {
			const before = getTextBeforeCursor(editor);
			const slash = getSlashFilterQueryBeforeCursor(before);
			slashFilterQuery = slash;
			mentionFilterQuery = slash === null ? getMentionFilterQueryBeforeCursor(before) : null;
		} else {
			slashFilterQuery = null;
			mentionFilterQuery = null;
		}
		// Reset the drill once the mention palette is closed.
		if (mentionFilterQuery === null && drillWorkspaceId !== null) {
			drillWorkspaceId = null;
			onRequestWorkspaceItems?.(null);
		}
	}

	// Seed the editor DOM from `value` + pinned pills whenever they change externally (external DOM sync
	// via {@attach}, NOT a derived reflex). Skips while focused+non-empty so the caret never jumps
	// jumps mid-type; the `serialized === value` guard makes the post-input re-run a no-op.
	function seedEditor(node: HTMLDivElement) {
		// Read reactive deps so the attachment re-runs on change.
		const v = value;
		const pinned = pinnedContextRefs;
		const serialized = serializeComposerEditor(node);
		const currentChipSignature = contextRefsSignature(extractContextRefsFromEditor(node));
		const desiredChipSignature = contextRefsSignature(pinned);
		if (serialized === v && currentChipSignature === desiredChipSignature) return;
		if (document.activeElement === node && v !== '') return;
		renderComposerEditorWithPinnedContext(node, { pinnedRefs: pinned, visibleContent: v });
		onCommandsChange(extractCommandsFromEditor(node));
		if (document.activeElement === node) moveCaretToEnd(node);
		onHeightChange?.(computeHeight(node, v));
	}

	function focusEditor(): void {
		requestAnimationFrame(() => {
			const editor = editorEl;
			if (!editor) return;
			editor.focus();
			moveCaretToEnd(editor);
		});
	}

	function handleSelectCommand(selected: PromptCommand): void {
		const editor = editorEl;
		if (!editor) return;
		removeSlashTokenBeforeCursor(editor);
		insertNodeAtSelection(createCommandChipElement(selected));
		setPaletteDismissed(false);
		syncEditorState();
		focusEditor();
	}

	function handleSelectWholeWorkspace(option: MentionWorkspaceOption): void {
		const editor = editorEl;
		if (!editor || option.disabled) return;
		removeMentionTokenBeforeCursor(editor);
		insertNodeAtSelection(
			createContextChipElement({
				kind: 'workspace',
				workspaceId: option.workspaceId,
				label: buildWorkspaceMentionLabel(option.name)
			})
		);
		drillWorkspaceId = null;
		onRequestWorkspaceItems?.(null);
		setPaletteDismissed(false);
		syncEditorState();
		focusEditor();
	}

	function handleDrillWorkspace(option: MentionWorkspaceOption): void {
		const editor = editorEl;
		if (!editor) return;
		removeMentionTokenBeforeCursor(editor);
		insertPlainTextAtSelection('@');
		drillWorkspaceId = option.workspaceId;
		onRequestWorkspaceItems?.(option.workspaceId);
		setPaletteDismissed(false);
		syncEditorState();
		focusEditor();
	}

	function handleSelectItem(option: MentionItemOption): void {
		const editor = editorEl;
		if (!editor || option.disabled) return;
		removeMentionTokenBeforeCursor(editor);
		insertNodeAtSelection(
			createContextChipElement({
				kind: 'paper',
				workspaceId: option.workspaceId,
				artifactId: option.artifactId,
				label: buildPaperMentionLabel(option.workspaceName, option.title)
			})
		);
		drillWorkspaceId = null;
		onRequestWorkspaceItems?.(null);
		setPaletteDismissed(false);
		syncEditorState();
		focusEditor();
	}

	function handleBackToWorkspaces(): void {
		drillWorkspaceId = null;
		onRequestWorkspaceItems?.(null);
		focusEditor();
	}

	function selectHighlightedOption(): void {
		if (slashOpen) {
			const command = filteredCommands[highlightedIndex];
			if (command) handleSelectCommand(command);
			return;
		}
		if (mentionMode === 'item') {
			const option = itemOptions[highlightedIndex];
			if (option) handleSelectItem(option);
			return;
		}
		const option = workspaceOptions[highlightedIndex];
		if (option) handleSelectWholeWorkspace(option);
	}

	function updateEditorFromInput(): void {
		// Typing = the chip tooltip is no longer relevant (pointer may sit on a chip by chance).
		hoveredChip = null;
		const editor = editorEl;
		if (!editor) return;
		const serialized = serializeComposerEditor(editor);
		if (serialized.length > maxLength) {
			renderComposerEditorWithPinnedContext(editor, {
				pinnedRefs: extractContextRefsFromEditor(editor),
				visibleContent: serialized.slice(0, maxLength)
			});
			moveCaretToEnd(editor);
		}
		syncEditorState();
	}

	function handleKeyDown(event: KeyboardEvent): void {
		if (event.isComposing) return; // IME composition in progress — let the composition finish
		if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') {
			event.preventDefault();
			onSubmit();
			return;
		}

		if (paletteOpen && activeLength > 0) {
			if (event.key === 'ArrowDown') {
				event.preventDefault();
				setHighlightedIndex((index) => (index + 1) % activeLength);
				return;
			}
			if (event.key === 'ArrowUp') {
				event.preventDefault();
				setHighlightedIndex((index) => (index - 1 + activeLength) % activeLength);
				return;
			}
			if (event.key === 'Tab' && !event.shiftKey) {
				event.preventDefault();
				selectHighlightedOption();
				return;
			}
			if (event.key === 'Enter' && !event.shiftKey) {
				event.preventDefault();
				selectHighlightedOption();
				return;
			}
			if (mentionOpen && mentionMode === 'workspace' && event.key === 'ArrowRight') {
				const option = workspaceOptions[highlightedIndex];
				if (option) {
					event.preventDefault();
					handleDrillWorkspace(option);
					return;
				}
			}
			if (mentionOpen && mentionMode === 'item' && event.key === 'ArrowLeft') {
				event.preventDefault();
				handleBackToWorkspaces();
				return;
			}
		}

		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			onSubmit();
			return;
		}

		if (event.key === 'Backspace') {
			const editor = editorEl;
			if (editor && removeCommandChipBeforeCursor(editor)) {
				event.preventDefault();
				syncEditorState();
				return;
			}
		}

		if (event.key === 'Escape' && paletteOpen) {
			event.preventDefault();
			setPaletteDismissed(true);
			slashFilterQuery = null;
			mentionFilterQuery = null;
			focusEditor();
		}
	}

	// Paste = plain text only (default contentEditable pastes rich HTML → broken composer look). Only
	// preventDefault when there is a caret/selection so plain text truly lands; otherwise let native
	// paste run (else the text is swallowed).
	function handlePaste(event: ClipboardEvent): void {
		const text = event.clipboardData?.getData('text/plain');
		if (!text) return;
		const selection = window.getSelection();
		if (!selection || selection.rangeCount === 0) return;
		event.preventDefault();
		insertPlainTextAtSelection(text);
		updateEditorFromInput();
	}

	function handleChipClick(event: MouseEvent): void {
		const target = event.target;
		if (!(target instanceof HTMLElement)) return;
		const chip = target.closest<HTMLElement>('[data-chip="command"],[data-chip="context"]');
		if (!chip || !editorEl?.contains(chip)) return;
		event.preventDefault();
		hoveredChip = null;
		chip.remove();
		syncEditorState();
		focusEditor();
	}

	function handleChipHover(event: MouseEvent): void {
		const target = event.target;
		if (!(target instanceof HTMLElement)) return;
		const chip = target.closest<HTMLElement>('[data-chip="command"],[data-chip="context"]');
		hoveredChip = chip && editorEl?.contains(chip) ? chip : null;
	}

	const isEditorEmpty = $derived(value.trim().length === 0 && pinnedContextRefs.length === 0);
</script>

<PopoverPrimitive.Root open={paletteOpen} onOpenChange={() => {}}>
	<div
		bind:this={editorWrapperEl}
		class={cn(
			'relative w-full min-w-0 text-[12.5px] leading-[18px] text-foreground',
			isCollapsed && 'flex min-h-8 items-center',
			className
		)}
	>
		{#if isEditorEmpty}
			<span
				class={cn(
					'pointer-events-none absolute left-0 text-[12.5px] font-normal text-muted-foreground',
					isCollapsed ? 'inset-y-0 flex items-center' : 'top-[3px]'
				)}
			>
				{#if typeof placeholder === 'string'}
					{placeholder}
				{:else}
					<span class="@lg/composer:hidden">{placeholder.narrow}</span>
					<span class="hidden @lg/composer:inline">{placeholder.wide}</span>
				{/if}
			</span>
		{/if}
		<!-- svelte-ignore a11y_mouse_events_have_key_events -->
		<div
			bind:this={editorEl}
			{@attach seedEditor}
			contenteditable={!disabled}
			role="textbox"
			aria-label="Pesan"
			aria-multiline="true"
			aria-controls={slashOpen
				? 'composer-slash-commands'
				: mentionOpen
					? 'composer-context-mentions'
					: undefined}
			class={cn(
				'max-h-36 w-full overflow-y-auto break-words whitespace-pre-wrap text-foreground caret-primary outline-none',
				isCollapsed ? 'min-h-8 py-[7px] leading-[18px]' : 'min-h-6 py-1'
			)}
			oninput={updateEditorFromInput}
			onblur={syncEditorState}
			onkeydown={handleKeyDown}
			onpaste={handlePaste}
			onclick={handleChipClick}
			onmouseover={handleChipHover}
			onmouseleave={() => (hoveredChip = null)}
			onscroll={() => (hoveredChip = null)}
			tabindex={0}
		></div>
		{#if hoveredChip}
			<ComposerChipTooltip chip={hoveredChip} />
		{/if}
	</div>
	<PopoverPrimitive.Content
		customAnchor={anchorToShell ? mobilePaletteAnchor : editorWrapperEl}
		align={anchorToShell ? 'center' : 'start'}
		side="bottom"
		sideOffset={12}
		trapFocus={false}
		preventScroll={false}
		interactOutsideBehavior="ignore"
		escapeKeydownBehavior="ignore"
		onOpenAutoFocus={(e: Event) => e.preventDefault()}
		onCloseAutoFocus={(e: Event) => {
			e.preventDefault();
			focusEditor();
		}}
		onmousedown={(e: MouseEvent) => e.preventDefault()}
		class={cn(
			'z-50 overflow-hidden rounded-xl bg-popover p-0 shadow-md ring-1 ring-foreground/10',
			anchorToShell ? 'w-(--bits-floating-anchor-width)' : 'w-[min(22.5rem,calc(100vw-2rem))]'
		)}
	>
		{#if slashOpen}
			<SlashCommandPalette
				commands={filteredCommands}
				{highlightedIndex}
				onHighlight={setHighlightedIndex}
				onSelect={handleSelectCommand}
			/>
		{:else}
			<ContextMentionPalette
				mode={mentionMode}
				{workspaceOptions}
				{itemOptions}
				itemsLoading={workspaceItemsLoading}
				{drillWorkspaceName}
				{highlightedIndex}
				{capNotice}
				onHighlight={setHighlightedIndex}
				onSelectWorkspace={handleSelectWholeWorkspace}
				onDrillWorkspace={handleDrillWorkspace}
				onSelectItem={handleSelectItem}
				onBack={handleBackToWorkspaces}
			/>
		{/if}
	</PopoverPrimitive.Content>
</PopoverPrimitive.Root>
