// apps/svelte/src/lib/features/onboarding/OnboardingPage.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { prefersReducedMotion } from 'svelte/motion';
	import { fly } from 'svelte/transition';
	import { createQuery } from '@tanstack/svelte-query';
	import { getApiClient } from '$lib/api';
	import { queryKeys, unwrap } from '$lib/query';
	import { Button } from '$lib/components/ui/button';
	import { FlickerSpinner } from '$lib/components/ui/flicker-spinner';
	import { Icon, ArrowLeftIcon, ArrowRight, Loader2Icon } from '$lib/icons';
	import {
		BACK_TARGET,
		HOME_AFTER_ONBOARDING,
		PRIMARY_LABEL,
		STEP_LABEL
	} from './lib/onboarding-machine';
	import { createOnboardingFlow } from './state.svelte';
	import OnboardingLayout from './components/OnboardingLayout.svelte';
	import OnboardingStepIndicator from './components/OnboardingStepIndicator.svelte';
	import WelcomeStep from './components/WelcomeStep.svelte';
	import BackgroundStep from './components/BackgroundStep.svelte';
	import InterestsStep from './components/InterestsStep.svelte';
	import SourceStep from './components/SourceStep.svelte';
	import FinishStep from './components/FinishStep.svelte';

	/**
	 * Onboarding wizard — port of apps/web/features/onboarding/pages/onboarding-page.tsx.
	 * The pure step machine + validation lives in `lib/onboarding-machine.ts`; the flow state +
	 * complete mutation in `state.svelte.ts`. Motion mirrors the framer AnimatePresence via
	 * Svelte `{#key}` + `fly` (mode="wait" equivalent), collapsing to no motion when reduced.
	 */
	const api = getApiClient();
	const flow = createOnboardingFlow();
	const reduce = $derived(prefersReducedMotion.current);

	const statusQuery = createQuery(() => ({
		queryKey: queryKeys.onboarding.status(),
		queryFn: async () => unwrap(await api.onboarding.status.get())
	}));
	const status = $derived(statusQuery.data);

	// Only relevant at mount: bounce an already-onboarded user who lands here directly. Once the
	// flow advances past "welcome", status is ignored — so a "completed" flipping true after submit
	// can't skip the finish screen (mirror web's mount-only useEffect intent).
	$effect(() => {
		if (flow.step === 'welcome' && status?.completed) {
			void goto(resolve('/app/explore'), { replaceState: true });
		}
	});

	const isQuestionStep = $derived(flow.questionIndex >= 0);
	const canPrimary = $derived(
		!flow.isSubmitting && (!isQuestionStep || flow.isStepValid(flow.step))
	);
	const backTarget = $derived(BACK_TARGET[flow.step]);

	function handleBack() {
		const target = BACK_TARGET[flow.step];
		if (target) flow.setStep(target);
	}

	async function handlePrimary() {
		switch (flow.step) {
			case 'welcome':
				flow.setStep('background');
				return;
			case 'background':
				flow.setStep('interests');
				return;
			case 'interests':
				flow.setStep('source');
				return;
			case 'source': {
				const ok = await flow.submit();
				if (ok) flow.setStep('finish');
				return;
			}
			case 'finish':
				void goto(resolve(HOME_AFTER_ONBOARDING), { replaceState: true });
				return;
		}
	}

	function onsubmit(event: SubmitEvent) {
		event.preventDefault();
		if (canPrimary) void handlePrimary();
	}
</script>

{#if flow.step === 'welcome' && (!status || status.completed)}
	<!-- At mount, wait for status before showing "welcome" — avoids flashing the wizard to an
		already-onboarded user we're about to redirect away (mirror web loader). -->
	<OnboardingLayout>
		<div class="flex justify-center text-muted-foreground">
			<FlickerSpinner class="size-5" />
		</div>
	</OnboardingLayout>
{:else}
	<OnboardingLayout>
		{#if isQuestionStep}
			<OnboardingStepIndicator
				index={flow.questionIndex + 1}
				total={flow.totalQuestions}
				label={STEP_LABEL[flow.step] ?? ''}
			/>
		{:else}
			<div class="mb-8 h-5"></div>
		{/if}

		<form {onsubmit}>
			<div class="relative">
				{#key flow.step}
					<div
						in:fly={reduce ? { duration: 0 } : { y: 8, duration: 220 }}
						out:fly={reduce ? { opacity: 1, duration: 0 } : { y: -8, duration: 220 }}
					>
						{#if flow.step === 'welcome'}
							<WelcomeStep />
						{:else if flow.step === 'background'}
							<BackgroundStep value={flow.answers.background} onselect={flow.setBackground} />
						{:else if flow.step === 'interests'}
							<InterestsStep value={flow.answers.interests} ontoggle={flow.toggleInterest} />
						{:else if flow.step === 'source'}
							<SourceStep
								value={flow.answers.source}
								other={flow.answers.sourceOther}
								onselect={flow.setSource}
								onotherchange={flow.setSourceOther}
							/>
						{:else if flow.step === 'finish'}
							<FinishStep answers={flow.answers} />
						{/if}
					</div>
				{/key}
			</div>

			{#if flow.errorMessage}
				<p class="mt-4 text-sm text-destructive">{flow.errorMessage}</p>
			{/if}

			<div class="mt-8 flex items-center justify-between gap-3">
				{#if backTarget}
					<Button type="button" variant="ghost" onclick={handleBack}>
						<Icon icon={ArrowLeftIcon} class="size-4" />
						Kembali
					</Button>
				{:else}
					<span></span>
				{/if}
				<Button type="submit" disabled={!canPrimary} class="h-11 px-6">
					{#if flow.isSubmitting}
						<Icon icon={Loader2Icon} class="size-4 animate-spin" />
					{/if}
					{PRIMARY_LABEL[flow.step]}
					{#if !flow.isSubmitting && flow.step !== 'finish'}
						<Icon icon={ArrowRight} class="size-4" />
					{/if}
				</Button>
			</div>
		</form>
	</OnboardingLayout>
{/if}

// apps/web/features/onboarding/pages/onboarding-page.tsx
"use client";

import { AnimatePresence, m, useReducedMotion } from "motion/react";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { ArrowLeftIcon, ArrowRight, Loader2Icon } from "@aqsha/ui/icons";
import { useQuery } from "@tanstack/react-query";
import { useApi } from "@/lib/api-client";
import { queryKeys, unwrap } from "@/lib/api-query";
import { Button } from "@/components/ui/button";
import { OnboardingLayout } from "../components/onboarding-layout";
import { OnboardingStepIndicator } from "../components/onboarding-step-indicator";
import {
  BackgroundStep,
  FinishStep,
  InterestsStep,
  SourceStep,
  WelcomeStep,
} from "../components/onboarding-steps";
import {
  type OnboardingStep,
  useOnboardingFlow,
} from "../lib/use-onboarding-flow";

const HOME_AFTER_ONBOARDING = "/app/explore";

const STEP_LABEL: Partial<Record<OnboardingStep, string>> = {
  background: "Latar belakang",
  interests: "Minat",
  source: "Sumber",
};

const PRIMARY_LABEL: Record<OnboardingStep, string> = {
  welcome: "Mulai",
  background: "Lanjut",
  interests: "Lanjut",
  source: "Selesai",
  finish: "Mulai jelajah",
};

const BACK_TARGET: Partial<Record<OnboardingStep, OnboardingStep>> = {
  background: "welcome",
  interests: "background",
  source: "interests",
};

export function OnboardingPage() {
  const router = useRouter();
  const reduce = useReducedMotion();
  const api = useApi();
  const flow = useOnboardingFlow();
  const {
    step,
    setStep,
    answers,
    setBackground,
    toggleInterest,
    setSource,
    setSourceOther,
    isStepValid,
    submit,
    isSubmitting,
    errorMessage,
    questionIndex,
    totalQuestions,
  } = flow;

  const statusQuery = useQuery({
    queryKey: queryKeys.onboarding.status(),
    queryFn: async () => unwrap(await api.onboarding.status.get()),
  });
  const status = statusQuery.data;

  // Only relevant at mount: bounce an already-onboarded user who lands here
  // directly. Once the flow advances past "welcome", status is ignored — so a
  // "completed" flipping true after submit can't skip the finish screen.
  useEffect(() => {
    if (step === "welcome" && status?.completed) {
      router.replace(HOME_AFTER_ONBOARDING);
    }
  }, [status, step, router]);

  const handleBack = () => {
    const target = BACK_TARGET[step];
    if (target) setStep(target);
  };

  const handlePrimary = async () => {
    switch (step) {
      case "welcome":
        setStep("background");
        return;
      case "background":
        setStep("interests");
        return;
      case "interests":
        setStep("source");
        return;
      case "source": {
        const ok = await submit();
        if (ok) setStep("finish");
        return;
      }
      case "finish":
        router.replace(HOME_AFTER_ONBOARDING);
        return;
    }
  };

  const isQuestionStep = questionIndex >= 0;
  const canPrimary =
    !isSubmitting && (!isQuestionStep || isStepValid(step));

  // At mount, wait for status before showing "welcome" — avoids flashing the
  // wizard to an already-onboarded user we're about to redirect away.
  if (step === "welcome" && (!status || status.completed)) {
    return (
      <OnboardingLayout>
        <div className="flex justify-center text-muted-foreground">
          <Loader2Icon className="size-5 animate-spin" />
        </div>
      </OnboardingLayout>
    );
  }

  return (
    <OnboardingLayout>
      {isQuestionStep ? (
        <OnboardingStepIndicator
          index={questionIndex + 1}
          total={totalQuestions}
          label={STEP_LABEL[step] ?? ""}
        />
      ) : (
        <div className="mb-8 h-5" />
      )}

      <form
        onSubmit={(event) => {
          event.preventDefault();
          if (canPrimary) void handlePrimary();
        }}
      >
        <AnimatePresence mode="wait" initial={false}>
          <m.div
            key={step}
            initial={reduce ? false : { opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={reduce ? { opacity: 0 } : { opacity: 0, y: -8 }}
            transition={{ duration: 0.22, ease: "easeOut" }}
          >
            {step === "welcome" ? <WelcomeStep /> : null}
            {step === "background" ? (
              <BackgroundStep value={answers.background} onSelect={setBackground} />
            ) : null}
            {step === "interests" ? (
              <InterestsStep value={answers.interests} onToggle={toggleInterest} />
            ) : null}
            {step === "source" ? (
              <SourceStep
                value={answers.source}
                other={answers.sourceOther}
                onSelect={setSource}
                onOtherChange={setSourceOther}
              />
            ) : null}
            {step === "finish" ? <FinishStep answers={answers} /> : null}
          </m.div>
        </AnimatePresence>

        {errorMessage ? (
          <p className="mt-4 text-sm text-destructive">{errorMessage}</p>
        ) : null}

        <div className="mt-8 flex items-center justify-between gap-3">
          {BACK_TARGET[step] ? (
            <Button type="button" variant="ghost" onClick={handleBack}>
              <ArrowLeftIcon className="size-4" />
              Kembali
            </Button>
          ) : (
            <span />
          )}
          <Button type="submit" disabled={!canPrimary} className="h-11 px-6">
            {isSubmitting ? <Loader2Icon className="size-4 animate-spin" /> : null}
            {PRIMARY_LABEL[step]}
            {!isSubmitting && step !== "finish" ? (
              <ArrowRight className="size-4" />
            ) : null}
          </Button>
        </div>
      </form>
    </OnboardingLayout>
  );
}
