// packages/ui/src/selia/textarea.tsx
'use client';

import { cn } from '../lib/cn';
import { cva, type VariantProps } from 'class-variance-authority';

export const textareaVariants = cva(
  [
    'w-full px-3.5 py-3.5 text-foreground placeholder:text-dimmed transition-[border-color,box-shadow] shadow-input rounded',
    'ring ring-input-border hover:not-[[disabled],[data-disabled]]:not-[:focus]:ring-input-accent-border focus:outline-0 focus:ring-primary focus:ring-2 min-h-24',
    'disabled:opacity-70 disabled:cursor-not-allowed',
  ],
  {
    variants: {
      variant: {
        default: 'bg-input',
        subtle: 'bg-input/60',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  },
);

export function Textarea({
  className,
  variant,
  ...props
}: React.ComponentProps<'textarea'> & VariantProps<typeof textareaVariants>) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(textareaVariants({ variant, className }))}
      {...props}
    />
  );
}

// packages/ui-svelte/src/components/textarea/textarea.svelte
<script lang="ts">
	import { cn, type WithElementRef, type WithoutChildren } from '../../utils.js';
	import type { HTMLTextareaAttributes } from 'svelte/elements';

	let {
		ref = $bindable(null),
		value = $bindable(),
		class: className,
		'data-slot': dataSlot = 'textarea',
		...restProps
	}: WithoutChildren<WithElementRef<HTMLTextareaAttributes>> = $props();
</script>

<textarea
	bind:this={ref}
	data-slot={dataSlot}
	class={cn(
		'border-input bg-card ctl-inset focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:aria-invalid:border-destructive/50 disabled:bg-muted disabled:text-muted-foreground rounded-md border-2 px-[13px] py-[9px] text-field font-medium transition-colors focus-visible:ring-3 aria-invalid:ring-3 placeholder:text-muted-foreground placeholder:font-medium flex field-sizing-content min-h-16 w-full outline-none disabled:cursor-not-allowed disabled:opacity-50',
		className
	)}
	bind:value
	{...restProps}></textarea>
