// apps/svelte/src/lib/features/onboarding/components/OnboardingLayout.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	// Full-viewport, card-less canvas: the page background only, content centered.
	let { children }: { children: Snippet } = $props();
</script>

<main class="flex min-h-svh w-full items-center justify-center px-6 py-12">
	<div class="w-full max-w-xl">{@render children()}</div>
</main>

// apps/web-v2/features/onboarding/components/onboarding-layout.tsx
"use client";

import type { ReactNode } from "react";

// Full-viewport, card-less canvas: the page background only, content centered.
export function OnboardingLayout({ children }: { children: ReactNode }) {
  return (
    <main className="flex min-h-svh w-full items-center justify-center px-6 py-12">
      <div className="w-full max-w-xl">{children}</div>
    </main>
  );
}
