// packages/ui/src/selia/alert.tsx
'use client';

import * as React from 'react';
import { cn } from '../lib/cn';
import { cva, type VariantProps } from 'class-variance-authority';

export const alertVariants = cva(
  [
    'w-full px-3.5 py-1.5 min-h-11 rounded font-medium',
    '[&_svg:not([class*=size-])]:size-4.5 *:[svg]:shrink-0',
    'items-center gap-x-2.5 gap-y-1 flex text-foreground',
    'has-[>[data-slot=alert-description]]:grid',
    'has-[>[data-slot=alert-description]]:py-3',
    'has-[>svg]:grid-cols-[calc(var(--spacing)*4.5)_1fr_auto]',
    'not-[:has(>svg)]:grid-cols-[1fr_auto]',
    'not-[:has(>svg)]:[&>[data-slot=alert-description]]:col-start-1',
  ],
  {
    variants: {
      variant: {
        default: 'bg-background ring ring-border',
        danger: 'bg-danger/7 ring ring-danger/30 [&_svg:not([class*=text-])]:text-danger',
        info: 'bg-info/7 ring ring-info/30 [&_svg:not([class*=text-])]:text-info',
        success: 'bg-success/7 ring ring-success/30 [&_svg:not([class*=text-])]:text-success',
        warning: 'bg-warning/7 ring ring-warning/30 [&_svg:not([class*=text-])]:text-warning',
        tertiary: 'bg-tertiary/7 ring ring-tertiary/30 [&_svg:not([class*=text-])]:text-tertiary',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  },
);

export function Alert({
  className,
  variant,
  ...props
}: React.ComponentProps<'div'> & VariantProps<typeof alertVariants>) {
  return (
    <div
      data-slot="alert"
      className={cn(alertVariants({ variant, className }))}
      {...props}
    />
  );
}

export function AlertTitle({
  className,
  ...props
}: React.ComponentProps<'div'>) {
  return <div data-slot="alert-title" className={cn(className)} {...props} />;
}

export function AlertDescription({
  className,
  ...props
}: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="alert-description"
      className={cn(
        'text-muted font-normal col-start-2 leading-relaxed',
        className,
      )}
      {...props}
    />
  );
}

export function AlertAction({
  className,
  ...props
}: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="alert-action"
      className={cn(
        'ml-auto flex items-center gap-1.5 col-start-3 row-start-1 row-span-2 self-center',
        className,
      )}
      {...props}
    />
  );
}

// packages/ui-svelte/src/components/alert/alert.svelte
<script lang="ts" module>
	import { type VariantProps, tv } from 'tailwind-variants';

	export const alertVariants = tv({
		base: "[--alert-hue:var(--border)] border-[color-mix(in_oklch,var(--alert-hue)_55%,var(--card))] bg-[color-mix(in_oklch,var(--alert-hue)_26%,var(--card))] shadow-[0_3px_0_0_color-mix(in_oklch,var(--alert-hue)_55%,var(--card))] grid gap-0.5 rounded-lg border-2 px-[15px] py-[13px] text-left text-sm has-data-[slot=alert-action]:relative has-data-[slot=alert-action]:pr-18 has-[>svg]:grid-cols-[auto_1fr] has-[>svg]:gap-x-2 *:[svg]:row-span-2 *:[svg]:translate-y-0.5 *:[svg]:text-current *:[svg:not([class*='size-'])]:size-4 group/alert relative w-full",
		variants: {
			variant: {
				default: 'text-card-foreground',
				mint: '[--alert-hue:var(--mint)] *:data-[slot=alert-title]:text-[color-mix(in_oklch,var(--foreground)_55%,var(--mint))]',
				lemon:
					'[--alert-hue:var(--lemon)] *:data-[slot=alert-title]:text-[color-mix(in_oklch,var(--foreground)_55%,var(--lemon))]',
				destructive:
					'[--alert-hue:var(--destructive)] text-foreground *:data-[slot=alert-title]:text-[color-mix(in_oklch,var(--foreground)_45%,var(--destructive))] *:[svg]:text-current'
			}
		},
		defaultVariants: {
			variant: 'default'
		}
	});

	export type AlertVariant = VariantProps<typeof alertVariants>['variant'];
</script>

<script lang="ts">
	import type { HTMLAttributes } from 'svelte/elements';
	import { cn, type WithElementRef } from '../../utils.js';

	let {
		ref = $bindable(null),
		class: className,
		variant = 'default',
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		variant?: AlertVariant;
	} = $props();
</script>

<div
	bind:this={ref}
	data-slot="alert"
	role="alert"
	class={cn(alertVariants({ variant }), className)}
	{...restProps}
>
	{@render children?.()}
</div>
