// packages/ui/src/selia/input-group.tsx
'use client';

import { cn } from '../lib/cn';
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { useRender } from '@base-ui/react/use-render';

export const inputGroupVariants = cva(
  [
    'relative flex flex-wrap transition-all',
    '[&>input,&>[role="combobox"],textarea]:flex-1',
    '[&>input,&>[role="combobox"],textarea]:bg-transparent',
    '[&>input,&>[role="combobox"],textarea]:ring-0',
    '[&>input,&>[role="combobox"],textarea]:shadow-none',
    '[&>input,&>[role="combobox"],textarea]:focus:ring-0',
    'has-[>[data-align^="block"]]:flex-col',
  ],
  {
    variants: {
      variant: {
        default: 'bg-input',
        subtle: 'bg-input/60',
        plain: 'bg-transparent focus:outline-none',
      },
    },
    compoundVariants: [
      {
        variant: ['default', 'subtle'],
        className: [
          'ring ring-input-border hover:ring-input-accent-border shadow-input rounded',
          '[&:has(>input:focus),&:has(>[role="combobox"]:focus),&:has(textarea:focus)]:ring-primary',
          '[&:has(>input:focus),&:has(>[role="combobox"]:focus),&:has(textarea:focus)]:ring-2',
        ],
      },
    ],
    defaultVariants: {
      variant: 'default',
    },
  },
);

export function InputGroup({
  className,
  children,
  variant,
  ...props
}: React.ComponentProps<'div'> & VariantProps<typeof inputGroupVariants>) {
  return (
    <div
      data-slot="input-group"
      className={cn(inputGroupVariants({ variant, className }))}
      {...props}
    >
      {children}
    </div>
  );
}

export const inputGroupAddonVariants = cva(
  [
    'flex items-center gap-1.5 shrink-0',
    '[&_svg:not([class*=size-])]:size-4 [&_svg:not([class*=text-])]:text-dimmed',
    '[&_[role="combobox"]]:not-focus:ring-0',
    '[&_[role="combobox"]]:not-focus:ring-transparent',
    '[&_[role="combobox"]]:shadow-none',
    '[&.items-start,&.items-end]:py-3',
  ],
  {
    variants: {
      align: {
        start: 'not-[:has(>[role="combobox"])]:pl-2.5',
        end: 'not-[:has(>[role="combobox"])]:pr-2.5',
        'block-start': 'px-3.5 pt-3.5',
        'block-end': 'px-3.5 pb-3.5',
      },
    },
    compoundVariants: [
      {
        align: ['start', 'end'],
        className: [
          '[&_button:not([role="combobox"])]:h-7 [&_button:not([role="combobox"])]:px-2',
          'has-[>button:not([role="combobox"])]:-mx-1',
        ],
      },
    ],
    defaultVariants: {
      align: 'start',
    },
  },
);

export function InputGroupAddon({
  className,
  align,
  render,
  ...props
}: useRender.ComponentProps<'div'> &
  VariantProps<typeof inputGroupAddonVariants>) {
  return useRender({
    defaultTagName: 'div',
    render,
    props: {
      'data-slot': 'input-group-addon',
      'data-align': align,
      className: cn(inputGroupAddonVariants({ align, className })),
      ...props,
    },
  });
}

export function InputGroupText({
  className,
  children,
  ...props
}: React.ComponentProps<'span'>) {
  return (
    <span
      data-slot="input-group-text"
      className={cn(
        'inline-flex items-center gap-1.5 text-muted select-none',
        '[&_svg:not([class*=size-])]:size-4 [&_svg:not([class*=text-])]:text-dimmed',
        className,
      )}
      {...props}
    >
      {children}
    </span>
  );
}

// packages/ui-svelte/src/components/input-group/input-group.svelte
<script lang="ts">
	import { cn, type WithElementRef } from '../../utils.js';
	import type { HTMLAttributes } from 'svelte/elements';

	let {
		ref = $bindable(null),
		class: className,
		children,
		...props
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="input-group"
	role="group"
	class={cn(
		'group/input-group border-input has-[[data-slot=input-group-control]:focus-visible]:border-ring has-[[data-slot=input-group-control]:focus-visible]:ring-ring/50 has-[[data-slot][aria-invalid=true]]:ring-destructive/20 has-[[data-slot][aria-invalid=true]]:border-destructive dark:has-[[data-slot][aria-invalid=true]]:ring-destructive/40 has-disabled:bg-muted h-10 rounded-md border-2 bg-card transition-colors in-data-[slot=combobox-content]:focus-within:border-inherit in-data-[slot=combobox-content]:focus-within:ring-0 has-disabled:opacity-50 has-[[data-slot=input-group-control]:focus-visible]:ring-3 has-[[data-slot][aria-invalid=true]]:ring-3 has-[>[data-align=block-end]]:h-auto has-[>[data-align=block-end]]:flex-col has-[>[data-align=block-start]]:h-auto has-[>[data-align=block-start]]:flex-col has-[>[data-align=block-end]]:[&>input]:pt-3 has-[>[data-align=block-start]]:[&>input]:pb-3 has-[>[data-align=inline-end]]:[&>input]:pr-1.5 has-[>[data-align=inline-start]]:[&>input]:pl-1.5 relative flex w-full min-w-0 items-center outline-none has-[>textarea]:h-auto',
		className
	)}
	{...props}
>
	{@render children?.()}
</div>
