// apps/svelte/src/lib/features/thread-experience/components/ComposerHeroState.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { cn } from '$lib/utils';

	/**
	 * Empty-thread hero — brand mark + heading over the rich composer (static `/logo.svg` mark).
	 */
	let {
		title = 'Apa yang ingin kita teliti?',
		logoClass = 'size-12 @2xl:size-14',
		titleClass = 'font-heading text-2xl leading-none font-bold tracking-tight text-foreground @2xl:text-3xl',
		headerClass,
		children,
		hint
	}: {
		title?: string;
		logoClass?: string;
		titleClass?: string;
		headerClass?: string;
		children: Snippet;
		hint?: Snippet;
	} = $props();
</script>

<div class="mx-auto flex w-full max-w-2xl flex-col items-center gap-4 text-center">
	<header
		class={cn('mb-4 flex flex-col items-center justify-center gap-2 text-center', headerClass)}
	>
		<div class="flex items-center justify-center gap-2">
			<img src="/logo.svg" alt="" class={cn('shrink-0', logoClass)} />
			<h1 class={titleClass}>{title}</h1>
		</div>
	</header>
	<div class="w-full">{@render children()}</div>
	{#if hint}
		<p class="max-w-sm text-[11px] leading-5 text-muted-foreground">{@render hint()}</p>
	{/if}
</div>

// apps/app/features/thread-experience/components/composer-hero-state.tsx
import type { ReactNode } from "react";
import { BrandLogoIcon } from "@/components/brand-logo-icon";
import { cn } from "@/lib/utils";

export function ComposerHeroState({
  title = "What story are we telling?",
  logoClassName = "size-8 text-mint",
  titleClassName = "font-heading text-2xl font-bold tracking-tight text-foreground sm:text-3xl leading-none",
  headerClassName,
  children,
  hint,
}: {
  title?: string;
  logoClassName?: string;
  titleClassName?: string;
  headerClassName?: string;
  children: ReactNode;
  hint?: ReactNode;
}) {
  return (
    <div className="flex w-full max-w-2xl flex-col items-center gap-4 text-center">
      <header
        className={cn(
          "mb-4 flex flex-col items-center justify-center gap-2 text-center",
          headerClassName,
        )}
      >
        <div className="flex items-center justify-center gap-2.5">
          <BrandLogoIcon className={logoClassName} />
          <h1 className={titleClassName}>{title}</h1>
        </div>
      </header>
      <div className="w-full">{children}</div>
      {hint ? (
        <p className="max-w-sm text-[11px] leading-5 text-muted-foreground">{hint}</p>
      ) : null}
    </div>
  );
}
