// apps/svelte/src/lib/features/explore/components/ThreadActionsMenu.svelte
<script lang="ts">
	import * as DropdownMenu from '$lib/components/ui/dropdown-menu/index.js';
	import ConfirmDialog from '$lib/components/ConfirmDialog.svelte';
	import { Button } from '$lib/components/ui/button';
	import { Icon, MoreHorizontalIcon, Trash2Icon } from '$lib/icons';

	/**
	 * Per-thread action menu (delete) for the compact chat panel header. Delete only; the sidebar-row pin
	 * variant is handled elsewhere.
	 */
	let { description, onDelete }: { description: string; onDelete: () => Promise<void> } = $props();

	let deleteDialogOpen = $state(false);
</script>

<DropdownMenu.Root>
	<DropdownMenu.Trigger>
		{#snippet child({ props })}
			<Button
				{...props}
				type="button"
				variant="ghost"
				size="icon-sm"
				class="size-8 shrink-0 rounded-full text-muted-foreground"
				aria-label="Aksi thread"
			>
				<Icon icon={MoreHorizontalIcon} class="size-4" />
			</Button>
		{/snippet}
	</DropdownMenu.Trigger>
	<DropdownMenu.Content align="end" class="w-44">
		<DropdownMenu.Item variant="destructive" onclick={() => (deleteDialogOpen = true)}>
			<Icon icon={Trash2Icon} class="size-4" />
			Hapus thread
		</DropdownMenu.Item>
	</DropdownMenu.Content>
</DropdownMenu.Root>
<ConfirmDialog
	open={deleteDialogOpen}
	onOpenChange={(open) => (deleteDialogOpen = open)}
	title="Hapus thread"
	{description}
	confirmLabel="Hapus"
	onConfirm={onDelete}
/>

// apps/app/features/thread-experience/components/thread-actions-menu.tsx
"use client";

import { MoreHorizontalIcon, Trash2Icon } from "lucide-react";
import { useState } from "react";
import { ConfirmDialog } from "@/components/confirm-dialog";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

export function ThreadDeleteActions({
  description,
  onDelete,
}: {
  description: string;
  onDelete: () => Promise<void>;
}) {
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            className="size-8 shrink-0 rounded-full text-muted-foreground"
            aria-label="Aksi thread"
          >
            <MoreHorizontalIcon className="size-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-44">
          <DropdownMenuItem
            variant="destructive"
            onClick={() => setDeleteDialogOpen(true)}
          >
            <Trash2Icon className="size-4" />
            Hapus thread
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
      <ConfirmDialog
        open={deleteDialogOpen}
        onOpenChange={setDeleteDialogOpen}
        title="Hapus thread"
        description={description}
        confirmLabel="Hapus"
        onConfirm={onDelete}
      />
    </>
  );
}
