// apps/svelte/src/lib/features/changelog/components/ChangelogCard.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import CategoryBadge from './CategoryBadge.svelte';
	import ChangelogDateline from './ChangelogDateline.svelte';
	import ChangelogPreview from './ChangelogPreview.svelte';
	import type { ChangelogEntry } from '../types';

	let { entry }: { entry: ChangelogEntry } = $props();
</script>

<!-- Kartu changelog compact (1 kolom, horizontal di desktop): thumbnail kiri, lalu tanggal (aksen) +
     judul + ringkasan + badge di kanan. Seluruh kartu link ke detail — body MDX lengkap di sana. -->
<a
	href={resolve('/(marketing)/changelog/[slug]', { slug: entry.slug })}
	class="group flex flex-col overflow-hidden rounded-2xl border border-border/60 bg-card transition-colors hover:border-border sm:min-h-[8.5rem] sm:flex-row"
>
	<ChangelogPreview
		{entry}
		class="aspect-[16/9] border-b border-border/60 sm:aspect-auto sm:w-52 sm:shrink-0 sm:border-r sm:border-b-0"
	/>

	<div class="flex-1 p-5">
		<ChangelogDateline {entry} class="text-xs" />

		<h2
			class="mt-1.5 text-base font-semibold leading-snug text-foreground transition-colors group-hover:text-foreground/70"
		>
			{entry.title}
		</h2>

		{#if entry.excerpt}
			<p class="mt-1.5 line-clamp-2 text-sm leading-6 text-muted-foreground">
				{entry.excerpt}
			</p>
		{/if}

		{#if entry.categories.length > 0}
			<div class="mt-3 flex flex-wrap gap-1.5">
				{#each entry.categories as category (category)}
					<CategoryBadge {category} />
				{/each}
			</div>
		{/if}
	</div>
</a>

// apps/www/src/components/changelog/changelog-card.tsx
import type { CSSProperties } from "react";

import { CATEGORY_META } from "@/lib/changelog/categories";
import { changelogEase, changelogGutter } from "@/lib/changelog/layout";
import type { ChangelogEntry } from "@/lib/changelog/types";
import { formatDateId } from "@/lib/dates";

function metaLine(entry: ChangelogEntry): string {
  const parts = [formatDateId(entry.publishedAt)];
  if (entry.version) parts.push(`v${entry.version}`);
  if (entry.categories.length > 0) {
    parts.push(
      entry.categories
        .map((c) => CATEGORY_META[c]?.label)
        .filter(Boolean)
        .join(", "),
    );
  }
  return parts.join(" · ");
}

/**
 * Baris changelog — pola sama dengan BlogCard: tanggal/meta, judul, excerpt.
 * Tanpa kartu/thumbnail; hover full-lebar baris.
 */
export function ChangelogCard({
  entry,
  index = 0,
}: {
  entry: ChangelogEntry;
  index?: number;
}) {
  return (
    <a
      href={entry.url}
      style={
        { "--tw-animation-delay": `${Math.min(index, 8) * 60}ms` } as CSSProperties
      }
      className={`group block animate-in fade-in fill-mode-both duration-500 ${changelogGutter} py-5 transition-colors ${changelogEase} hover:bg-muted/40`}
    >
      <p className="text-xs text-muted-foreground">{metaLine(entry)}</p>

      <h2 className="mt-1.5 text-base font-medium leading-snug text-foreground sm:text-[1.0625rem]">
        {entry.title}
      </h2>

      {entry.excerpt ? (
        <p className="mt-1.5 line-clamp-2 max-w-xl text-sm leading-6 text-muted-foreground">
          {entry.excerpt}
        </p>
      ) : null}
    </a>
  );
}
