// apps/svelte/src/routes/app/(product)/projects/[projectId]/artifacts/[artifactId]/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import ArtifactReaderPageShell from '$lib/features/workspaces/components/ArtifactReaderPageShell.svelte';

	// Route params are decoded by SvelteKit; the shell owns the fixed h-svh frame + fetch.
	// The project id IS the workspace id — the reader shell is workspace-scoped underneath.
	const workspaceId = $derived(page.params.projectId ?? '');
	const artifactId = $derived(page.params.artifactId ?? '');
</script>

<ArtifactReaderPageShell {workspaceId} {artifactId} />

// apps/web/app/app/(product)/workspaces/[workspaceId]/artifacts/[artifactId]/page.tsx
import { ArtifactReaderPageShell } from "@/features/workspaces/components/artifact-reader-page-shell";

export default async function ArtifactReaderPage({
  params,
}: {
  params: Promise<{ workspaceId: string; artifactId: string }>;
}) {
  const { workspaceId, artifactId } = await params;
  return <ArtifactReaderPageShell workspaceId={workspaceId} artifactId={artifactId} />;
}
