// apps/svelte/src/lib/features/settings/pages/UsageBillingPage.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Icon, CheckIcon, ExternalLinkIcon, Loader2Icon } from '$lib/icons';
	import { readableApiErrorMessage } from '$lib/errors';
	import { cn } from '$lib/utils';
	import {
		type ProductKey,
		useBillingCurrent,
		useBillingPlans,
		useCancelSubscription,
		useChangeSubscription,
		useCheckout,
		usePortal,
		useUsageActivity
	} from '../api';
	import { formatIdr } from '../lib/format';
	import CreditMeter from '../components/CreditMeter.svelte';
	import UsageChart from '../components/UsageChart.svelte';
	import SettingsHeader from '../components/SettingsHeader.svelte';
	import {
		SettingsPanel,
		SettingsPanelBody,
		SettingsPanelFooter,
		SettingsPanelHeader,
		SettingsPill,
		SettingsSegmentedControl
	} from '../components/settings-card';

	const WINDOWS = [30, 90, 365] as const;

	const billing = useBillingCurrent();
	const plans = useBillingPlans();
	let days = $state<(typeof WINDOWS)[number]>(30);
	const usage = useUsageActivity(() => days);

	const checkout = useCheckout();
	const change = useChangeSubscription();
	const cancel = useCancelSubscription();
	const portal = usePortal();

	const hasSubscription = $derived(billing.data?.canChangeSubscription ?? false);
	const pendingPurchase = $derived(checkout.isPending || change.isPending);

	function onSelectProduct(productKey: ProductKey) {
		if (hasSubscription) change.mutate(productKey);
		else checkout.mutate(productKey);
	}
</script>

<SettingsHeader
	section="usage-billing"
	title="Penggunaan & tagihan"
	description="Kelola paket, pantau kredit, dan buka portal billing."
/>

<!-- Paket aktif + aksi -->
<SettingsPanel>
	<SettingsPanelHeader
		title="Paket aktif"
		description={billing.isPending
			? 'Memuat…'
			: billing.data
				? billing.data.planLabel
				: 'Tidak tersedia'}
	>
		{#snippet action()}
			{#if billing.data}
				<SettingsPill>{billing.data.isAdmin ? 'Admin' : billing.data.status}</SettingsPill>
			{/if}
		{/snippet}
	</SettingsPanelHeader>
	<SettingsPanelBody class="space-y-3">
		{#if billing.isPending}
			<p class="text-[13px] text-muted-foreground">Memuat billing…</p>
		{:else if billing.data}
			<CreditMeter
				creditsUsed={billing.data.creditsUsed}
				creditsLimit={billing.data.creditsLimit}
				creditsRemaining={billing.data.creditsRemaining}
				unlimited={billing.data.isUnlimitedCredits}
				resetAt={billing.data.resetAt}
			/>
		{:else}
			<p class="text-[13px] text-destructive">
				{readableApiErrorMessage(billing.error, 'Tidak dapat memuat billing.')}
			</p>
		{/if}
		{#if billing.data?.cancelAtPeriodEnd}
			<p class="text-[12px] text-coral-foreground">
				Langganan akan berakhir pada akhir periode berjalan.
			</p>
		{/if}
	</SettingsPanelBody>
	{#if billing.data?.billingPortalAvailable || billing.data?.canCancelSubscription}
		<SettingsPanelFooter>
			{#if billing.data?.billingPortalAvailable}
				<Button
					variant="outline"
					size="sm"
					onclick={() => portal.mutate()}
					disabled={portal.isPending}
				>
					{#if portal.isPending}
						<Icon icon={Loader2Icon} class="size-4 animate-spin" />
					{:else}
						<Icon icon={ExternalLinkIcon} class="size-4" />
					{/if}
					Kelola tagihan
				</Button>
			{/if}
			{#if billing.data?.canCancelSubscription}
				<Button
					variant="ghost"
					size="sm"
					onclick={() => cancel.mutate()}
					disabled={cancel.isPending}
				>
					{#if cancel.isPending}
						<Icon icon={Loader2Icon} class="size-4 animate-spin" />
					{/if}
					Batalkan langganan
				</Button>
			{/if}
		</SettingsPanelFooter>
	{/if}
</SettingsPanel>

<!-- Daftar plan + produk -->
<SettingsPanel>
	<SettingsPanelHeader
		title="Paket tersedia"
		description="Pilih paket yang sesuai kebutuhan riset kamu."
	/>
	<SettingsPanelBody>
		{#if plans.isPending}
			<div class="grid gap-3 sm:grid-cols-2">
				{#each [0, 1, 2, 3] as i (i)}
					<div class="h-44 animate-pulse rounded-xl border border-border/60 bg-muted/40"></div>
				{/each}
			</div>
		{:else if !plans.data}
			<p class="text-[13px] text-destructive">
				{readableApiErrorMessage(plans.error, 'Tidak dapat memuat daftar paket.')}
			</p>
		{:else}
			<div class="grid gap-3 sm:grid-cols-2">
				{#each plans.data as plan (plan.key)}
					{@const isCurrent = billing.data?.planKey === plan.key}
					<div
						class={cn(
							'flex flex-col gap-3 rounded-xl border bg-card p-4',
							isCurrent ? 'border-primary/50 ring-1 ring-primary/20' : 'border-border/70'
						)}
					>
						<div class="flex items-start justify-between gap-2">
							<div class="min-w-0">
								<p class="text-[14px] font-semibold tracking-tight text-foreground">
									{plan.label}
								</p>
								<p class="mt-0.5 text-[12px] text-muted-foreground">
									{formatIdr(plan.monthlyPriceIdr)}{plan.monthlyPriceIdr > 0 ? '/bln' : ''}
								</p>
							</div>
							{#if isCurrent}
								<SettingsPill class="border-primary/40 text-primary">Saat ini</SettingsPill>
							{/if}
						</div>

						<ul class="space-y-1.5 text-[12px] text-muted-foreground">
							{#each plan.features as f (f)}
								<li class="flex items-start gap-2">
									<Icon icon={CheckIcon} class="mt-0.5 size-3.5 shrink-0 text-primary" />
									{f}
								</li>
							{/each}
						</ul>

						{#if plan.products.length > 0}
							<div class="mt-auto flex flex-col gap-2 pt-1">
								{#each plan.products as product (product.key)}
									<Button
										variant={product.interval === 'month' ? 'default' : 'outline'}
										size="sm"
										disabled={!product.configured ||
											pendingPurchase ||
											(isCurrent && product.key === billing.data?.productKey)}
										onclick={() => onSelectProduct(product.key)}
									>
										{#if pendingPurchase}
											<Icon icon={Loader2Icon} class="size-4 animate-spin" />
										{/if}
										{`${formatIdr(product.displayPriceIdr)}/${product.interval === 'month' ? 'bln' : 'thn'}`}{!product.configured
											? ' (belum tersedia)'
											: ''}
									</Button>
								{/each}
							</div>
						{:else}
							<p class="mt-auto text-[12px] text-muted-foreground">
								Paket dasar — tidak perlu pembayaran.
							</p>
						{/if}
					</div>
				{/each}
			</div>
		{/if}
	</SettingsPanelBody>
</SettingsPanel>

<!-- Usage timeseries dengan toggle window -->
<SettingsPanel>
	<SettingsPanelHeader title="Penggunaan" description="Kredit terpakai per hari">
		{#snippet action()}
			<SettingsSegmentedControl>
				{#each WINDOWS as w (w)}
					{@const active = days === w}
					<button
						type="button"
						onclick={() => (days = w)}
						class={cn(
							'rounded-md px-2.5 py-1 text-[12px] font-medium transition-colors duration-150',
							active
								? 'border border-border/40 bg-card text-foreground'
								: 'text-muted-foreground hover:text-foreground'
						)}
					>
						{w}h
					</button>
				{/each}
			</SettingsSegmentedControl>
		{/snippet}
	</SettingsPanelHeader>
	<SettingsPanelBody>
		{#if usage.isPending}
			<p class="text-[13px] text-muted-foreground">Memuat penggunaan…</p>
		{:else if usage.data}
			<UsageChart days={usage.data} />
		{:else}
			<p class="text-[13px] text-muted-foreground">Tidak dapat memuat penggunaan.</p>
		{/if}
	</SettingsPanelBody>
</SettingsPanel>

// apps/web/features/settings/pages/usage-billing-page.tsx
"use client";

import { Loader2Icon, XCircleIcon } from "@aqsha/ui/icons";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { useSettingsUsageBillingData } from "../api/use-settings-usage-billing-data";
import {
  PlanBillingRow,
  PlanIntervalSelector,
  type BillingInterval,
} from "../components/billing-plan-controls";
import { LoadingSettingsPage } from "../components/loading-settings-page";
import {
  CreditsUsageSection,
  SettingsPanel,
  SettingsPanelBody,
  SettingsPanelHeader,
  SettingsSegmentedControl,
  SettingsSummaryCard,
} from "../components/settings-card";
import { SettingsHeader } from "../components/settings-header";
import { UsageHeatmap } from "../components/usage-heatmap";
import { formatShortDate } from "../lib/settings-format";
import { formatPlanPrice, formatProviderSpend, usagePercentage } from "../utils/settings-summary";

export function SettingsUsageBillingPage({
  checkoutStatus,
}: {
  checkoutStatus?: string;
}) {
  const data = useSettingsUsageBillingData();
  const [billingInterval, setBillingInterval] = useState<BillingInterval>("month");
  const current = data.current;
  const plans = data.plans;
  const activity = data.activity;
  const checkoutNotice =
    checkoutStatus === "success"
      ? "Checkout berhasil dikembalikan. Status langganan diperbarui setelah webhook Polar diterima."
      : null;
  const checkoutError =
    checkoutStatus === "error" ? "Checkout dibatalkan atau gagal diproses." : null;
  const billingNoticeMessage = data.billingNotice ?? checkoutNotice;
  const billingErrorMessage = data.billingError ?? checkoutError;

  useEffect(() => {
    if (billingNoticeMessage) toast.success(billingNoticeMessage);
  }, [billingNoticeMessage]);

  useEffect(() => {
    if (billingErrorMessage) toast.error(billingErrorMessage);
  }, [billingErrorMessage]);

  if (!current || !plans || !activity) return <LoadingSettingsPage />;

  const usagePercent = usagePercentage(current);

  return (
    <>
      <SettingsHeader section="usage-billing" title="Penggunaan & tagihan" />

      <div className="grid gap-4 sm:grid-cols-2">
        <SettingsSummaryCard
          label="Paket saat ini"
          footer={
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={data.openPortal}
              disabled={!current.billingPortalAvailable || data.pendingKey === "portal"}
              className="h-9 w-fit rounded-lg text-[13px]"
            >
              {data.pendingKey === "portal" ? (
                <Loader2Icon className="size-3.5 animate-spin" />
              ) : null}
              {current.isAdmin ? "Kelola langganan" : "Sesuaikan paket"}
            </Button>
          }
        >
          <div>
            <div className="flex flex-wrap items-baseline gap-2">
              <h3 className="text-base font-semibold tracking-tight text-foreground">
                {current.planLabel}
              </h3>
              <span className="rounded-md border border-border/50 bg-muted/50 px-2 py-0.5 text-[12px] text-muted-foreground">
                {formatPlanPrice(plans, current.planKey)}
              </span>
            </div>
            <p className="mt-1.5 text-[13px] text-muted-foreground">
              Reset {formatShortDate(current.resetAt)}
            </p>
            {current.currentPeriodEnd ? (
              <p className="mt-1 text-[12px] text-muted-foreground">
                Periode berakhir {formatShortDate(current.currentPeriodEnd)}
              </p>
            ) : null}
          </div>
        </SettingsSummaryCard>

        <SettingsSummaryCard
          label="Status langganan"
          footer={
            current.canCancelSubscription ? (
              <Button
                type="button"
                variant="destructive"
                size="sm"
                onClick={data.cancelPlan}
                disabled={data.pendingKey === "cancel"}
                className="h-9 w-fit rounded-lg text-[13px]"
              >
                {data.pendingKey === "cancel" ? (
                  <Loader2Icon className="size-3.5 animate-spin" />
                ) : (
                  <XCircleIcon className="size-3.5" />
                )}
                Batalkan perpanjangan
              </Button>
            ) : null
          }
        >
          <div>
            <h3 className="text-base font-semibold tracking-tight text-foreground">
              {current.cancelAtPeriodEnd
                ? "Berhenti di akhir periode"
                : current.status}
            </h3>
            <p className="mt-1.5 text-[13px] text-muted-foreground">
              {current.isAdmin
                ? "Admin internal tidak muncul sebagai produk publik."
                : current.billingInterval
                  ? `Billing ${current.billingInterval === "year" ? "tahunan" : "bulanan"}`
                  : "Belum ada langganan aktif."}
            </p>
          </div>
        </SettingsSummaryCard>
      </div>

      <SettingsPanel>
        <SettingsPanelHeader
          title="Paket publik"
          description="Free, Starter, dan Plus adalah produk publik. Admin tetap override internal."
        />
        <SettingsPanelBody className="grid gap-4">
          <PlanIntervalSelector value={billingInterval} onChange={setBillingInterval} />
          <div className="grid gap-3">
            {plans.map((plan) => (
              <PlanBillingRow
                key={plan.key}
                plan={plan}
                interval={billingInterval}
                current={current}
                pendingKey={data.pendingKey}
                onCheckout={data.openCheckout}
                onChangePlan={data.changePlan}
              />
            ))}
          </div>
        </SettingsPanelBody>
      </SettingsPanel>

      <SettingsPanel>
        <SettingsPanelHeader title={`Termasuk di ${current.planLabel}`} />
        <SettingsPanelBody>
          <CreditsUsageSection
            isUnlimitedCredits={current.isUnlimitedCredits}
            usagePercent={usagePercent}
            creditsUsed={current.creditsUsed}
            creditsRemaining={current.creditsRemaining}
            creditsLimit={current.creditsLimit}
            unlimitedLabel="Penggunaan tercatat"
            billingLimitedLabel="Total"
          />
        </SettingsPanelBody>
      </SettingsPanel>

      <SettingsPanel>
        <SettingsPanelHeader
          title="Batas pengeluaran provider"
          description="Aqsha memblokir panggilan provider baru sebelum batas ini terlampaui."
        />
        <SettingsPanelBody className="grid gap-4 sm:grid-cols-2">
          <div>
            <p className="text-[13px] font-medium text-foreground">Estimasi biaya provider</p>
            <p className="mt-2 text-sm font-semibold text-foreground">
              {formatProviderSpend(current)}
            </p>
          </div>
          <div>
            <p className="text-[13px] font-medium text-foreground">Pengeluaran on-demand</p>
            <p className="mt-0.5 text-[12px] text-muted-foreground">
              Penggunaan di luar paket bulanan dinonaktifkan di v1.
            </p>
            <span className="mt-2 inline-block rounded-md border border-border/50 bg-muted/60 px-2.5 py-1 font-mono text-[11px] text-muted-foreground">
              Nonaktif
            </span>
          </div>
        </SettingsPanelBody>
      </SettingsPanel>

      <SettingsPanel>
        <SettingsPanelHeader title="Aktivitas" />
        <SettingsPanelBody className="grid gap-4">
          <SettingsSegmentedControl>
            {([30, 90, 365] as const).map((days) => (
              <button
                key={days}
                type="button"
                onClick={() => data.setUsageRangeDays(days)}
                className={`rounded-md px-3 py-1.5 text-[12px] font-medium ${
                  data.usageRangeDays === days
                    ? "bg-card text-foreground"
                    : "text-muted-foreground hover:text-foreground"
                }`}
              >
                {days} hari
              </button>
            ))}
          </SettingsSegmentedControl>
          <UsageHeatmap rows={activity} />
        </SettingsPanelBody>
      </SettingsPanel>
    </>
  );
}
