// apps/web-v2/components/nav-user.tsx
"use client";

import { useClerk } from "@clerk/nextjs";
import { useRouter } from "next/navigation";
import Link from "next/link";
import {
  LogOutIcon,
  MoreVerticalIcon,
  SettingsIcon,
} from "@aqsha/ui/icons";
import { ThemeMenuSub } from "@/components/theme-toggle";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from "@/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from "@/components/ui/sidebar";
import { useViewerDisplay } from "@/lib/use-viewer-identity";

type Viewer = {
  name: string | null;
  email: string | null;
  image: string | null;
};

export function NavUser({ user }: { user: Viewer | undefined }) {
  const router = useRouter();
  const { signOut: clerkSignOut } = useClerk();
  const { isMobile } = useSidebar();
  const { name, email, image, initials } = useViewerDisplay(user, {
    name: "Aqsha user",
    email: "Signed in",
  });

  const signOut = async () => {
    await clerkSignOut({ redirectUrl: "/sign-in" });
    router.replace("/sign-in");
    router.refresh();
  };

  const menuItemClass =
    "h-9 gap-2 rounded-[8px] px-2 text-[13px] font-medium text-popover-foreground [&_svg]:size-4 [&_svg]:text-muted-foreground";

  return (
    <SidebarMenu>
      <SidebarMenuItem>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <SidebarMenuButton
              size="lg"
              className="h-10 min-w-0 rounded-[8px] border border-sidebar-border/70 bg-muted/15 p-2.5 text-muted-foreground transition-[background-color,border-color,color] duration-150 ease-out hover:border-primary/20 hover:bg-primary/5 hover:text-foreground data-[state=open]:border-primary/25 data-[state=open]:bg-primary/8 data-[state=open]:text-foreground"
            >
              <Avatar className="size-6 shrink-0 rounded-full ring-1 ring-sky-soft-border">
                {image ? <AvatarImage src={image} alt={name} /> : null}
                <AvatarFallback className="rounded-full bg-sky-soft text-[10px] font-semibold text-sky-foreground">
                  {initials}
                </AvatarFallback>
              </Avatar>
              <span className="min-w-0 flex-1 truncate text-left text-[12px] font-medium">
                {name}
              </span>
              <MoreVerticalIcon className="size-3.5 shrink-0 text-muted-foreground" />
            </SidebarMenuButton>
          </DropdownMenuTrigger>
          <DropdownMenuContent
            className="w-(--radix-dropdown-menu-trigger-width) min-w-64 rounded-[12px] p-1.5"
            side={isMobile ? "bottom" : "right"}
            align="end"
            sideOffset={4}
          >
            <DropdownMenuLabel className="p-2 font-normal">
              <div className="flex min-w-0 items-center gap-2">
                <Avatar className="size-8 rounded-full ring-1 ring-sky-soft-border">
                  {image ? <AvatarImage src={image} alt={name} /> : null}
                  <AvatarFallback className="rounded-full bg-sky-soft text-xs font-semibold text-sky-foreground">
                    {initials}
                  </AvatarFallback>
                </Avatar>
                <div className="grid min-w-0 gap-0.5">
                  <span className="truncate text-[13px] font-semibold text-popover-foreground">
                    {name}
                  </span>
                  <span className="truncate text-[11px] font-medium text-muted-foreground">
                    {email}
                  </span>
                </div>
              </div>
            </DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem asChild className={menuItemClass}>
              <Link href="/app/settings/overview">
                <SettingsIcon />
                <span className="truncate">Pengaturan</span>
              </Link>
            </DropdownMenuItem>
            <ThemeMenuSub />
            <DropdownMenuSeparator />
            <DropdownMenuItem onSelect={signOut} className={menuItemClass}>
              <LogOutIcon />
              <span className="truncate">Sign out</span>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </SidebarMenuItem>
    </SidebarMenu>
  );
}

// apps/web/src/lib/components/layout/NavUser.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import * as Avatar from '@aqsha/ui-svelte/components/avatar';
	import * as DropdownMenu from '@aqsha/ui-svelte/components/dropdown-menu';
	import * as Sidebar from '$lib/components/ui/sidebar/index.js';
	import { compactMenuItemClass } from '@aqsha/ui-svelte/recipes';
	import ThemeMenuSub from './ThemeMenuSub.svelte';
	import { Icon, LogOutIcon, MoreVerticalIcon, SettingsIcon } from '$lib/icons';
	import { getSignOut, viewerContext } from '$lib/auth';

	/**
	 * User menu in the sidebar footer. Avatar trigger → dropdown with profile header, Settings
	 * link, theme submenu, sign out. Viewer display resolves from `viewerContext` (Clerk-backed);
	 * sign out uses the Clerk seam then re-runs load via `goto(..., { invalidateAll })`.
	 */
	const sidebar = Sidebar.useSidebar();
	const viewer = viewerContext.get();
	const display = $derived(viewer.display({ name: 'Aqsha user', email: 'Signed in' }));

	// Captured at init (getContext is init-only) so the handler reads a fresh, non-null clerk.
	const clerkSignOut = getSignOut();

	async function signOut() {
		await clerkSignOut();
		await goto(resolve('/(auth)/sign-in'), { invalidateAll: true });
	}
</script>

<Sidebar.Menu class="group-data-[collapsible=icon]:items-center">
	<Sidebar.MenuItem>
		<DropdownMenu.Root>
			<DropdownMenu.Trigger>
				{#snippet child({ props })}
					<Sidebar.MenuButton
						{...props}
						size="lg"
						class="h-10 min-w-0 rounded-sm border border-sidebar-border/70 bg-muted/15 p-2.5 text-muted-foreground transition-[background-color,border-color,color] duration-150 ease-out hover:border-primary/20 hover:bg-primary/5 hover:text-foreground data-[state=open]:border-primary/25 data-[state=open]:bg-primary/8 data-[state=open]:text-foreground group-data-[collapsible=icon]:size-8! group-data-[collapsible=icon]:justify-center"
					>
						<Avatar.Root class="size-6 shrink-0 rounded-full ring-1 ring-sky-soft-border">
							{#if display.image}
								<Avatar.Image src={display.image} alt={display.name} />
							{/if}
							<Avatar.Fallback
								class="rounded-full bg-sky-soft text-[10px] font-semibold text-sky-foreground"
							>
								{display.initials}
							</Avatar.Fallback>
						</Avatar.Root>
						<span
							class="min-w-0 flex-1 truncate text-left text-[12px] font-medium group-data-[collapsible=icon]:hidden"
						>
							{display.name}
						</span>
						<Icon
							icon={MoreVerticalIcon}
							class="size-3.5 shrink-0 text-muted-foreground group-data-[collapsible=icon]:hidden"
						/>
					</Sidebar.MenuButton>
				{/snippet}
			</DropdownMenu.Trigger>
			<DropdownMenu.Content
				class="w-(--bits-floating-anchor-width) min-w-64 rounded-md p-1.5"
				side={sidebar.isMobile ? 'bottom' : 'right'}
				align="end"
				sideOffset={4}
			>
				<DropdownMenu.Label class="p-2 font-normal">
					<div class="flex min-w-0 items-center gap-2">
						<Avatar.Root class="size-8 rounded-full ring-1 ring-sky-soft-border">
							{#if display.image}
								<Avatar.Image src={display.image} alt={display.name} />
							{/if}
							<Avatar.Fallback
								class="rounded-full bg-sky-soft text-xs font-semibold text-sky-foreground"
							>
								{display.initials}
							</Avatar.Fallback>
						</Avatar.Root>
						<div class="grid min-w-0 gap-0.5">
							<span class="truncate text-[13px] font-semibold text-popover-foreground">
								{display.name}
							</span>
							<span class="truncate text-label font-medium text-muted-foreground">
								{display.email}
							</span>
						</div>
					</div>
				</DropdownMenu.Label>
				<DropdownMenu.Separator />
				<DropdownMenu.Item class={compactMenuItemClass}>
					{#snippet child({ props })}
						<a href={resolve('/app/settings/overview')} {...props}>
							<Icon icon={SettingsIcon} />
							<span class="truncate">Pengaturan</span>
						</a>
					{/snippet}
				</DropdownMenu.Item>
				<ThemeMenuSub />
				<DropdownMenu.Separator />
				<DropdownMenu.Item class={compactMenuItemClass} onSelect={signOut}>
					<Icon icon={LogOutIcon} />
					<span class="truncate">Sign out</span>
				</DropdownMenu.Item>
			</DropdownMenu.Content>
		</DropdownMenu.Root>
	</Sidebar.MenuItem>
</Sidebar.Menu>
