// apps/web/features/thread-experience/components/mastra-chat-thread-surface.tsx
"use client";

import { Button } from "@aqsha/ui";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { m, useReducedMotion } from "motion/react";
import { useMemo, useRef, useState } from "react";
import { ChevronRightIcon } from "@aqsha/ui/icons";
import { ConversationContent } from "@/components/ai-elements/conversation-content";
import { Conversation } from "@/components/ai-elements/conversation-root";
import { ConversationScrollButton } from "@/components/ai-elements/conversation-scroll-button";
import { HomeExploreBento } from "@/features/discovery/components/home-explore-bento";
import {
  usePinnedThreads,
  useSendStatus,
  useThread,
  useThreadArtifacts,
  useThreadsList,
  useThreadSources,
} from "@/features/threads/api";
import {
  Composer,
  type ComposerNotice,
  type ComposerSendPayload,
  type RecentThread,
} from "@/features/threads/components/composer";
import { MessageList } from "@/features/threads/components/message-list";
import { QuestionsCard } from "@/features/threads/components/questions-card";
import { bucketMessageAttachments } from "@/features/threads/lib/attachment-buckets";
import { type AgentKind, ASTRA_AGENT_ID, useMastraClient } from "@/features/threads/lib/mastra-client";
import type { TimelineMessage } from "@/features/threads/lib/timeline-types";
import { buildThreadPanelLookups } from "@/features/threads/lib/thread-panel-data";
import { mastraMessagesToTimeline } from "@/features/threads/lib/mastra-timeline";
import { useMastraAgent } from "@/features/threads/lib/use-mastra-agent";
import type { ResearchSource } from "@/features/threads/types";
import { threadTitle } from "@/features/threads/types";
import { queryKeys } from "@/lib/api-query";
import { panelBodyPaddingClass, threadTranscriptColumnClass } from "@/lib/panel-surface";
import { cn } from "@/lib/utils";
import type { ContextRef } from "@aqsha/chat-core";
import { useAmbientContextRefs } from "./composer-context-mentions";
import { useRegisterThreadPanelData, useThreadPanel } from "./thread-panel-context";
import { LIVE_PLAN_KEY } from "../utils/thread-panel-model";
import { ComposerHeroState } from "./composer-hero-state";
import { ExploreHandwrittenCue } from "./explore-handwritten-cue";
import { CenteredLoading } from "./shared";

const HOME_EASE_OUT = [0.23, 1, 0.32, 1] as const;

/** Map status kirim terblok → notice composer (billing return-union / cooldown). */
function blockedNotice(status: ReturnType<typeof useSendStatus>["data"]): ComposerNotice | null {
  if (!status || status.canSend) return null;
  switch (status.reason) {
    case "cooldown":
      return { message: "Terlalu cepat. Tunggu sebentar sebelum mengirim lagi.", retryAt: status.retryAt };
    case "quota_exceeded":
      return { message: "Kredit chat bulan ini sudah habis. Tingkatkan paket atau tunggu reset." };
    case "subscription_required":
      return { message: "Fitur ini butuh paket berbayar. Tingkatkan paket untuk melanjutkan." };
    case "billing_inactive":
      return { message: "Langganan tidak aktif. Perbarui pembayaran untuk melanjutkan." };
    default:
      return { message: "Pengiriman sedang tidak tersedia." };
  }
}

/** Teks user terakhir di timeline (untuk regenerate). */
function lastUserText(messages: readonly TimelineMessage[]): string | null {
  for (let i = messages.length - 1; i >= 0; i -= 1) {
    const msg = messages[i];
    if (msg?.role !== "user") continue;
    const text = msg.parts
      .filter((p) => p.kind === "text")
      .map((p) => (p as { text: string }).text)
      .join("\n")
      .trim();
    return text || null;
  }
  return null;
}

/**
 * Surface chat runtime MASTRA — komposisi V1 (composer KAYA + landing hero + explore bento)
 * di atas `useMastraAgent`. Mastra Memory (server) = SoT pesan; `@mastra/client-js` menangani
 * stream + persist; thread id ditentukan klien (Mastra mengizinkannya), jadi URL di-bump SEGERA
 * saat kirim pertama (tanpa discovery race ala eve). HITL = kartu approval tool. Sumber riset
 * tetap via API `research_sources` (panel terpisah).
 */
export function MastraChatThreadSurface({
  threadId,
  isLoading,
  compact = false,
  seed,
}: {
  threadId?: string;
  isLoading?: boolean;
  compact?: boolean;
  seed?: string;
}) {
  // Thread baru: id klien-side stabil (Mastra mengizinkan klien menentukan thread id).
  const [newThreadId] = useState(() =>
    typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID() : `t-${Date.now()}`,
  );
  const effectiveThreadId = threadId ?? newThreadId;

  const client = useMastraClient();
  const { data: historyMessages, isLoading: historyLoading } = useQuery({
    queryKey: ["mastra", "thread-messages", threadId],
    enabled: Boolean(threadId),
    queryFn: async () => {
      const thread = client.getMemoryThread({ threadId: threadId!, agentId: ASTRA_AGENT_ID });
      const res = await thread.listMessages();
      return mastraMessagesToTimeline(res.messages ?? []);
    },
  });

  if (isLoading || (threadId && historyLoading)) {
    return <CenteredLoading label="Memuat thread..." />;
  }

  return (
    <MastraChatInner
      key={effectiveThreadId}
      threadId={effectiveThreadId}
      isExistingThread={Boolean(threadId)}
      seed={historyMessages ?? []}
      compact={compact}
      initialContent={seed}
    />
  );
}

function MastraChatInner({
  threadId,
  isExistingThread,
  seed,
  compact,
  initialContent,
}: {
  threadId: string;
  isExistingThread: boolean;
  seed: TimelineMessage[];
  compact: boolean;
  initialContent?: string;
}) {
  // Tier TERSIMPAN thread (`chat_threads.agent_kind`) dibaca SEKALI di sini, gated ke thread existing
  // (thread baru = id klien tanpa baris server → tak ada GET 404). Diteruskan ke `useMastraAgent`
  // (seed channel agent untuk langganan/regenerate/approval) dan ke `Composer` (default selektor).
  const threadDetail = useThread(threadId, isExistingThread);
  const threadAgentKind: AgentKind = threadDetail.data?.agentKind === "pro" ? "pro" : "lite";
  const agent = useMastraAgent({ threadId, seedMessages: seed, initialAgentKind: threadAgentKind });
  const sendStatus = useSendStatus();
  const qc = useQueryClient();
  const ambientContextRefs = useAmbientContextRefs();
  const boundRef = useRef(isExistingThread);

  const busy = agent.status !== "ready";
  const notice = blockedNotice(sendStatus.data);
  const blocked = notice !== null;
  const isEmpty = agent.messages.length === 0 && !busy;

  // Sumber riset `/deep` (research_sources, citation_number) → dikelompokkan per turn (runId) untuk
  // dirender di bawah jawaban (G4). Fetch saat thread mapan (ready + ada pesan) → hindari 404 thread
  // baru; invalidasi otomatis saat run deep selesai (lihat useMastraAgent).
  const { data: sources } = useThreadSources(threadId, !busy && agent.messages.length > 0);
  const sourcesByTurn = useMemo(() => {
    const map = new Map<string, ResearchSource[]>();
    for (const s of sources ?? []) {
      if (s.citationNumber == null) continue;
      const list = map.get(s.turnId);
      if (list) list.push(s);
      else map.set(s.turnId, [s]);
    }
    return map;
  }, [sources]);

  // Lampiran upload thread → dipetakan ke pesan user (join sisi-baca thread↔waktu) supaya berkas
  // yang dikirim user tampil sebagai kartu di message row. Poll selama ada index `pending`.
  const { data: threadArtifacts } = useThreadArtifacts(
    agent.messages.length > 0 ? threadId : null,
    { pollWhilePending: true },
  );
  // React Compiler (next.config `reactCompiler: true`) meng-cache turunan ini — recompute hanya saat
  // input berubah, jadi tak perlu memo manual. Scan-nya kecil (O(pesan-user × upload), array mungil).
  const attachmentsByMessage = bucketMessageAttachments(agent.messages, threadArtifacts);

  const threadPanel = useThreadPanel();

  // Id-keyed detail lookups for the right-side panels (sources / search / step / plan).
  // The surface owns the parsed timeline + DB sources + plan gate, so it builds them
  // here and publishes them to `ThreadPanelProvider`; no-op in compact panels (no
  // provider). While the plan gate is live, the panel mirrors its Setujui/Tolak actions.
  const { messages: agentMessages, planGate, resolvePlan, askGate, resolveAsk } = agent;
  const panelLookups = useMemo(() => {
    const lookups = buildThreadPanelLookups(agentMessages, sources, planGate, askGate);
    // While a plan gate is live, mirror its Setujui/Tolak into the live plan entry so the
    // panel opened from the gate card carries the same actions.
    const livePlan = planGate ? lookups.plans.get(LIVE_PLAN_KEY) : undefined;
    if (livePlan) {
      lookups.plans.set(LIVE_PLAN_KEY, {
        ...livePlan,
        resolve: (approve: boolean) => void resolvePlan(approve),
      });
    }
    // While an ask gate is live, inject resolve/skip so the panel form submits the same answers.
    if (lookups.ask) {
      lookups.ask = {
        ...lookups.ask,
        resolve: (resume) => void resolveAsk(resume),
        skip: () => void resolveAsk({ action: "skipped" }),
      };
    }
    return lookups;
  }, [agentMessages, sources, planGate, resolvePlan, askGate, resolveAsk]);
  useRegisterThreadPanelData(panelLookups);

  // Kirim pertama dari thread baru → bump URL ke /app/threads/<id> (history.replaceState, tanpa
  // navigasi Next → komponen tetap mounted) supaya refresh me-resume thread. Klien sudah tahu id.
  const bumpUrl = () => {
    if (!boundRef.current && typeof window !== "undefined") {
      boundRef.current = true;
      // Preserve the query string (nuqs `?panel=` detail-panel state) — bumping to a
      // bare path would strip an open panel from the URL while nuqs React state still
      // holds it, desyncing them and closing the panel on the next refresh.
      window.history.replaceState(
        window.history.state,
        "",
        `/app/threads/${threadId}${window.location.search}`,
      );
    }
  };

  const onComposerSend = (payload: ComposerSendPayload) => {
    bumpUrl();
    const run =
      payload.command === "deep"
        ? agent.sendDeep(
            payload.text,
            payload.clientContext,
            payload.richText,
            payload.attachmentIds,
            payload.agentKind,
          )
        : agent.send(
            payload.text,
            payload.clientContext,
            payload.richText,
            payload.attachmentIds,
            payload.agentKind,
          );
    void run.then(() => {
      void qc.invalidateQueries({ queryKey: queryKeys.threads.sendStatus() });
    });
  };

  const regenerate = () => {
    void agent.regenerate();
  };

  const approvalCards =
    agent.approvals.length > 0 ? (
      <div className={cn(threadTranscriptColumnClass, "flex flex-col gap-2")}>
        {agent.approvals.map((a) => (
          <div
            key={a.toolCallId}
            className="rounded-lg border border-border bg-card p-3 text-sm"
          >
            <p className="mb-2 text-foreground">
              {a.title}
              {typeof a.args.artifactId === "string" ? ` — ${a.args.artifactId}` : ""}? Setujui untuk
              menjalankan.
            </p>
            <div className="flex gap-2">
              <Button size="sm" onClick={() => void agent.approve(a.toolCallId)}>
                Setujui
              </Button>
              <Button size="sm" variant="ghost" onClick={() => void agent.decline(a.toolCallId)}>
                Tolak
              </Button>
            </div>
          </div>
        ))}
      </div>
    ) : null;

  // Kartu klarifikasi (`ask_questions`) — HITL Questions di atas composer (chat tool-suspend ATAU
  // /deep step clarify). Header punya aksi buka panel; jawab inline atau di panel kanan.
  const questionsCard = agent.askGate ? (
    <div className={cn(threadTranscriptColumnClass)}>
      <QuestionsCard
        questions={agent.askGate.questions}
        onSubmit={(resume) => void agent.resolveAsk(resume)}
        onSkip={() => void agent.resolveAsk({ action: "skipped" })}
        onOpenPanel={threadPanel?.openQuestionsPanel}
      />
    </div>
  ) : null;

  // Plan-gate `/deep` (Workflow suspended di `approve-plan`) — kartu rencana HITL. BUKAN collapsible:
  // kartu statis (judul + ringkasan + Setujui/Tolak). Header bisa diklik → buka panel rencana penuh
  // (sub-pertanyaan + aksi yang sama), bukan expand inline. Dirender DI ATAS composer (sejajar approvalCards).
  const planGateCard = agent.planGate ? (
    <div className={cn(threadTranscriptColumnClass)}>
      <div className="rounded-xl border border-border bg-card p-4">
        {threadPanel?.openPlanPanel ? (
          <button
            type="button"
            onClick={() => threadPanel.openPlanPanel(LIVE_PLAN_KEY)}
            className="group -m-1 flex w-full items-start justify-between gap-3 rounded-lg p-1 text-left transition-colors hover:bg-muted/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            <div className="grid min-w-0 gap-1">
              <span className="text-sm font-semibold text-foreground">Rencana riset</span>
              <span className="text-[13px] text-muted-foreground">
                {`${agent.planGate.subQuestions.length} sub-pertanyaan riset · ketuk untuk lihat detail`}
              </span>
            </div>
            <ChevronRightIcon className="mt-0.5 size-4 shrink-0 text-muted-foreground/60 transition-colors group-hover:text-muted-foreground" />
          </button>
        ) : (
          <div className="grid gap-1">
            <span className="text-sm font-semibold text-foreground">Rencana riset</span>
            <span className="text-[13px] text-muted-foreground">
              {`${agent.planGate.subQuestions.length} sub-pertanyaan riset · tinjau sebelum menyetujui`}
            </span>
          </div>
        )}
        <div className="mt-3 flex gap-2">
          <Button size="sm" onClick={() => void agent.resolvePlan(true)}>
            Setujui
          </Button>
          <Button size="sm" variant="ghost" onClick={() => void agent.resolvePlan(false)}>
            Tolak
          </Button>
        </div>
      </div>
    </div>
  ) : null;

  if (isEmpty) {
    return (
      <MastraComposerLanding
        compact={compact}
        initialContent={initialContent}
        ambientContextRefs={ambientContextRefs}
        busy={busy}
        disabled={blocked}
        notice={notice}
        threadId={threadId}
        threadAgentKind={threadAgentKind}
        errorDraft={agent.error ? lastUserText(agent.messages) : null}
        onSend={onComposerSend}
        onStop={agent.stop}
      />
    );
  }

  return (
    <div className="flex h-full min-h-0 w-full flex-col">
      <Conversation className="flex-1">
        <ConversationContent className="max-w-none p-0">
          <div className={cn(threadTranscriptColumnClass, "flex flex-col gap-4 pt-3 pb-8")}>
            <MessageList
              messages={agent.messages}
              pending={agent.status === "submitted"}
              busy={busy}
              sourcesByTurn={sourcesByTurn}
              attachmentsByMessage={attachmentsByMessage}
              onRegenerate={regenerate}
            />
            {agent.error ? <p className="text-red-500 text-sm">{agent.error.message}</p> : null}
          </div>
        </ConversationContent>
        <ConversationScrollButton />
      </Conversation>
      <div className={cn(threadTranscriptColumnClass, "flex flex-col gap-2.5 pt-2.5 pb-4")}>
        {questionsCard}
        {planGateCard}
        {approvalCards}
        <Composer
          onSend={onComposerSend}
          onStop={agent.stop}
          busy={busy}
          disabled={blocked}
          notice={notice}
          threadId={threadId}
          threadAgentKind={threadAgentKind}
          ambientContextRefs={ambientContextRefs}
          errorDraft={agent.error ? lastUserText(agent.messages) : null}
        />
      </div>
    </div>
  );
}

/** Landing /app identik V1 — hero + composer kaya + explore bento. */
function MastraComposerLanding({
  compact,
  initialContent,
  ambientContextRefs,
  busy,
  disabled,
  notice,
  threadId,
  threadAgentKind,
  errorDraft,
  onSend,
  onStop,
}: {
  compact: boolean;
  initialContent?: string;
  ambientContextRefs?: ContextRef[];
  busy: boolean;
  disabled: boolean;
  notice: ComposerNotice | null;
  // D6: threadId client-generated (effectiveThreadId) → izinkan lampiran di pesan pertama.
  threadId: string;
  threadAgentKind: AgentKind;
  errorDraft: string | null;
  onSend: (payload: ComposerSendPayload) => void;
  onStop: () => void;
}) {
  const shouldReduceMotion = useReducedMotion();
  const threadsList = useThreadsList();
  const pinnedThreads = usePinnedThreads();
  // `useThreadsList` kini exclude thread yang disematkan → gabungkan pinned dulu (dedup by id)
  // supaya empty-state tetap menawarkan thread penting user.
  const recentThreads: RecentThread[] = [
    ...(pinnedThreads.data ?? []),
    ...(threadsList.data?.pages ?? []).flatMap((page) => page.items),
  ].reduce<RecentThread[]>((acc, t) => {
    if (!acc.some((r) => r.threadId === t.id)) {
      acc.push({ threadId: t.id, title: threadTitle(t), lastActivityAt: t.lastActivityAt });
    }
    return acc;
  }, []);

  return (
    <main className="flex min-h-0 min-w-0 flex-1 flex-col overflow-y-auto overflow-x-hidden bg-background">
      <div
        className={cn(
          "relative mx-auto flex w-full items-center justify-center",
          compact
            ? cn("flex-1 max-w-none", panelBodyPaddingClass)
            : "min-h-[calc(100%-5rem)] max-w-5xl px-4 py-10 sm:px-8",
        )}
      >
        <m.div
          className={cn("w-full", compact ? "max-w-none" : "max-w-2xl")}
          initial={
            shouldReduceMotion
              ? { opacity: 0 }
              : { opacity: 0, transform: "translateY(10px) scale(0.985)" }
          }
          animate={{ opacity: 1, transform: "translateY(0px) scale(1)" }}
          transition={{ duration: shouldReduceMotion ? 0.14 : 0.24, ease: HOME_EASE_OUT }}
        >
          <ComposerHeroState
            headerClassName="mb-5 gap-2"
            logoClassName={compact ? "size-12 sm:size-18" : "size-12 sm:size-22"}
            titleClassName={cn(
              "font-sans font-bold tracking-tight text-foreground leading-none",
              compact ? "text-xl" : "text-2xl sm:text-3xl",
            )}
          >
            <Composer
              showSuggestions={!compact}
              recentThreads={recentThreads}
              initialContent={initialContent}
              ambientContextRefs={ambientContextRefs}
              threadId={threadId}
              threadAgentKind={threadAgentKind}
              onSend={onSend}
              onStop={onStop}
              busy={busy}
              disabled={disabled}
              notice={notice}
              errorDraft={errorDraft}
            />
          </ComposerHeroState>
        </m.div>
        {compact ? null : <ExploreHandwrittenCue shouldReduceMotion={shouldReduceMotion ?? false} />}
      </div>
      {compact ? null : <HomeExploreBento />}
    </main>
  );
}

// apps/svelte/src/lib/features/thread-experience/components/MastraChatThreadSurface.svelte
<script lang="ts">
	import { untrack } from 'svelte';
	import { prefersReducedMotion } from 'svelte/motion';
	import { slide } from 'svelte/transition';
	import { replaceState } from '$app/navigation';
	import { page } from '$app/state';
	import { resolve } from '$app/paths';
	import { useQueryClient } from '@tanstack/svelte-query';
	import { toast } from 'svelte-sonner';
	import type { StatsGroup } from '@aqsha/chat-core/stats-viz';
	import {
		Icon,
		AlertCircleIcon,
		ClockIcon,
		NotebookIcon,
		RotateCcwIcon,
		WrenchIcon,
		XIcon
	} from '$lib/icons';
	import { Button } from '$lib/components/ui/button';
	import {
		Conversation,
		ConversationContent,
		ConversationScrollButton
	} from '$lib/components/ai-elements';
	import { cn } from '$lib/utils';
	import { queryKeys } from '$lib/query';
	import { threadTranscriptColumnClass } from '$lib/components/layout/panel-surface';
	import {
		usePinnedThreads,
		useSendStatus,
		useThreadArtifacts,
		useThreadSources,
		useThreadStatsBlocks,
		useThreadsList
	} from '$lib/features/threads/api';
	import {
		Composer,
		type ComposerNotice,
		type ComposerSendPayload,
		type RecentThread
	} from '$lib/features/threads/components/composer';
	import MessageList from '$lib/features/threads/components/MessageList.svelte';
	import QuestionsCard from '$lib/features/threads/components/QuestionsCard.svelte';
	import ToolCard, { toolCardShellClass } from '$lib/features/threads/components/ToolCard.svelte';
	import { bucketMessageAttachments } from '$lib/features/threads/lib/attachment-buckets';
	import { buildThreadPanelLookups } from '$lib/features/threads/lib/thread-panel-data';
	import { wfStepLabel } from '$lib/features/threads/lib/mastra-timeline';
	import { setMessageInteractions } from '$lib/features/threads/components/message-interactions';
	import type { ThreadAgent } from '$lib/features/threads/state/thread-agent.svelte';
	import type { ResearchSource } from '$lib/features/threads/types';
	import { threadTitle } from '$lib/features/threads/types';
	import { getThreadPanel } from './thread-panel-context.svelte';
	import { LIVE_PLAN_KEY } from '../utils/thread-panel-model';
	import { blockedNotice, deepBlockedMessage } from '../utils/send-status';
	import ComposerHeroState from './ComposerHeroState.svelte';
	import HomeBannerCarousel from '$lib/components/HomeBannerCarousel.svelte';
	import HomeExploreBento from '$lib/features/discovery/components/HomeExploreBento.svelte';
	import ExploreHandwrittenCue from '$lib/features/discovery/components/ExploreHandwrittenCue.svelte';

	/**
	 * Mastra chat runtime surface — the V1 composition (rich composer + landing hero) over `ThreadAgent`.
	 * Mastra Memory (server) = message SoT; the thread id is client-chosen so the URL is bumped on first
	 * send without waiting for a server round-trip.
	 */
	let {
		agent,
		threadId,
		threadAgentKind = 'lite',
		compact = false,
		initialContent,
		bindUrlOnSend = true
	}: {
		agent: ThreadAgent;
		threadId: string;
		threadAgentKind?: 'lite' | 'pro';
		compact?: boolean;
		initialContent?: string;
		/**
		 * Whether the first send of a NEW thread soft-bumps the URL to /app/threads/<id> (default). The
		 * Explore/reader chat panel passes `false`: it owns the thread lifecycle inside the panel and must
		 * NOT overwrite the page URL (which carries the Explore `?q=&topic=` state).
		 */
		bindUrlOnSend?: boolean;
	} = $props();

	const qc = useQueryClient();
	const panel = getThreadPanel();

	// Bridge the panel controller's openers to in-message cards (MessageInteractions).
	setMessageInteractions(
		panel
			? {
					openArtifact: (id) => panel.openArtifactPanel(id),
					openSources: (id) => panel.openSourcesPanel(id),
					openSearch: (turnId, idx) => panel.openSearchPanel(turnId, idx),
					openStep: (id) => panel.openStepPanel(id),
					openPlan: (turnId) => panel.openPlanPanel(turnId),
					openStats: (runKey) => panel.openStatsPanel(runKey)
				}
			: {}
	);

	const hasMessages = () => agent.messages.length > 0;
	const sendStatus = useSendStatus('normal_chat');
	// FE-11: `/deep` pre-check (non-consuming) — checked on submit so cap-exhaustion surfaces before the run.
	const deepSendStatus = useSendStatus('deep_research');

	const busy = $derived(agent.status !== 'ready');
	const reduce = $derived(prefersReducedMotion.current);
	const notice = $derived<ComposerNotice | null>(blockedNotice(sendStatus.data));
	const blocked = $derived(notice !== null);
	const isEmpty = $derived(agent.messages.length === 0 && !busy);

	// Research sources → grouped per turn (runId). Fetch once the thread has messages.
	const sources = useThreadSources(() => threadId, hasMessages);
	const sourcesByTurn = $derived.by(() => {
		// eslint-disable-next-line svelte/prefer-svelte-reactivity -- derived lookup map, not reactive state
		const map = new Map<string, ResearchSource[]>();
		for (const s of sources.data ?? []) {
			if (s.citationNumber == null) continue;
			const list = map.get(s.turnId);
			if (list) list.push(s);
			else map.set(s.turnId, [s]);
		}
		return map;
	});

	const statsBlocks = useThreadStatsBlocks(() => threadId, hasMessages);
	const statsGroupsByToolCallId = $derived.by(() => {
		// eslint-disable-next-line svelte/prefer-svelte-reactivity -- derived lookup map, not reactive state
		const map = new Map<string, StatsGroup>();
		for (const g of statsBlocks.data ?? []) map.set(g.toolCallId, g.group);
		return map;
	});

	const threadArtifacts = useThreadArtifacts(() => (hasMessages() ? threadId : null), {
		pollWhilePending: true
	});
	const attachmentsByMessage = $derived(
		bucketMessageAttachments(agent.messages, threadArtifacts.data)
	);

	// Id-keyed detail lookups for the side panels — built here + published to the controller. While a
	// plan/ask gate is live, inject its Setujui/Tolak / resolve-skip so the panel matches the gate card.
	$effect(() => {
		if (!panel) return;
		const lookups = buildThreadPanelLookups(
			agent.messages,
			sources.data,
			agent.planGate,
			agent.askGate,
			statsBlocks.data
		);
		const livePlan = agent.planGate ? lookups.plans.get(LIVE_PLAN_KEY) : undefined;
		if (livePlan) {
			lookups.plans.set(LIVE_PLAN_KEY, {
				...livePlan,
				resolve: (approve: boolean) => void agent.resolvePlan(approve)
			});
		}
		if (lookups.ask) {
			lookups.ask = {
				...lookups.ask,
				resolve: (resume) => void agent.resolveAsk(resume),
				skip: () => void agent.resolveAsk({ action: 'skipped' })
			};
		}
		panel.register(lookups);
	});

	// First send of a NEW thread → bump the URL to /app/threads/<id> (shallow, no navigation) so a
	// refresh resumes the thread. A new-thread landing has no `?panel=` yet (panels need messages), so a
	// bare resolve() path is sufficient — no query to preserve on the very first send.
	let bound = untrack(() => page.url.pathname.includes('/threads/'));
	function bumpUrl(): void {
		if (!bindUrlOnSend || bound) return;
		bound = true;
		replaceState(resolve('/app/(product)/threads/[threadId]', { threadId }), page.state);
	}

	function onComposerSend(payload: ComposerSendPayload): void {
		if (payload.command === 'deep') {
			const st = deepSendStatus.data;
			if (st && !st.canSend) {
				toast.error(deepBlockedMessage(st));
				return;
			}
		}
		bumpUrl();
		const opts = {
			clientContext: payload.clientContext,
			richText: payload.richText,
			attachmentIds: payload.attachmentIds,
			agentKind: payload.agentKind
		};
		const run =
			payload.command === 'deep'
				? agent.sendDeep(payload.text, opts)
				: agent.send(payload.text, opts);
		void run.then(() => {
			void qc.invalidateQueries({ queryKey: queryKeys.threads.sendStatus('normal_chat') });
			void qc.invalidateQueries({ queryKey: queryKeys.threads.sendStatus('deep_research') });
		});
	}

	// Landing recent threads (pinned first, dedup by id).
	const threadsList = useThreadsList(() => isEmpty && !compact);
	const pinnedThreads = usePinnedThreads(() => isEmpty && !compact);
	const recentThreads = $derived.by<RecentThread[]>(() => {
		const merged = [
			...(pinnedThreads.data ?? []),
			...(threadsList.data?.pages ?? []).flatMap((p) => p.items)
		];
		const out: RecentThread[] = [];
		for (const t of merged) {
			if (!out.some((r) => r.threadId === t.id)) {
				out.push({ threadId: t.id, title: threadTitle(t), lastActivityAt: t.lastActivityAt });
			}
		}
		return out;
	});

	const errorDraft = $derived(agent.error ? lastUserText() : null);
	function lastUserText(): string | null {
		const msgs = agent.messages;
		for (let i = msgs.length - 1; i >= 0; i--) {
			const msg = msgs[i];
			if (msg?.role !== 'user') continue;
			const t = msg.parts
				.filter((p) => p.kind === 'text')
				.map((p) => (p.kind === 'text' ? p.text : ''))
				.join('\n')
				.trim();
			return t || null;
		}
		return null;
	}
</script>

{#snippet deepNoticeCard(
	body: string,
	detail: string | null | undefined,
	primary: { label: string; onClick: () => void; disabled?: boolean; stop?: boolean },
	secondary?: { label: string; onClick: () => void }
)}
	<div
		class={threadTranscriptColumnClass}
		transition:slide={reduce ? { duration: 0 } : { duration: 180 }}
	>
		<div class={toolCardShellClass}>
			<div class="flex gap-2">
				<Icon icon={AlertCircleIcon} class="mt-0.5 size-4 shrink-0 text-muted-foreground" />
				<div class="min-w-0 flex-1">
					<p class="text-sm text-foreground">{body}</p>
					{#if detail}<p class="mt-1 text-xs text-muted-foreground">{detail}</p>{/if}
				</div>
			</div>
			<div class="mt-3 flex gap-2 pl-6">
				<Button size="sm" onclick={primary.onClick} disabled={primary.disabled}>
					{#if !primary.stop}<Icon icon={RotateCcwIcon} class="size-3.5" />{/if}
					{primary.label}
				</Button>
				{#if secondary}
					<Button size="sm" variant="ghost" onclick={secondary.onClick}>{secondary.label}</Button>
				{/if}
			</div>
		</div>
	</div>
{/snippet}

{#snippet composerDock(showSuggestions: boolean)}
	<Composer
		onSend={onComposerSend}
		onStop={() => agent.stop()}
		{busy}
		disabled={blocked}
		{notice}
		{threadId}
		{threadAgentKind}
		{errorDraft}
		{showSuggestions}
		recentThreads={showSuggestions ? recentThreads : []}
		initialContent={showSuggestions ? initialContent : undefined}
	/>
{/snippet}

{#if isEmpty}
	<main
		class="flex min-h-0 min-w-0 flex-1 flex-col overflow-x-hidden overflow-y-auto bg-background"
	>
		<div
			class={cn(
				'relative mx-auto flex w-full flex-col',
				compact
					? 'max-w-none flex-1 px-5 pt-3 pb-8 @2xl:px-6'
					: 'min-h-full max-w-5xl shrink-0 px-4 pt-10 pb-5 @2xl:px-8'
			)}
		>
			<div class="flex w-full flex-1 items-center justify-center">
				<div class={cn('w-full', compact ? 'max-w-none' : 'max-w-2xl')}>
					<ComposerHeroState
						headerClass="mb-5 gap-2"
						logoClass={compact ? 'size-12 @2xl:size-18' : 'size-12 @2xl:size-22'}
						titleClass={cn(
							'font-sans leading-none font-bold tracking-tight text-foreground',
							compact ? 'text-xl' : 'text-2xl @2xl:text-3xl'
						)}
					>
						{@render composerDock(!compact)}
					</ComposerHeroState>
				</div>
			</div>
			{#if !compact}
				<div class="mx-auto w-full max-w-2xl">
					<HomeBannerCarousel />
				</div>
				<!-- Cue positioned absolute vs the landing column — top-right, diagonal between the open-panel
				     action and the hero title. -->
				<ExploreHandwrittenCue />
			{/if}
		</div>
		{#if !compact}
			<HomeExploreBento />
		{/if}
	</main>
{:else}
	<div class="flex h-full min-h-0 w-full flex-col">
		<Conversation class="flex-1">
			<ConversationContent class="max-w-none p-0">
				<div class={cn(threadTranscriptColumnClass, 'flex flex-col gap-4 pt-3 pb-8')}>
					<MessageList
						messages={agent.messages}
						pending={agent.status === 'submitted'}
						{busy}
						{sourcesByTurn}
						{statsGroupsByToolCallId}
						{attachmentsByMessage}
						onRegenerate={() => void agent.regenerate()}
					/>
					{#if agent.error}
						<p class="text-sm text-red-500">{agent.error}</p>
					{/if}
				</div>
			</ConversationContent>
			{#snippet overlay()}
				<ConversationScrollButton />
			{/snippet}
		</Conversation>
		<div class={cn(threadTranscriptColumnClass, 'flex flex-col gap-2.5 pt-2.5 pb-4')}>
			{#if agent.deepStalled}
				{@render deepNoticeCard(
					agent.deepStalled,
					null,
					{ label: 'Mulai ulang', onClick: () => void agent.restartDeep() },
					{ label: 'Hentikan', onClick: () => agent.stop() }
				)}
			{/if}
			{#if agent.deepFailed}
				{@render deepNoticeCard(
					`Riset mendalam gagal${agent.deepFailed.stepId ? ` pada langkah "${wfStepLabel(agent.deepFailed.stepId).toLowerCase()}"` : ''}. Coba lagi akan melanjutkan dari langkah itu tanpa memotong kredit baru.`,
					agent.deepFailed.message,
					{ label: 'Coba lagi', onClick: () => void agent.retryDeep(), disabled: busy },
					{ label: 'Buang', onClick: () => agent.dismissDeepFailure() }
				)}
			{/if}
			{#if agent.deepNotice && !agent.messages.some((m) => m.id === `deep-bail:${agent.deepNotice!.runId}`)}
				{@render deepNoticeCard(`Riset mendalam dihentikan: ${agent.deepNotice.reason}`, null, {
					label: 'Tutup',
					onClick: () => agent.dismissDeepNotice(),
					stop: true
				})}
			{/if}
			{#if agent.askGate}
				<div
					class={threadTranscriptColumnClass}
					transition:slide={reduce ? { duration: 0 } : { duration: 180 }}
				>
					<QuestionsCard
						questions={agent.askGate.questions}
						findings={agent.askGate.findings}
						onSubmit={(resume) => void agent.resolveAsk(resume)}
						onSkip={() => void agent.resolveAsk({ action: 'skipped' })}
						onOpenPanel={panel ? () => panel.openQuestionsPanel() : undefined}
					/>
				</div>
			{/if}
			{#if agent.planGate}
				<div
					class={threadTranscriptColumnClass}
					transition:slide={reduce ? { duration: 0 } : { duration: 180 }}
				>
					<ToolCard
						icon={NotebookIcon}
						title="Rencana riset"
						meta={`${agent.planGate.subQuestions.length} sub-pertanyaan`}
						onOpenPanel={panel ? () => panel.openPlanPanel(LIVE_PLAN_KEY) : undefined}
					>
						<div class="flex gap-2">
							<Button size="sm" onclick={() => void agent.resolvePlan(true)}>Setujui</Button>
							<Button size="sm" variant="ghost" onclick={() => void agent.resolvePlan(false)}>
								Tolak
							</Button>
						</div>
					</ToolCard>
				</div>
			{/if}
			{#if agent.approvals.length > 0}
				<div
					class={cn(threadTranscriptColumnClass, 'flex flex-col gap-2.5')}
					transition:slide={reduce ? { duration: 0 } : { duration: 180 }}
				>
					{#each agent.approvals as a (a.toolCallId)}
						<ToolCard
							icon={WrenchIcon}
							title={a.title}
							meta={typeof a.args.artifactId === 'string' ? a.args.artifactId : undefined}
						>
							<div class="flex gap-2">
								<Button size="sm" onclick={() => void agent.approve(a.toolCallId)}>Setujui</Button>
								<Button size="sm" variant="ghost" onclick={() => void agent.decline(a.toolCallId)}>
									Tolak
								</Button>
							</div>
						</ToolCard>
					{/each}
				</div>
			{/if}
			{#if agent.queued.length > 0}
				<div
					class={cn(threadTranscriptColumnClass, 'flex flex-col gap-1.5')}
					transition:slide={reduce ? { duration: 0 } : { duration: 180 }}
				>
					{#each agent.queued as q (q.id)}
						<div
							class="flex items-center gap-2 rounded-lg border border-border bg-muted/30 px-3 py-2 text-[13px]"
						>
							<Icon icon={ClockIcon} class="size-3.5 shrink-0 text-muted-foreground/70" />
							<span class="min-w-0 flex-1 truncate text-foreground/80">{q.text}</span>
							<span class="shrink-0 text-[11px] text-muted-foreground">
								{q.mode === 'deep' ? 'Antre · /deep' : q.serverRunId ? 'Antre di server' : 'Antre'}
							</span>
							{#if q.serverRunId === undefined}
								<button
									type="button"
									onclick={() => agent.cancelQueued(q.id)}
									aria-label="Batalkan antrean"
									class="shrink-0 rounded p-0.5 text-muted-foreground/60 transition-colors hover:text-foreground"
								>
									<Icon icon={XIcon} class="size-3.5" />
								</button>
							{/if}
						</div>
					{/each}
				</div>
			{/if}
			{@render composerDock(false)}
		</div>
	</div>
{/if}
