// apps/app/features/thread-experience/components/thread-header.tsx
"use client";

import { LayersIcon, PanelLeftIcon } from "lucide-react";
import { PanelTitleLabel } from "@/components/panel-title-dropdown-trigger";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { panelHeaderPaddingClass } from "@/lib/panel-surface";
import type { ThreadSummary } from "./component-types";
import { ThreadDeleteActions } from "./thread-actions-menu";
import { ThreadRecentSwitcher } from "./thread-recent-switcher";

export function ThreadHeader({
  title,
  threads,
  onSelectThread,
  onCreateThread,
  showLeftTrigger,
  onToggleLeftSidebar,
  showContextToggle,
  contextPanelOpen,
  onToggleContextPanel,
  threadId,
  onDeleteThread,
}: {
  title: string;
  threads?: ThreadSummary[];
  onSelectThread?: (threadId: string) => void;
  onCreateThread?: () => void;
  showLeftTrigger: boolean;
  onToggleLeftSidebar: () => void;
  showContextToggle: boolean;
  contextPanelOpen: boolean;
  onToggleContextPanel: () => void;
  threadId?: string;
  onDeleteThread?: () => Promise<void>;
}) {
  const showThreadSwitcher = Boolean(threadId && onSelectThread && onCreateThread && threads);

  return (
    <div
      className={cn(
        "flex shrink-0 items-center justify-between gap-3 border-border bg-background",
        panelHeaderPaddingClass,
      )}
    >
      <div className="flex min-w-0 items-center gap-1.5">
        {showLeftTrigger ? (
          <Button
            type="button"
            variant="ghost"
            className="size-7 shrink-0 rounded-full text-muted-foreground hover:bg-muted hover:text-foreground"
            onClick={onToggleLeftSidebar}
            aria-label="Buka sidebar kiri"
          >
            <PanelLeftIcon className="size-3.5" />
          </Button>
        ) : null}
        {showThreadSwitcher ? (
          <ThreadRecentSwitcher
            title={title}
            threads={threads ?? []}
            onSelectThread={onSelectThread!}
            onNewThread={onCreateThread!}
            newLabel="Thread baru"
            emptyLabel="Belum ada thread"
          />
        ) : (
          <PanelTitleLabel>{title}</PanelTitleLabel>
        )}
      </div>
      <div className="flex shrink-0 items-center gap-1">
        {threadId && onDeleteThread ? (
          <ThreadDeleteActions
            description="Thread dan pesannya akan dihapus permanen."
            onDelete={onDeleteThread}
          />
        ) : null}
        {showContextToggle ? (
          <button
            type="button"
            onClick={onToggleContextPanel}
            className={cn(
              "flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[12px] font-semibold transition-colors",
              contextPanelOpen
                ? "bg-primary/15 text-primary"
                : "text-muted-foreground hover:bg-muted hover:text-foreground",
            )}
          >
            <LayersIcon className="size-3.5" />
            Konteks
          </button>
        ) : null}
      </div>
    </div>
  );
}

// apps/svelte/src/lib/features/thread-experience/components/ThreadHeader.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { Button } from '@aqsha/ui-svelte/components/button';
	import { Icon, LayersIcon, PanelLeftIcon } from '$lib/icons';
	import PanelOpenButton from '$lib/components/layout/PanelOpenButton.svelte';
	import PanelTitleLabel from '$lib/components/layout/PanelTitleLabel.svelte';
	import { panelHeaderBarClass } from '$lib/components/layout/panel-surface';
	import ThreadRecentSwitcher from '$lib/features/explore/components/ThreadRecentSwitcher.svelte';
	import { useDeleteThread } from '$lib/features/threads/api';
	import type { RecentThreadSummary } from '$lib/features/threads/types';
	import ThreadActionsMenu from './ThreadActionsMenu.svelte';

	/**
	 * Thread surface header chrome — title, recent switcher, delete, and context panel trigger.
	 * Data fetching stays in the parent shell so `useThread` runs once per tree.
	 */
	let {
		threadId,
		title,
		isExisting = Boolean(threadId),
		recentThreads = [],
		showLeftTrigger,
		onToggleLeftSidebar,
		contextPanelOpen,
		onOpenContextPanel
	}: {
		threadId?: string;
		title: string;
		isExisting?: boolean;
		recentThreads?: RecentThreadSummary[];
		showLeftTrigger: boolean;
		onToggleLeftSidebar: () => void;
		contextPanelOpen: boolean;
		onOpenContextPanel: () => void;
	} = $props();

	const deleteThread = useDeleteThread();

	async function handleDeleteThread(): Promise<void> {
		if (!threadId) return;
		await deleteThread.mutateAsync({ id: threadId });
		await goto(resolve('/app'), { replaceState: true });
	}

	function selectThread(id: string): void {
		void goto(resolve('/app/(product)/threads/[threadId]', { threadId: id }));
	}

	function createThread(): void {
		void goto(resolve('/app'));
	}
</script>

<header class={panelHeaderBarClass}>
	<div class="flex min-w-0 items-center gap-1.5">
		{#if showLeftTrigger}
			<Button
				type="button"
				variant="ghost"
				class="size-7 shrink-0 rounded-full text-muted-foreground hover:bg-muted hover:text-foreground"
				onclick={onToggleLeftSidebar}
				aria-label="Buka sidebar kiri"
			>
				<Icon icon={PanelLeftIcon} class="size-3.5" />
			</Button>
		{/if}
		{#if isExisting}
			<ThreadRecentSwitcher
				{title}
				threads={recentThreads}
				onSelectThread={selectThread}
				onNewThread={createThread}
				newLabel="Thread baru"
				emptyLabel="Belum ada thread"
			/>
		{:else}
			<PanelTitleLabel>{title}</PanelTitleLabel>
		{/if}
	</div>
	<div class="flex shrink-0 items-center gap-1">
		{#if threadId}
			<ThreadActionsMenu
				description="Thread dan pesannya akan dihapus permanen."
				onDelete={handleDeleteThread}
			/>
		{/if}
		<PanelOpenButton
			open={contextPanelOpen}
			onOpen={onOpenContextPanel}
			label="Panel"
			ariaLabel="Buka panel samping"
		>
			{#snippet icon()}
				<Icon icon={LayersIcon} class="size-3.5" />
			{/snippet}
		</PanelOpenButton>
	</div>
</header>
