// apps/web/components/ui/announcement.tsx
"use client";

import { type HTMLAttributes, createContext, useContext } from "react";

import { Badge, type BadgeProps } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

type BadgeContextType = {
  themed: boolean;
};

const BadgeContext = createContext<BadgeContextType | undefined>(undefined);

const useBadgeContext = () => {
  const context = useContext(BadgeContext);

  if (!context) {
    throw new Error("useBadgeContext must be used within a Badge");
  }

  return context;
};

export type AnnouncementProps = BadgeProps & {
  themed?: boolean;
};

export const Announcement = ({
  variant = "outline",
  themed = false,
  className,
  ...props
}: AnnouncementProps) => (
  <BadgeContext.Provider value={{ themed }}>
    <Badge
      variant={variant}
      className={cn(
        // `h-auto` melepas tinggi tetap Badge lokal (h-5) supaya padding internal
        // tag/title tak terpotong oleh `overflow-hidden`.
        "h-auto max-w-full gap-2 rounded-full bg-background px-3 py-0.5 font-medium shadow-sm transition-all",
        "hover:shadow-md",
        themed && "border-foreground/5",
        className,
      )}
      {...props}
    />
  </BadgeContext.Provider>
);

export type AnnouncementTagProps = HTMLAttributes<HTMLDivElement>;

export const AnnouncementTag = ({
  className,
  ...props
}: AnnouncementTagProps) => {
  const { themed } = useBadgeContext();

  return (
    <div
      className={cn(
        "-ml-2.5 shrink-0 truncate rounded-full bg-foreground/5 px-2.5 py-1 text-xs",
        themed && "bg-background/60",
        className,
      )}
      {...props}
    />
  );
};

export type AnnouncementTitleProps = HTMLAttributes<HTMLDivElement>;

export const AnnouncementTitle = ({
  className,
  ...props
}: AnnouncementTitleProps) => (
  <div
    className={cn("flex items-center gap-1 truncate py-1", className)}
    {...props}
  />
);

// apps/svelte/src/lib/components/ui/announcement/announcement.svelte
<script lang="ts" module>
	import { createContext } from '$lib/context';

	type AnnouncementContextValue = { readonly themed: boolean };
	/** Shared `themed` flag between Announcement and its Tag. */
	export const announcementContext = createContext<AnnouncementContextValue>('announcement');
</script>

<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HTMLAnchorAttributes } from 'svelte/elements';
	import { Badge, type BadgeVariant } from '$lib/components/ui/badge/index.js';
	import { cn } from '$lib/utils';

	/**
	 * Announcement pill. A rounded Badge with a `themed` context read by `AnnouncementTag`. `h-auto`
	 * Badge with a `themed` context read by `AnnouncementTag`. `h-auto` releases Badge's fixed
	 * height so the tag/title padding is not clipped by `overflow-hidden`.
	 */
	let {
		variant = 'outline',
		themed = false,
		class: className,
		children,
		...restProps
	}: HTMLAnchorAttributes & {
		variant?: BadgeVariant;
		themed?: boolean;
		children?: Snippet;
	} = $props();

	announcementContext.set({
		get themed() {
			return themed;
		}
	});
</script>

<Badge
	{variant}
	class={cn(
		'h-auto max-w-full gap-2 rounded-full bg-background px-3 py-0.5 font-medium shadow-sm transition-all',
		'hover:shadow-md',
		themed && 'border-foreground/5',
		className
	)}
	{...restProps}
>
	{@render children?.()}
</Badge>
