// apps/svelte/src/lib/features/marketing/components/FeatureFrame.svelte
<script lang="ts">
	import { mapRange, motionContext, scrollProgress } from '$lib/motion';
	import { cn } from '$lib/utils';
	import FrameChrome from './FrameChrome.svelte';

	// FeatureFrame — frame gambar editorial besar di bawah copy tiap fitur. Signature: "foto diluruskan
	// di meja" — masuk sedikit miring lalu scroll-linked lurus (rotate→0, y 32→0) + parallax internal +
	// hover zoom. Port `feature-frame.tsx` (`useScroll`/`useTransform` → scrollProgress + mapRange).
	let {
		image,
		alt,
		aspectClassName,
		sizes,
		initialRotate = 0,
		priority = false,
		class: className
	}: {
		image: string;
		alt: string;
		/** Utility aspect, mis. "aspect-[16/10]". */
		aspectClassName: string;
		/** `sizes` per placement. */
		sizes: string;
		/** Tilt awal (derajat); frame lurus ke 0 saat scroll masuk. */
		initialRotate?: number;
		priority?: boolean;
		class?: string;
	} = $props();

	const motion = motionContext.get();
	const reduce = $derived(motion.reducedMotion);

	// Lurus + naik saat frame bergerak dari bawah viewport ke 40%.
	let settle = $state(0);
	// Parallax internal lambat sepanjang perjalanan frame.
	let journey = $state(0);

	const settleAttach = scrollProgress(['start end', 'start 0.4'], (p) => (settle = p));
	const journeyAttach = scrollProgress(['start end', 'end start'], (p) => (journey = p));

	const rotate = $derived(mapRange(settle, [0, 1], [initialRotate, 0]));
	const y = $derived(mapRange(settle, [0, 1], [32, 0]));
	const parallax = $derived(mapRange(journey, [0, 1], [-6, 6]));
</script>

<div
	class={cn(
		'group relative w-full overflow-hidden rounded-2xl border border-border',
		aspectClassName,
		className
	)}
	style:transform={reduce ? undefined : `translateY(${y}px) rotate(${rotate}deg)`}
	{@attach settleAttach}
	{@attach journeyAttach}
>
	<div
		class="absolute inset-[-8%]"
		style:transform={reduce ? undefined : `translateY(${parallax}%)`}
	>
		<img
			src={image}
			{alt}
			{sizes}
			loading={priority ? 'eager' : 'lazy'}
			class="absolute inset-0 h-full w-full object-cover transition-transform duration-700 ease-out group-hover:scale-[1.03]"
		/>
	</div>
	<FrameChrome />
</div>

// apps/www/src/components/marketing/feature-frame.tsx
"use client";

import { m, useReducedMotion, useScroll, useTransform } from "motion/react";
import { useRef } from "react";

import { cn } from "@/lib/utils";

/**
 * FrameChrome — shared editorial dressing for large image frames: paper-grain
 * turbulence overlay + four corner crosshair marks. Used by the hero frame and
 * every FeatureFrame so the whole page speaks one visual language.
 */
export function FrameChrome() {
  return (
    <>
      <div className="paper-grain pointer-events-none absolute inset-0" />
      {(
        ["left-3 top-3", "right-3 top-3", "bottom-3 left-3", "bottom-3 right-3"] as const
      ).map((pos) => (
        <span
          key={pos}
          aria-hidden
          className={cn("pointer-events-none absolute size-[3px] bg-foreground/50", pos)}
        />
      ))}
    </>
  );
}

type FeatureFrameProps = {
  image: string;
  alt: string;
  /** Aspect utility, e.g. "aspect-[16/10]". Varies per feature block. */
  aspectClassName: string;
  /** Starting tilt in degrees; the frame straightens to 0 as it scrolls in. */
  initialRotate?: number;
  className?: string;
};

/**
 * FeatureFrame — big editorial image frame below each feature's copy.
 *
 * Signature micro-interaction: "foto diluruskan di meja" — the frame enters
 * slightly tilted and scroll-linked straightens (rotate → 0) while rising
 * (y 32 → 0), with a slow internal parallax and a gentle hover zoom. Thin 1px
 * border, no shadow. Image is a per-block prop so real screenshots can swap in
 * later without touching layout.
 */
export function FeatureFrame({
  image,
  alt,
  aspectClassName,
  initialRotate = 0,
  className,
}: FeatureFrameProps) {
  const reduce = useReducedMotion();
  const ref = useRef<HTMLDivElement>(null);

  // Straighten + rise while the frame travels from viewport bottom to 40%.
  const { scrollYProgress: settle } = useScroll({
    target: ref,
    offset: ["start end", "start 0.4"],
  });
  const rotate = useTransform(settle, [0, 1], [initialRotate, 0]);
  const y = useTransform(settle, [0, 1], [32, 0]);

  // Slow internal parallax across the frame's whole viewport journey.
  const { scrollYProgress: journey } = useScroll({
    target: ref,
    offset: ["start end", "end start"],
  });
  const parallaxY = useTransform(journey, [0, 1], ["-6%", "6%"]);

  return (
    <m.div
      ref={ref}
      className={cn(
        "group relative w-full overflow-hidden rounded-2xl border-2 border-border",
        aspectClassName,
        className,
      )}
      style={reduce ? undefined : { rotate, y }}
    >
      <m.div
        className="absolute inset-[-8%]"
        style={reduce ? undefined : { y: parallaxY }}
      >
        <img
          src={image}
          alt={alt}
          loading="lazy"
          decoding="async"
          className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 ease-out [@media(hover:hover)]:group-hover:scale-[1.03]"
        />
      </m.div>
      <FrameChrome />
    </m.div>
  );
}
