// packages/ui/src/selia/toggle.tsx
'use client';

import { Toggle as BaseToggle } from '@base-ui/react/toggle';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../lib/cn';

const toggleVariants = cva(
  [
    'inline-flex items-center justify-center gap-2.5 ring [&_svg:not([class*=size-])]:size-4.5 cursor-pointer',
    'focus:outline-0 focus-visible:outline-2 focus-visible:outline-offset-2 outline-primary',
    'transition-colors duration-100 [&_svg:not([class*=text-])]:text-foreground',
    'hover:not-[[data-disabled]]:not-[[data-pressed]]:bg-accent/50 data-disabled:cursor-not-allowed data-disabled:opacity-70',
  ],
  {
    variants: {
      variant: {
        default: 'ring-border shadow data-pressed:bg-accent',
        plain: 'ring-transparent data-pressed:bg-accent',
      },
      size: {
        sm: 'h-8.5 min-w-8.5 rounded px-3',
        'sm-icon': 'h-8.5 w-8.5 rounded',
        md: 'h-9.5 min-w-9.5 rounded px-4',
        'md-icon': 'h-9.5 w-9.5 rounded',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  },
);

export function Toggle({
  className,
  children,
  variant,
  size,
  ...props
}: React.ComponentProps<typeof BaseToggle> &
  VariantProps<typeof toggleVariants>) {
  return (
    <BaseToggle
      data-slot="toggle"
      data-size={size}
      className={cn(toggleVariants({ variant, size, className }))}
      {...props}
    >
      {children}
    </BaseToggle>
  );
}

// packages/ui-svelte/src/components/toggle/toggle.svelte
<script lang="ts" module>
	import { type VariantProps, tv } from 'tailwind-variants';

	export const toggleVariants = tv({
		base: "text-muted-foreground hover:text-foreground focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive data-[state=on]:bg-mint-strong data-[state=on]:text-white data-[state=on]:hover:bg-mint-strong gap-1 rounded-md text-[0.82rem] font-medium transition-all [&_svg:not([class*='size-'])]:size-4 group/toggle hover:bg-muted inline-flex items-center justify-center whitespace-nowrap outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
		variants: {
			variant: {
				default: 'bg-transparent',
				outline:
					'border-border hover:bg-muted border-2 bg-transparent data-[state=on]:border-mint-strong'
			},
			size: {
				default:
					'h-9 min-w-9 px-3.5 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2',
				sm: "h-8 min-w-8 rounded-sm px-3 text-[0.8rem] has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3.5",
				lg: 'h-10 min-w-10 px-4 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2'
			}
		},
		defaultVariants: {
			variant: 'default',
			size: 'default'
		}
	});

	export type ToggleVariant = VariantProps<typeof toggleVariants>['variant'];
	export type ToggleSize = VariantProps<typeof toggleVariants>['size'];
	export type ToggleVariants = VariantProps<typeof toggleVariants>;
</script>

<script lang="ts">
	import { Toggle as TogglePrimitive } from 'bits-ui';
	import { cn } from '../../utils.js';

	let {
		ref = $bindable(null),
		pressed = $bindable(false),
		class: className,
		size = 'default',
		variant = 'default',
		...restProps
	}: TogglePrimitive.RootProps & {
		variant?: ToggleVariant;
		size?: ToggleSize;
	} = $props();
</script>

<TogglePrimitive.Root
	bind:ref
	bind:pressed
	data-slot="toggle"
	class={cn(toggleVariants({ variant, size }), className)}
	{...restProps}
/>
