// apps/svelte/src/lib/features/workspaces/components/WorkspaceLibraryGrid.svelte
<script module lang="ts">
	export type FolderDropState = {
		/** True while ANY card is being dragged (so every folder hints it can receive it). */
		active: boolean;
		/** True for the folder the pointer is currently over (so it pops to confirm the drop). */
		isOver: boolean;
	};

	/** Container-relative marquee overlay rectangle (board-driven when `enableMarquee={false}`). */
	export type MarqueeOverlayRect = {
		left: number;
		top: number;
		width: number;
		height: number;
	};
</script>

<script lang="ts">
	import type { Attachment } from 'svelte/attachments';
	import { Icon, FolderIcon } from '$lib/icons';
	import * as ContextMenu from '@aqsha/ui-svelte/components/context-menu';
	import LibraryArtifactCard from '$lib/components/LibraryArtifactCard.svelte';
	import { libraryArtifactGridClass } from '../utils/library-grid';
	import { cn } from '@aqsha/ui-svelte/utils';
	import ArtifactContextMenuContent from './ArtifactContextMenuContent.svelte';
	import FolderContextMenuContent from './FolderContextMenuContent.svelte';
	import type { ArtifactSource } from '$lib/components/artifact-presentation';
	import type {
		FolderSummary,
		MoveTargetOption,
		WorkspaceArtifact,
		WorkspaceFolder
	} from '$lib/features/workspaces/utils/workspace-library-model';
	import {
		applyMarqueeSelection,
		intersectingTargetIds,
		normalizeMarqueeRect,
		type MarqueePoint,
		type MarqueeRect
	} from '$lib/features/workspaces/utils/workspace-marquee-selection';

	/**
	 * Presentational library grid (folders + artifact cards + marquee overlay). Drag/drop is wired
	 * through the `gridAttach` / `foldersAttach` attachment seams, the `getFolderDropState` highlight
	 * callback, `draggingArtifactIds` (card dimming), and the `data-artifact-tile-id` /
	 * `data-folder-tile-id` hooks. The marquee (pointer logic + hit-test + overlay) is self-contained
	 * here; set `enableMarquee={false}` to fully own selection from the board and drive the overlay via
	 * `marqueeRect`.
	 */
	const MIN_MARQUEE_SIZE = 6;
	const CLICK_DELAY_MS = 250;

	let {
		folders,
		artifacts,
		workspaceId,
		workspaces,
		moveTargets,
		draggingArtifactIds,
		getArtifactSelected,
		onToggleArtifactContext,
		onSetArtifactContextSelection,
		onOpenFolder,
		onOpenArtifact,
		onRenameFolder,
		onDeleteFolder,
		onMoveFolderToWorkspace,
		onRenameArtifact,
		onDeleteArtifact,
		onMoveArtifact,
		onMoveArtifactToWorkspace,
		onAddToCitations,
		// Board seam (native DnD + optional board-driven marquee).
		enableMarquee = true,
		gridAttach,
		foldersAttach,
		getFolderDropState,
		marqueeRect,
		// Native HTML5 DnD (card → folder), driven by the board.
		onArtifactDragStart,
		onArtifactDragEnd,
		onFolderDragEnter,
		onFolderDragLeave,
		onFolderDrop
	}: {
		folders: FolderSummary[];
		artifacts: WorkspaceArtifact[];
		workspaceId: string;
		workspaces: Array<{ _id: string; name: string }>;
		moveTargets: MoveTargetOption[];
		/** Ids of every card in the active drag (>1 when dragging a multi-selection). */
		draggingArtifactIds: string[];
		getArtifactSelected: (artifactId: string) => boolean;
		onToggleArtifactContext: (artifactId: string) => void;
		onSetArtifactContextSelection: (artifactIds: string[]) => void;
		onOpenFolder: (folderId: string) => void;
		onOpenArtifact: (artifactId: string) => void;
		onRenameFolder: (folder: WorkspaceFolder) => void;
		onDeleteFolder: (folder: WorkspaceFolder) => void;
		onMoveFolderToWorkspace: (folderId: string, targetWorkspaceId: string) => Promise<void>;
		onRenameArtifact: (artifact: WorkspaceArtifact) => void;
		onDeleteArtifact: (artifact: WorkspaceArtifact) => void;
		onMoveArtifact: (artifactId: string, target: string) => Promise<void>;
		onMoveArtifactToWorkspace: (artifactId: string, targetWorkspaceId: string) => Promise<void>;
		onAddToCitations?: (artifact: WorkspaceArtifact) => void;
		/** Set false to fully own selection/marquee from the board (still renders `marqueeRect`). */
		enableMarquee?: boolean;
		/** Board attachment on the artifact grid container (e.g. `svelte-dnd-action` dndzone). */
		gridAttach?: Attachment<HTMLDivElement>;
		/** Board attachment on the folders row (e.g. a drop-zone for card-onto-folder). */
		foldersAttach?: Attachment<HTMLElement>;
		/** Board-driven folder drop highlight — `{ active, isOver }` per folder id. */
		getFolderDropState?: (folderId: string) => FolderDropState;
		/** Board-driven marquee overlay rect (used when `enableMarquee={false}`). */
		marqueeRect?: MarqueeOverlayRect | null;
		/** Native drag lifecycle (board resolves the multi-selection drag set + clears it). */
		onArtifactDragStart?: (grabbedId: string) => void;
		onArtifactDragEnd?: () => void;
		/** Folder drop targets (board tracks the hovered folder + performs the move). */
		onFolderDragEnter?: (folderId: string) => void;
		onFolderDragLeave?: (folderId: string) => void;
		onFolderDrop?: (folderId: string) => void;
	} = $props();

	// Grid tunggal: folder + semua artifak folder-scoped (pustaka user maupun output agent). Kartu
	// agent dibedakan lewat badge/aksen di kartunya sendiri.
	const selectedIds = $derived(
		artifacts.flatMap((artifact) => (getArtifactSelected(artifact._id) ? [artifact._id] : []))
	);
	const visibleArtifactIds = $derived(artifacts.map((artifact) => artifact._id));

	// Stable attachment wrappers so the board's optional attach seams can be applied unconditionally.
	const gridContainerAttach: Attachment<HTMLDivElement> = (node) => gridAttach?.(node);
	const foldersContainerAttach: Attachment<HTMLElement> = (node) => foldersAttach?.(node);

	function folderDropState(folderId: string): FolderDropState {
		return getFolderDropState?.(folderId) ?? { active: false, isOver: false };
	}

	function isProcessing(artifact: WorkspaceArtifact): boolean {
		return artifact.indexingStatus === 'pending' || artifact.indexingStatus === 'failed';
	}

	// --- Single-vs-double click --------------------------------------------------------------
	// Per-card debounce timers; a plain registry (not reactive state).
	// eslint-disable-next-line svelte/prefer-svelte-reactivity -- transient timer registry, never rendered
	const clickTimers = new Map<string, ReturnType<typeof setTimeout>>();

	function clearClickTimer(id: string) {
		const timer = clickTimers.get(id);
		if (timer) {
			clearTimeout(timer);
			clickTimers.delete(id);
		}
	}

	function selectLibraryItem(id: string) {
		clearClickTimer(id);
		clickTimers.set(
			id,
			setTimeout(() => {
				onToggleArtifactContext(id);
				clickTimers.delete(id);
			}, CLICK_DELAY_MS)
		);
	}

	function openLibraryItem(id: string) {
		clearClickTimer(id);
		onOpenArtifact(id);
	}

	$effect(() => () => {
		for (const timer of clickTimers.values()) clearTimeout(timer);
		clickTimers.clear();
	});

	// --- Marquee (self-contained; toggleable via `enableMarquee`) ---------------------------------
	let gridEl = $state<HTMLDivElement | null>(null);
	let marquee = $state<{
		start: MarqueePoint;
		current: MarqueePoint;
		mode: 'add' | 'toggle';
	} | null>(null);
	let previewIds = $state<string[]>([]);
	let localSelectionRect = $state<MarqueeOverlayRect | null>(null);

	const overlayRect = $derived(enableMarquee ? localSelectionRect : (marqueeRect ?? null));

	function toLocalRect(rect: MarqueeRect, containerRect: DOMRect): MarqueeOverlayRect {
		return {
			left: rect.left - containerRect.left,
			top: rect.top - containerRect.top,
			width: rect.width,
			height: rect.height
		};
	}

	function collectTileTargets() {
		if (!gridEl) return [];
		return Array.from(gridEl.querySelectorAll<HTMLElement>('[data-artifact-tile-id]')).map(
			(element) => ({
				id: element.dataset.artifactTileId ?? '',
				rect: element.getBoundingClientRect()
			})
		);
	}

	function updatePreview(rect: MarqueeRect) {
		previewIds = intersectingTargetIds(rect, collectTileTargets());
	}

	function tileSelected(id: string): boolean {
		const selected = getArtifactSelected(id);
		if (!enableMarquee || !previewIds.includes(id)) return selected;
		return (marquee?.mode ?? 'add') === 'toggle' ? !selected : true;
	}

	function handleGridPointerDown(event: PointerEvent) {
		if (event.button !== 0 || event.target !== event.currentTarget) return;
		event.preventDefault();
		const container = event.currentTarget as HTMLElement;
		container.setPointerCapture(event.pointerId);
		const point = { x: event.clientX, y: event.clientY };
		marquee = {
			start: point,
			current: point,
			mode: event.metaKey || event.ctrlKey ? 'toggle' : 'add'
		};
		localSelectionRect = toLocalRect(
			normalizeMarqueeRect(point, point),
			container.getBoundingClientRect()
		);
		previewIds = [];
	}

	function handleGridPointerMove(event: PointerEvent) {
		if (!marquee) return;
		const current = { x: event.clientX, y: event.clientY };
		const rect = normalizeMarqueeRect(marquee.start, current);
		marquee = { ...marquee, current };
		localSelectionRect = toLocalRect(
			rect,
			(event.currentTarget as HTMLElement).getBoundingClientRect()
		);
		updatePreview(rect);
	}

	function endMarquee() {
		if (!marquee) return;
		const rect = normalizeMarqueeRect(marquee.start, marquee.current);
		const shouldCommit = rect.width >= MIN_MARQUEE_SIZE || rect.height >= MIN_MARQUEE_SIZE;

		if (shouldCommit && previewIds.length > 0) {
			onSetArtifactContextSelection(
				applyMarqueeSelection({
					currentIds: selectedIds,
					hitIds: previewIds,
					visibleIds: visibleArtifactIds,
					mode: marquee.mode
				})
			);
		}

		marquee = null;
		previewIds = [];
		localSelectionRect = null;
	}

	function artifactHref(artifactId: string) {
		return `/app/workspaces/${workspaceId}/artifacts/${artifactId}`;
	}
</script>

{#snippet folderTile(folder: FolderSummary)}
	{@const drop = folderDropState(folder._id)}
	<ContextMenu.Root>
		<ContextMenu.Trigger>
			{#snippet child({ props })}
				<div
					{...props}
					data-folder-tile-id={folder._id}
					role="group"
					ondragover={(event) => {
						if (!drop.active) return;
						event.preventDefault();
						if (event.dataTransfer) event.dataTransfer.dropEffect = 'move';
					}}
					ondragenter={(event) => {
						if (!drop.active) return;
						event.preventDefault();
						onFolderDragEnter?.(folder._id);
					}}
					ondragleave={(event) => {
						const currentTarget = event.currentTarget as Node | null;
						if (!currentTarget?.contains(event.relatedTarget as Node | null))
							onFolderDragLeave?.(folder._id);
					}}
					ondrop={(event) => {
						if (!drop.active) return;
						event.preventDefault();
						onFolderDrop?.(folder._id);
					}}
					class={cn(
						'group relative inline-flex max-w-full items-center rounded-lg hover:bg-muted/50',
						'motion-safe:transition-[transform,background-color,box-shadow] motion-safe:duration-150 motion-safe:ease-out',
						drop.active && 'ring-1 ring-primary/25',
						drop.isOver && '-translate-y-0.5 scale-[1.03] bg-primary/10 ring-2 ring-primary/60'
					)}
				>
					<button
						type="button"
						ondblclick={() => onOpenFolder(folder._id)}
						class="inline-flex min-w-0 items-center gap-2.5 py-2 pl-2.5 pr-1 text-left outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background"
						aria-label={`Folder ${folder.name}. Klik dua kali untuk membuka.`}
					>
						<Icon
							icon={FolderIcon}
							class={cn(
								'size-5 shrink-0 fill-lemon text-lemon motion-safe:transition-transform motion-safe:duration-150 motion-safe:ease-out',
								drop.isOver && 'scale-110'
							)}
							strokeWidth={1.25}
						/>
						<span class="truncate text-[13px] font-medium text-foreground">{folder.name}</span>
					</button>
				</div>
			{/snippet}
		</ContextMenu.Trigger>
		<FolderContextMenuContent
			{workspaces}
			onOpen={() => onOpenFolder(folder._id)}
			onRename={() => onRenameFolder(folder)}
			onDelete={() => onDeleteFolder(folder)}
			onMoveToWorkspace={(targetWorkspaceId) =>
				onMoveFolderToWorkspace(folder._id, targetWorkspaceId)}
		/>
	</ContextMenu.Root>
{/snippet}

{#snippet artifactTile(artifact: WorkspaceArtifact)}
	<ContextMenu.Root>
		<ContextMenu.Trigger>
			{#snippet child({ props })}
				<div
					{...props}
					data-artifact-tile-id={artifact._id}
					draggable={!isProcessing(artifact)}
					ondragstart={(event) => {
						if (isProcessing(artifact)) return;
						event.dataTransfer?.setData('text/plain', artifact._id);
						if (event.dataTransfer) event.dataTransfer.effectAllowed = 'move';
						onArtifactDragStart?.(artifact._id);
					}}
					ondragend={() => onArtifactDragEnd?.()}
					class={cn(
						'group relative motion-safe:transition-opacity motion-safe:duration-150',
						draggingArtifactIds.includes(artifact._id) && 'opacity-40'
					)}
				>
					<LibraryArtifactCard
						title={artifact.title}
						artifactType={artifact.artifactType}
						source={artifact.source as ArtifactSource | undefined}
						createdAt={artifact.createdAt}
						isSelected={tileSelected(artifact._id)}
						isProcessing={isProcessing(artifact)}
						processingFailed={artifact.indexingStatus === 'failed'}
						onClick={() => selectLibraryItem(artifact._id)}
						onDoubleClick={() => openLibraryItem(artifact._id)}
					/>
				</div>
			{/snippet}
		</ContextMenu.Trigger>
		<ArtifactContextMenuContent
			{moveTargets}
			{workspaces}
			artifactHref={artifactHref(artifact._id)}
			isSelected={tileSelected(artifact._id)}
			onSelect={() => onToggleArtifactContext(artifact._id)}
			onOpen={() => onOpenArtifact(artifact._id)}
			onRename={() => onRenameArtifact(artifact)}
			onDelete={() => onDeleteArtifact(artifact)}
			onMove={(target) => onMoveArtifact(artifact._id, target)}
			onMoveToWorkspace={(targetWorkspaceId) =>
				onMoveArtifactToWorkspace(artifact._id, targetWorkspaceId)}
			onAddToCitations={onAddToCitations && artifact.detectedDocumentKind === 'scholarly_paper'
				? () => onAddToCitations(artifact)
				: undefined}
		/>
	</ContextMenu.Root>
{/snippet}

<div class="flex flex-col gap-6">
	{#if folders.length > 0}
		<section class="flex flex-wrap gap-2" {@attach foldersContainerAttach}>
			{#each folders as folder (folder._id)}
				{@render folderTile(folder)}
			{/each}
		</section>
	{/if}

	{#if artifacts.length > 0}
		<section class="flex flex-col gap-5">
			<!-- marquee is a pointer-only enhancement; the interactive controls are the cards inside -->
			<!-- svelte-ignore a11y_no_static_element_interactions -->
			<div
				bind:this={gridEl}
				class={cn(libraryArtifactGridClass, 'relative')}
				{@attach gridContainerAttach}
				onpointerdown={enableMarquee ? handleGridPointerDown : undefined}
				onpointermove={enableMarquee ? handleGridPointerMove : undefined}
				onpointerup={enableMarquee ? endMarquee : undefined}
				onpointercancel={enableMarquee ? endMarquee : undefined}
			>
				{#each artifacts as artifact (artifact._id)}
					{@render artifactTile(artifact)}
				{/each}
				{#if overlayRect}
					<div
						class="pointer-events-none absolute z-20 rounded-md border border-primary/60 bg-primary/10"
						style="left: {overlayRect.left}px; top: {overlayRect.top}px; width: {overlayRect.width}px; height: {overlayRect.height}px;"
					></div>
				{/if}
			</div>
		</section>
	{/if}
</div>

// apps/web-v2/features/workspaces/components/workspace-library-grid.tsx
"use client";

import { useRef, useState, type ReactNode } from "react";
import { FileTextIcon, FolderIcon, NotebookIcon } from "@aqsha/ui/icons";
import { LibraryArtifactCard } from "@/components/library-artifact-card";
import { useLibraryItemClick } from "../hooks/use-library-item-click";
import { ContextMenu, ContextMenuTrigger } from "@/components/ui/context-menu";
import { libraryArtifactGridClass } from "@/lib/library-grid";
import { cn } from "@/lib/utils";
import {
  ArtifactContextMenuContent,
  FolderContextMenuContent,
} from "./workspace-library-context-menus";
import { WorkspaceLibraryEmpty } from "./workspace-library-empty";
import {
  partitionArtifactsByCategory,
  type FolderSummary,
  type MoveTargetOption,
  type WorkspaceArtifact,
  type WorkspaceFolder,
} from "../utils/workspace-library-model";
import {
  applyMarqueeSelection,
  intersectingTargetIds,
  normalizeMarqueeRect,
  type MarqueePoint,
  type MarqueeRect,
} from "../utils/workspace-marquee-selection";

const MIN_MARQUEE_SIZE = 6;

type ArtifactItemHandlers = {
  workspaceId: string;
  workspaces: Array<{ _id: string; name: string }>;
  moveTargets: MoveTargetOption[];
  dragArtifactId: string | null;
  getArtifactSelected: (artifactId: string) => boolean;
  onToggleArtifactContext: (artifactId: string) => void;
  onSetArtifactContextSelection: (artifactIds: string[]) => void;
  onOpenArtifact: (artifactId: string) => void;
  onRenameArtifact: (artifact: WorkspaceArtifact) => void;
  onDeleteArtifact: (artifact: WorkspaceArtifact) => void;
  onMoveArtifact: (artifactId: string, target: string) => Promise<void>;
  onMoveArtifactToWorkspace: (artifactId: string, targetWorkspaceId: string) => Promise<void>;
  onDragArtifactStart: (artifactId: string) => void;
  onDragArtifactEnd: () => void;
};

export function WorkspaceLibraryGrid({
  folders,
  artifacts,
  workspaceId,
  workspaces,
  moveTargets,
  dragArtifactId,
  getArtifactSelected,
  onToggleArtifactContext,
  onSetArtifactContextSelection,
  onOpenFolder,
  onOpenArtifact,
  onRenameFolder,
  onDeleteFolder,
  onMoveFolderToWorkspace,
  onRenameArtifact,
  onDeleteArtifact,
  onMoveArtifact,
  onMoveArtifactToWorkspace,
  onDragArtifactStart,
  onDragArtifactEnd,
  onDropArtifactOnFolder,
  controls,
}: {
  folders: FolderSummary[];
  artifacts: WorkspaceArtifact[];
  workspaceId: string;
  workspaces: Array<{ _id: string; name: string }>;
  moveTargets: MoveTargetOption[];
  dragArtifactId: string | null;
  getArtifactSelected: (artifactId: string) => boolean;
  onToggleArtifactContext: (artifactId: string) => void;
  onSetArtifactContextSelection: (artifactIds: string[]) => void;
  onOpenFolder: (folderId: string) => void;
  onOpenArtifact: (artifactId: string) => void;
  onRenameFolder: (folder: WorkspaceFolder) => void;
  onDeleteFolder: (folder: WorkspaceFolder) => void;
  onMoveFolderToWorkspace: (folderId: string, targetWorkspaceId: string) => Promise<void>;
  onRenameArtifact: (artifact: WorkspaceArtifact) => void;
  onDeleteArtifact: (artifact: WorkspaceArtifact) => void;
  onMoveArtifact: (artifactId: string, target: string) => Promise<void>;
  onMoveArtifactToWorkspace: (artifactId: string, targetWorkspaceId: string) => Promise<void>;
  onDragArtifactStart: (artifactId: string) => void;
  onDragArtifactEnd: () => void;
  onDropArtifactOnFolder: (folderId: string) => void;
  controls?: ReactNode;
}) {
  const { library, output } = partitionArtifactsByCategory(artifacts);
  // When there are no artifacts at all (folders-only view) we skip the two
  // section shells so the board doesn't show a double "empty" — the fully-empty
  // workspace case is handled upstream by WorkspaceLibraryEmpty.
  const hasAnyArtifacts = library.length > 0 || output.length > 0;
  // Full selection across both sections, used as marquee `currentIds` so a
  // marquee in one section never wipes the other section's selection.
  const selectedIds = artifacts.flatMap((artifact) =>
    getArtifactSelected(artifact._id) ? [artifact._id] : [],
  );

  const itemHandlers: ArtifactItemHandlers = {
    workspaceId,
    workspaces,
    moveTargets,
    dragArtifactId,
    getArtifactSelected,
    onToggleArtifactContext,
    onSetArtifactContextSelection,
    onOpenArtifact,
    onRenameArtifact,
    onDeleteArtifact,
    onMoveArtifact,
    onMoveArtifactToWorkspace,
    onDragArtifactStart,
    onDragArtifactEnd,
  };

  return (
    <div className="flex flex-col gap-9">
      {folders.length > 0 ? (
        <section className="flex flex-col gap-5">
          <LibrarySectionHeader title="Folders" />
          <div className="flex flex-wrap gap-2">
            {folders.map((folder) => (
              <FolderTile
                key={folder._id}
                folder={folder}
                isDropTarget={dragArtifactId !== null}
                onOpen={() => onOpenFolder(folder._id)}
                onRename={() => onRenameFolder(folder)}
                onDelete={() => onDeleteFolder(folder)}
                onMoveToWorkspace={(targetWorkspaceId) =>
                  onMoveFolderToWorkspace(folder._id, targetWorkspaceId)
                }
                onDrop={() => onDropArtifactOnFolder(folder._id)}
                workspaces={workspaces}
              />
            ))}
          </div>
        </section>
      ) : null}

      {hasAnyArtifacts ? (
        <>
          <ArtifactSection
            title={`Pustaka (${library.length})`}
            artifacts={library}
            selectedIds={selectedIds}
            controls={controls}
            emptyState={
              <WorkspaceLibraryEmpty
                variant="root"
                icon={FileTextIcon}
                title="Mulai bangun pustakamu"
                description="Tambahkan dokumen, file, atau URL untuk mulai mengumpulkan bahan risetmu."
                showActions={false}
                showSamples
              />
            }
            {...itemHandlers}
          />

          <ArtifactSection
            title={`Artifact (${output.length})`}
            artifacts={output}
            selectedIds={selectedIds}
            emptyState={
              <WorkspaceLibraryEmpty
                variant="root"
                icon={NotebookIcon}
                title="Hasil kerja agent muncul di sini"
                description="Minta agent membuat laporan, ringkasan, atau visualisasi lewat chat — semuanya tersimpan otomatis di sini."
                showActions={false}
                showSamples
              />
            }
            {...itemHandlers}
          />
        </>
      ) : null}
    </div>
  );
}

function ArtifactSection({
  title,
  artifacts,
  selectedIds,
  controls,
  emptyState,
  workspaceId,
  workspaces,
  moveTargets,
  dragArtifactId,
  getArtifactSelected,
  onToggleArtifactContext,
  onSetArtifactContextSelection,
  onOpenArtifact,
  onRenameArtifact,
  onDeleteArtifact,
  onMoveArtifact,
  onMoveArtifactToWorkspace,
  onDragArtifactStart,
  onDragArtifactEnd,
}: ArtifactItemHandlers & {
  title: string;
  artifacts: WorkspaceArtifact[];
  selectedIds: string[];
  controls?: ReactNode;
  emptyState: ReactNode;
}) {
  const gridRef = useRef<HTMLDivElement | null>(null);
  const tileRefs = useRef<Map<string, HTMLDivElement> | null>(null);
  if (tileRefs.current === null) {
    tileRefs.current = new Map();
  }
  const tileElementRefs = tileRefs.current;
  const [marquee, setMarquee] = useState<{
    start: MarqueePoint;
    current: MarqueePoint;
    mode: "add" | "toggle";
  } | null>(null);
  const [previewIds, setPreviewIds] = useState<string[]>([]);
  const [localSelectionRect, setLocalSelectionRect] = useState<{
    left: number;
    top: number;
    width: number;
    height: number;
  } | null>(null);

  const sectionSelectedCount = artifacts.reduce(
    (count, artifact) => (getArtifactSelected(artifact._id) ? count + 1 : count),
    0,
  );
  const visibleArtifactIds = artifacts.map((artifact) => artifact._id);
  const previewIdSet = new Set(previewIds);
  const updatePreview = (rect: MarqueeRect) => {
    const targets = artifacts.flatMap((artifact) => {
      const element = tileElementRefs.get(artifact._id);
      if (!element) return [];
      return [{ id: artifact._id, rect: element.getBoundingClientRect() }];
    });
    setPreviewIds(intersectingTargetIds(rect, targets));
  };

  const endMarquee = () => {
    if (!marquee) return;
    const rect = normalizeMarqueeRect(marquee.start, marquee.current);
    const shouldCommit =
      rect.width >= MIN_MARQUEE_SIZE || rect.height >= MIN_MARQUEE_SIZE;

    if (shouldCommit && previewIds.length > 0) {
      onSetArtifactContextSelection(
        applyMarqueeSelection({
          currentIds: selectedIds,
          hitIds: previewIds,
          visibleIds: visibleArtifactIds,
          mode: marquee.mode,
        }),
      );
    }

    setMarquee(null);
    setPreviewIds([]);
    setLocalSelectionRect(null);
  };

  return (
    <section className="flex flex-col gap-5">
      <LibrarySectionHeader title={title} controls={controls} />
      {artifacts.length > 0 ? (
        <div className="relative">
          {sectionSelectedCount > 0 || marquee ? (
            <div className="pointer-events-none absolute right-0 top-0 z-10 flex translate-y-[-calc(100%+0.5rem)] items-center gap-2 rounded-lg border border-border bg-card/95 px-2.5 py-1.5 text-[11px] font-medium text-muted-foreground shadow-sm">
              <span>
                {selectionCountLabel(marquee ? previewIds.length : sectionSelectedCount)}
              </span>
              {sectionSelectedCount > 0 ? (
                <button
                  type="button"
                  className="pointer-events-auto rounded-md px-1.5 py-0.5 text-foreground transition-colors hover:bg-muted"
                  onClick={() => onSetArtifactContextSelection([])}
                >
                  Bersihkan
                </button>
              ) : null}
            </div>
          ) : null}
          <div
            ref={gridRef}
            className={cn(libraryArtifactGridClass, "relative")}
            onPointerDown={(event) => {
              if (event.button !== 0 || event.target !== event.currentTarget) return;
              event.preventDefault();
              event.currentTarget.setPointerCapture(event.pointerId);
              const point = { x: event.clientX, y: event.clientY };
              setMarquee({
                start: point,
                current: point,
                mode: event.metaKey || event.ctrlKey ? "toggle" : "add",
              });
              setLocalSelectionRect(
                toLocalRect(
                  normalizeMarqueeRect(point, point),
                  event.currentTarget.getBoundingClientRect(),
                ),
              );
              setPreviewIds([]);
            }}
            onPointerMove={(event) => {
              if (!marquee) return;
              const current = { x: event.clientX, y: event.clientY };
              const rect = normalizeMarqueeRect(marquee.start, current);
              setMarquee((state) => (state ? { ...state, current } : state));
              setLocalSelectionRect(
                toLocalRect(rect, event.currentTarget.getBoundingClientRect()),
              );
              updatePreview(rect);
            }}
            onPointerUp={endMarquee}
            onPointerCancel={endMarquee}
          >
            {artifacts.map((artifact) => (
              <ArtifactTile
                key={artifact._id}
                refCallback={(element) => {
                  if (element) {
                    tileElementRefs.set(artifact._id, element);
                  } else {
                    tileElementRefs.delete(artifact._id);
                  }
                }}
                artifact={artifact}
                workspaceId={workspaceId}
                moveTargets={moveTargets}
                isDragging={dragArtifactId === artifact._id}
                isSelected={getPreviewSelectedState({
                  selected: getArtifactSelected(artifact._id),
                  previewed: previewIdSet.has(artifact._id),
                  mode: marquee?.mode ?? "add",
                })}
                onSelect={() => onToggleArtifactContext(artifact._id)}
                onOpen={() => onOpenArtifact(artifact._id)}
                onRename={() => onRenameArtifact(artifact)}
                onDelete={() => onDeleteArtifact(artifact)}
                onMove={(target) => onMoveArtifact(artifact._id, target)}
                onMoveToWorkspace={(targetWorkspaceId) =>
                  onMoveArtifactToWorkspace(artifact._id, targetWorkspaceId)
                }
                onDragStart={() => onDragArtifactStart(artifact._id)}
                onDragEnd={onDragArtifactEnd}
                workspaces={workspaces}
              />
            ))}
            {localSelectionRect ? (
              <div
                className="pointer-events-none absolute z-20 rounded-md border border-primary/60 bg-primary/10"
                style={{
                  left: localSelectionRect.left,
                  top: localSelectionRect.top,
                  width: localSelectionRect.width,
                  height: localSelectionRect.height,
                }}
              />
            ) : null}
          </div>
        </div>
      ) : (
        emptyState
      )}
    </section>
  );
}

function LibrarySectionHeader({
  title,
  controls,
}: {
  title: string;
  controls?: ReactNode;
}) {
  return (
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div className="flex min-w-0 flex-1 items-center gap-5">
        <h2 className="shrink-0 text-[15px] font-semibold leading-none text-foreground">
          {title}
        </h2>
        <div className="h-px min-w-0 flex-1 bg-border/70" />
      </div>
      {controls ? (
        <div className="flex shrink-0 justify-start sm:justify-end">
          {controls}
        </div>
      ) : null}
    </div>
  );
}

function toLocalRect(rect: MarqueeRect, containerRect: DOMRect) {
  return {
    left: rect.left - containerRect.left,
    top: rect.top - containerRect.top,
    width: rect.width,
    height: rect.height,
  };
}

function getPreviewSelectedState({
  selected,
  previewed,
  mode,
}: {
  selected: boolean;
  previewed: boolean;
  mode: "add" | "toggle";
}) {
  if (!previewed) return selected;
  return mode === "toggle" ? !selected : true;
}

function selectionCountLabel(count: number) {
  return `${count} dipilih untuk konteks`;
}

function FolderTile({
  folder,
  isDropTarget,
  onOpen,
  onRename,
  onDelete,
  onMoveToWorkspace,
  onDrop,
  workspaces,
}: {
  folder: FolderSummary;
  isDropTarget: boolean;
  onOpen: () => void;
  onRename: () => void;
  onDelete: () => void;
  onMoveToWorkspace: (targetWorkspaceId: string) => void;
  onDrop: () => void;
  workspaces: Array<{ _id: string; name: string }>;
}) {
  return (
    <ContextMenu>
      <ContextMenuTrigger asChild>
        <div
          className={cn(
            "group relative inline-flex max-w-full items-center rounded-lg transition-colors hover:bg-muted/50",
            isDropTarget && "ring-2 ring-primary/30",
          )}
          onDragOver={(event) => {
            if (!isDropTarget) return;
            event.preventDefault();
            event.dataTransfer.dropEffect = "move";
          }}
          onDrop={(event) => {
            event.preventDefault();
            onDrop();
          }}
        >
          <button
            type="button"
            onDoubleClick={onOpen}
            className="inline-flex min-w-0 items-center gap-2.5 py-2 pl-2.5 pr-1 text-left outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background"
            aria-label={`Folder ${folder.name}. Klik dua kali untuk membuka.`}
          >
            <FolderIcon
              className="size-5 shrink-0 fill-lemon text-lemon"
              strokeWidth={1.25}
            />
            <span className="truncate text-[13px] font-medium text-foreground">{folder.name}</span>
          </button>
        </div>
      </ContextMenuTrigger>
      <FolderContextMenuContent
        workspaces={workspaces}
        onOpen={onOpen}
        onRename={onRename}
        onDelete={onDelete}
        onMoveToWorkspace={onMoveToWorkspace}
      />
    </ContextMenu>
  );
}

function ArtifactTile({
  refCallback,
  artifact,
  workspaceId,
  moveTargets,
  isDragging,
  isSelected,
  onSelect,
  onOpen,
  onRename,
  onDelete,
  onMove,
  onMoveToWorkspace,
  onDragStart,
  onDragEnd,
  workspaces,
}: {
  refCallback: (element: HTMLDivElement | null) => void;
  artifact: WorkspaceArtifact;
  workspaceId: string;
  moveTargets: MoveTargetOption[];
  workspaces: Array<{ _id: string; name: string }>;
  isDragging: boolean;
  isSelected: boolean;
  onSelect: () => void;
  onOpen: () => void;
  onRename: () => void;
  onDelete: () => void;
  onMove: (target: string) => void;
  onMoveToWorkspace: (targetWorkspaceId: string) => void;
  onDragStart: () => void;
  onDragEnd: () => void;
}) {
  const { selectLibraryItem, openLibraryItem } = useLibraryItemClick({
    onSingleClick: onSelect,
    onDoubleClick: onOpen,
  });

  // While ingestion runs (or fails) the card is shown in a non-interactive
  // loading state; it "matures" into a normal clickable card once ready.
  const isProcessing =
    artifact.indexingStatus === "pending" || artifact.indexingStatus === "failed";
  const processingFailed = artifact.indexingStatus === "failed";

  return (
    <ContextMenu>
      <ContextMenuTrigger asChild>
        <div
          ref={refCallback}
          className={cn("group relative", isDragging && "opacity-50")}
          draggable={!isProcessing}
          onDragStart={(event) => {
            if (isProcessing) {
              event.preventDefault();
              return;
            }
            event.dataTransfer.effectAllowed = "move";
            event.dataTransfer.setData("text/plain", artifact._id);
            onDragStart();
          }}
          onDragEnd={onDragEnd}
        >
          <LibraryArtifactCard
            title={artifact.title}
            artifactType={artifact.artifactType}
            source={artifact.source}
            createdAt={artifact.createdAt}
            isSelected={isSelected}
            isProcessing={isProcessing}
            processingFailed={processingFailed}
            onClick={selectLibraryItem}
            onDoubleClick={openLibraryItem}
          />
        </div>
      </ContextMenuTrigger>
      <ArtifactContextMenuContent
        moveTargets={moveTargets}
        workspaces={workspaces}
        artifactHref={`/app/workspaces/${workspaceId}/artifacts/${artifact._id}`}
        isSelected={isSelected}
        onSelect={onSelect}
        onOpen={onOpen}
        onRename={onRename}
        onDelete={onDelete}
        onMove={onMove}
        onMoveToWorkspace={onMoveToWorkspace}
      />
    </ContextMenu>
  );
}
