// apps/web/components/app-sidebar.tsx
"use client";

import { NavUser } from "@/components/nav-user";
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from "@/components/ui/sidebar";
import { cn } from "@/lib/utils";
import {
  HomeIcon,
  LayoutGridIcon,
  MessageSquareIcon,
  PanelLeftIcon,
  PlusIcon,
  SearchIcon,
  SettingsIcon,
  TrendingUpIcon,
} from "@aqsha/ui/icons";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { NameDialog } from "@/features/workspaces/components/workspace-dialogs";
import { ThreadDeleteActions } from "@/features/thread-experience/components/thread-actions-menu";
import type {
  RemoveThread,
  ThreadSummary,
} from "@/features/thread-experience/components/component-types";
import {
  type ComponentProps,
  type ReactNode,
  useEffect,
  useState,
} from "react";

type Viewer = {
  name: string | null;
  email: string | null;
  image: string | null;
};

type WorkspaceSummary = {
  _id: string;
  name: string;
  emoji?: string;
  updatedAt?: number;
};

const emptyWorkspaces: WorkspaceSummary[] = [];
const MOBILE_THREAD_TITLE_MAX_CHARS = 42;
const sidebarItemBaseClass =
  "h-8 gap-2 rounded-[8px] px-2.5 py-0 text-[12px] font-medium transition-[background-color,color,box-shadow] duration-150 ease-out hover:bg-muted/60 data-active:bg-primary/10 data-active:font-medium data-active:text-foreground data-active:shadow-none data-active:[&_svg]:text-primary hover:text-foreground active:bg-muted active:text-foreground [&_svg]:size-3.5";

function sidebarItemClass(active?: boolean) {
  return cn(
    sidebarItemBaseClass,
    active
      ? "bg-primary/10 text-foreground [&_svg]:text-primary"
      : "text-muted-foreground [&_svg]:text-muted-foreground hover:[&_svg]:text-primary/70",
  );
}

export function AppSidebar({
  viewer,
  workspaces = emptyWorkspaces,
  selectedWorkspaceId,
  threads,
  selectedThreadId,
  onCreateThread,
  createWorkspace,
  removeThread,
  ...props
}: ComponentProps<typeof Sidebar> & {
  viewer: Viewer | undefined;
  workspaces?: WorkspaceSummary[];
  selectedWorkspaceId?: string;
  threads: ThreadSummary[];
  selectedThreadId?: string;
  onCreateThread: () => void;
  createWorkspace?: (args: { name: string }) => Promise<unknown>;
  removeThread?: RemoveThread;
}) {
  const pathname = usePathname();
  const router = useRouter();
  const [commandOpen, setCommandOpen] = useState(false);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const { isMobile, setOpen, setOpenMobile } = useSidebar();
  const sortedWorkspaces = workspaces.toSorted(
    (left, right) => (right.updatedAt ?? 0) - (left.updatedAt ?? 0),
  );
  const sortedThreads = threads.toSorted(
    (left, right) => right.lastActivityAt - left.lastActivityAt,
  );
  const isHomeActive = pathname === "/app" && !selectedThreadId;
  const isWorkspaceRoute = pathname.startsWith("/app/workspaces");
  const isExploreActive = pathname.startsWith("/app/explore");
  const showWorkspaceSection =
    sortedWorkspaces.length > 0 || Boolean(createWorkspace);
  const showThreadSection = sortedThreads.length > 0 || Boolean(onCreateThread);
  const hasSidebarItems = showWorkspaceSection || showThreadSection;
  const workspaceSectionAction = createWorkspace ? (
    <button
      type="button"
      onClick={() => setCreateDialogOpen(true)}
      className="flex size-5 shrink-0 items-center justify-center rounded-[5px] text-muted-foreground transition-[background-color,color] duration-150 ease-out hover:bg-primary/10 hover:text-primary"
      aria-label="Workspace baru"
    >
      <PlusIcon className="size-3" />
    </button>
  ) : null;

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") {
        event.preventDefault();
        setCommandOpen(true);
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const runCreateThread = () => {
    setCommandOpen(false);
    onCreateThread();
  };

  const threadSectionAction = (
    <button
      type="button"
      onClick={runCreateThread}
      className="flex size-5 shrink-0 items-center justify-center rounded-[5px] text-muted-foreground transition-[background-color,color] duration-150 ease-out hover:bg-primary/10 hover:text-primary"
      aria-label="Thread baru"
    >
      <PlusIcon className="size-3" />
    </button>
  );

  const runCreateWorkspace = () => {
    setCommandOpen(false);
    setCreateDialogOpen(true);
  };

  const closeSidebar = () => {
    if (isMobile) {
      setOpenMobile(false);
      return;
    }
    setOpen(false);
  };

  const handleDeleteThread = async (thread: ThreadSummary) => {
    if (!removeThread) return;
    await removeThread({ threadId: thread.threadId });
    if (pathname === `/app/threads/${thread.threadId}`) {
      router.replace(
        thread.workspaceId ? `/app/workspaces/${thread.workspaceId}` : "/app",
      );
    }
  };

  return (
    <>
      <Sidebar
        collapsible="offcanvas"
        variant="flush"
        {...props}
      >
        <SidebarHeader className="gap-3 px-3 pb-3 pt-3.5">
          <div className="flex items-center gap-1.5 pl-1.5 pr-2.5">
            <button
              type="button"
              onClick={closeSidebar}
              className="flex size-6 items-center justify-center rounded-[6px] text-muted-foreground transition-[background-color,color] duration-150 ease-out hover:bg-primary/10 hover:text-primary"
              aria-label="Tutup sidebar kiri"
            >
              <PanelLeftIcon className="size-3.5" />
            </button>
            <button
              type="button"
              onClick={() => setCommandOpen(true)}
              className="flex size-6 items-center justify-center rounded-[6px] text-muted-foreground transition-[background-color,color] duration-150 ease-out hover:bg-primary/10 hover:text-primary"
              aria-label="Cari thread"
            >
              <SearchIcon className="size-3.5" />
            </button>
          </div>

          <SidebarMenu className="gap-1">
            <PrimaryNavLink
              href="/app"
              icon={HomeIcon}
              label="Home"
              active={isHomeActive}
            />
            <PrimaryNavLink
              href="/app/explore"
              icon={TrendingUpIcon}
              label="Jelajahi"
              active={isExploreActive}
            />
          </SidebarMenu>
        </SidebarHeader>

        <SidebarContent className="min-h-0 px-3 pb-3 pt-2">
          <ScrollArea className="min-h-0 min-w-0 flex-1 overflow-hidden px-0">
            <div className="grid min-w-0 gap-5 overflow-hidden">
              {!hasSidebarItems ? (
                <div className="rounded-[8px] border border-dashed border-mint-soft-border bg-mint-soft/50 px-3 py-4 text-center text-[12px] leading-relaxed text-muted-foreground">
                  Belum ada thread atau workspace.
                </div>
              ) : (
                <>
                  {showWorkspaceSection ? (
                    <SidebarSection
                      label="Workspaces"
                      first
                      action={workspaceSectionAction}
                    >
                      {sortedWorkspaces.length > 0 ? (
                        <SidebarMenu className="min-w-0 gap-1 overflow-hidden">
                          {sortedWorkspaces.map((workspace) => (
                            <RecentWorkspaceRow
                              key={workspace._id}
                              workspace={workspace}
                              active={
                                isWorkspaceRoute &&
                                workspace._id === selectedWorkspaceId
                              }
                            />
                          ))}
                        </SidebarMenu>
                      ) : (
                        <EmptyWorkspaceRow
                          onCreate={
                            createWorkspace ? runCreateWorkspace : undefined
                          }
                        />
                      )}
                    </SidebarSection>
                  ) : null}
                  {showThreadSection ? (
                    <SidebarSection
                      label="Threads"
                      action={threadSectionAction}
                    >
                      {sortedThreads.length > 0 ? (
                        <SidebarMenu className="min-w-0 gap-1 overflow-hidden">
                          {sortedThreads.map((thread) => (
                            <RecentThreadRow
                              key={thread.threadId}
                              thread={thread}
                              active={thread.threadId === selectedThreadId}
                              onDelete={
                                removeThread
                                  ? () => handleDeleteThread(thread)
                                  : undefined
                              }
                            />
                          ))}
                        </SidebarMenu>
                      ) : (
                        <EmptyThreadRow onCreate={runCreateThread} />
                      )}
                    </SidebarSection>
                  ) : null}
                </>
              )}
            </div>
          </ScrollArea>
        </SidebarContent>

        <SidebarFooter className="mt-auto p-3">
          <NavUser user={viewer} />
        </SidebarFooter>
      </Sidebar>

      <CommandDialog open={commandOpen} onOpenChange={setCommandOpen}>
        {commandOpen ? (
          <>
            <CommandInput placeholder="Cari atau buat..." />
            <CommandList>
              <CommandEmpty>Tidak ada hasil.</CommandEmpty>
              <CommandGroup heading="Buat">
                <CommandItem onSelect={runCreateThread}>
                  <MessageSquareIcon className="size-4" />
                  Chat baru
                </CommandItem>
                {createWorkspace ? (
                  <CommandItem onSelect={runCreateWorkspace}>
                    <LayoutGridIcon className="size-4" />
                    Workspace baru
                  </CommandItem>
                ) : null}
              </CommandGroup>
              <CommandGroup heading="Buka">
                <CommandItem
                  value="buka-beranda"
                  onSelect={() => setCommandOpen(false)}
                  asChild
                >
                  <Link href="/app">
                    <HomeIcon className="size-4" />
                    Beranda
                  </Link>
                </CommandItem>
                <CommandItem
                  value="buka-jelajahi"
                  onSelect={() => setCommandOpen(false)}
                  asChild
                >
                  <Link href="/app/explore">
                    <TrendingUpIcon className="size-4" />
                    Jelajahi
                  </Link>
                </CommandItem>
                <CommandItem
                  value="buka-pengaturan"
                  onSelect={() => setCommandOpen(false)}
                  asChild
                >
                  <Link href="/app/settings">
                    <SettingsIcon className="size-4" />
                    Pengaturan
                  </Link>
                </CommandItem>
              </CommandGroup>
              {sortedWorkspaces.length > 0 ? (
                <CommandGroup heading="Workspaces">
                  {sortedWorkspaces.map((workspace) => (
                    <CommandItem
                      key={workspace._id}
                      value={`workspace-${workspace.name}`}
                      onSelect={() => setCommandOpen(false)}
                      asChild
                    >
                      <Link href={`/app/workspaces/${workspace._id}`}>
                        <WorkspaceEmojiGlyph emoji={workspace.emoji} />
                        <span className="truncate">{workspace.name}</span>
                      </Link>
                    </CommandItem>
                  ))}
                </CommandGroup>
              ) : null}
              {sortedThreads.length > 0 ? (
                <CommandGroup heading="Threads">
                  {sortedThreads.map((thread) => (
                    <CommandItem
                      key={thread.threadId}
                      value={`thread-${thread.title}`}
                      onSelect={() => setCommandOpen(false)}
                      asChild
                    >
                      <Link href={`/app/threads/${thread.threadId}`}>
                        <MessageSquareIcon className="size-4" />
                        <span className="truncate">{thread.title}</span>
                      </Link>
                    </CommandItem>
                  ))}
                </CommandGroup>
              ) : null}
            </CommandList>
          </>
        ) : null}
      </CommandDialog>
      {createWorkspace ? (
        <NameDialog
          open={createDialogOpen}
          onOpenChange={setCreateDialogOpen}
          title="Workspace baru"
          description="Buat area riset personal."
          submitLabel="Buat"
          onSubmit={async ({ name }) => {
            const workspaceId = await createWorkspace({ name });
            router.push(`/app/workspaces/${String(workspaceId)}`);
          }}
        />
      ) : null}
    </>
  );
}

function PrimaryNavLink({
  href,
  icon: Icon,
  label,
  active,
}: {
  href: string;
  icon: typeof HomeIcon;
  label: string;
  active?: boolean;
}) {
  return (
    <SidebarMenuItem className="min-w-0 overflow-hidden">
      <SidebarMenuButton
        asChild
        isActive={active}
        size="sm"
        className={sidebarItemClass(active)}
      >
        <Link href={href}>
          <Icon className="size-3.5 shrink-0" />
          <span>{label}</span>
        </Link>
      </SidebarMenuButton>
    </SidebarMenuItem>
  );
}

function SidebarSection({
  label,
  children,
  first,
  action,
}: {
  label: string;
  children: ReactNode;
  first?: boolean;
  action?: ReactNode;
}) {
  return (
    <div className="min-w-0 overflow-hidden">
      <div
        className={cn(
          "flex items-center justify-between gap-1 px-0.5 pb-1.5",
          first ? "pt-0" : "pt-1",
        )}
      >
        <span className="text-[11px] font-medium tracking-[-0.01em] text-primary/75">
          {label}
        </span>
        {action}
      </div>
      {children}
    </div>
  );
}

function RecentThreadRow({
  thread,
  active,
  onDelete,
}: {
  thread: ThreadSummary;
  active: boolean;
  onDelete?: () => Promise<void>;
}) {
  const deleteDescription = thread.workspaceId
    ? "Thread dan pesannya akan dihapus permanen dari workspace ini."
    : "Thread dan pesannya akan dihapus permanen.";

  return (
    <SidebarMenuItem className="min-w-0 overflow-hidden">
      <SidebarMenuButton
        asChild
        size="sm"
        isActive={active}
        className={cn(
          sidebarItemClass(active),
          "w-full min-w-0 max-w-full overflow-hidden",
          onDelete ? "pr-8" : undefined,
        )}
      >
        <Link
          href={`/app/threads/${thread.threadId}`}
          aria-label={thread.title}
          title={thread.title}
          className="flex min-w-0 max-w-full items-center gap-2 overflow-hidden"
        >
          <MessageSquareIcon className="size-3.5 shrink-0" />
          <span className="min-w-0 flex-1 truncate font-normal">
            {truncateCharacters(thread.title, MOBILE_THREAD_TITLE_MAX_CHARS)}
          </span>
          {thread.status === "streaming" ? (
            <span className="ml-auto inline-flex size-1.5 shrink-0 rounded-full bg-primary" />
          ) : null}
        </Link>
      </SidebarMenuButton>
      {onDelete ? (
        <ThreadDeleteActions
          variant="sidebar-row"
          description={deleteDescription}
          onDelete={onDelete}
        />
      ) : null}
    </SidebarMenuItem>
  );
}

function EmptyWorkspaceRow({ onCreate }: { onCreate?: () => void }) {
  if (onCreate) {
    return (
      <button
        type="button"
        onClick={onCreate}
        className="flex h-8 w-full min-w-0 items-center gap-2 rounded-[8px] px-2.5 text-left text-[12px] font-medium text-muted-foreground transition-[background-color,color] duration-150 ease-out hover:bg-muted/60 hover:text-foreground"
      >
        <LayoutGridIcon className="size-3.5 shrink-0 text-muted-foreground" />
        <span className="min-w-0 flex-1 truncate">Buat workspace pertama</span>
        <PlusIcon className="size-3 shrink-0 text-muted-foreground" />
      </button>
    );
  }

  return (
    <div className="rounded-[8px] border border-dashed border-border/70 px-2.5 py-2 text-[11px] font-medium leading-5 text-muted-foreground">
      Belum ada workspace.
    </div>
  );
}

function EmptyThreadRow({ onCreate }: { onCreate: () => void }) {
  return (
    <button
      type="button"
      onClick={onCreate}
      className="flex h-8 w-full min-w-0 items-center gap-2 rounded-[8px] px-2.5 text-left text-[12px] font-medium text-muted-foreground transition-[background-color,color] duration-150 ease-out hover:bg-muted/60 hover:text-foreground"
    >
      <MessageSquareIcon className="size-3.5 shrink-0 text-muted-foreground" />
      <span className="min-w-0 flex-1 truncate">Buat thread baru</span>
      <PlusIcon className="size-3 shrink-0 text-muted-foreground" />
    </button>
  );
}

function RecentWorkspaceRow({
  workspace,
  active,
}: {
  workspace: WorkspaceSummary;
  active: boolean;
}) {
  return (
    <SidebarMenuItem className="min-w-0 overflow-hidden">
      <SidebarMenuButton
        asChild
        size="sm"
        isActive={active}
        className={cn(
          sidebarItemClass(active),
          "w-full min-w-0 max-w-full overflow-hidden",
        )}
      >
        <Link
          href={`/app/workspaces/${workspace._id}`}
          className="flex min-w-0 max-w-full items-center gap-2 overflow-hidden"
        >
          <WorkspaceEmojiGlyph emoji={workspace.emoji} active={active} />
          <span className="min-w-0 flex-1 truncate font-normal">
            {workspace.name}
          </span>
        </Link>
      </SidebarMenuButton>
    </SidebarMenuItem>
  );
}

function WorkspaceEmojiGlyph({
  emoji,
  active,
}: {
  emoji?: string;
  active?: boolean;
}) {
  return (
    <span
      aria-hidden="true"
      className={cn(
        "flex size-4 shrink-0 items-center justify-center rounded-[5px] text-[13px] leading-none",
        active ? "bg-background/70" : "bg-muted/35",
      )}
    >
      {emoji?.trim() || "📚"}
    </span>
  );
}

function truncateCharacters(value: string, maxLength: number) {
  const trimmed = value.trim();
  if (trimmed.length <= maxLength) return trimmed;
  return `${trimmed.slice(0, maxLength - 1).trimEnd()}...`;
}

// apps/svelte/src/lib/components/layout/AppSidebar.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { page } from '$app/state';
	import * as Sidebar from '$lib/components/ui/sidebar/index.js';
	import * as Command from '$lib/components/ui/command/index.js';
	import NavUser from './NavUser.svelte';
	import SidebarSection from './sidebar/SidebarSection.svelte';
	import ThreadArchiveGroup from './sidebar/ThreadArchiveGroup.svelte';
	import ThreadActionsMenu from '$lib/features/thread-experience/components/ThreadActionsMenu.svelte';
	import CreateWorkspacePopover from '$lib/features/workspaces/components/CreateWorkspacePopover.svelte';
	import NameDialog from '$lib/features/workspaces/components/NameDialog.svelte';
	import {
		useWorkspaceIndexData,
		type SidebarThread,
		type SidebarWorkspace
	} from '$lib/features/workspaces/api/use-workspaces-data';
	import {
		Icon,
		HomeIcon,
		LayoutGridIcon,
		MessageSquareIcon,
		PanelLeftIcon,
		PinIcon,
		PlusIcon,
		SearchIcon,
		SettingsIcon,
		TrendingUpIcon
	} from '$lib/icons';
	import { cn } from '$lib/utils';

	/**
	 * Left navigation rail. Fetches sidebar data via `useWorkspaceIndexData()` (reactive getters);
	 * selection derives from the route. Renders the workspace tree + thread groups (pinned / recent /
	 * older) with per-row `ThreadActionsMenu`, `CreateWorkspacePopover`, collapsible sections, and the
	 * ⌘K command palette.
	 */
	const MOBILE_THREAD_TITLE_MAX_CHARS = 42;
	const THREADS_COLLAPSED_STORAGE_KEY = 'aqsha:sidebar:threads-collapsed';
	const WORKSPACES_COLLAPSED_STORAGE_KEY = 'aqsha:sidebar:workspaces-collapsed';
	const sidebarItemBaseClass =
		'h-8 gap-2 rounded-[8px] px-2.5 py-0 text-[12px] font-medium transition-[background-color,color,box-shadow] duration-150 ease-out hover:bg-muted/60 data-active:bg-primary/10 data-active:font-medium data-active:text-foreground data-active:shadow-none data-active:[&_svg]:text-primary hover:text-foreground active:bg-muted active:text-foreground [&_svg]:size-3.5';

	function sidebarItemClass(active?: boolean) {
		return cn(
			sidebarItemBaseClass,
			active
				? 'bg-primary/10 text-foreground [&_svg]:text-primary'
				: 'text-muted-foreground [&_svg]:text-muted-foreground hover:[&_svg]:text-primary/70'
		);
	}

	const sidebar = Sidebar.useSidebar();
	const data = useWorkspaceIndexData();

	let commandOpen = $state(false);
	let createDialogOpen = $state(false);

	const pathname = $derived(page.url.pathname);
	const selectedThreadId = $derived(page.params.threadId);
	const selectedWorkspaceId = $derived(page.params.workspaceId);
	const isHomeActive = $derived(pathname === '/app' && !selectedThreadId);
	const isWorkspaceRoute = $derived(pathname.startsWith('/app/workspaces'));
	const isExploreActive = $derived(pathname.startsWith('/app/explore'));

	const sortedWorkspaces = $derived(
		[...data.workspaces].sort((a, b) => (b.updatedAt ?? 0) - (a.updatedAt ?? 0))
	);
	const sortedThreads = $derived(
		[...data.threads].sort((a, b) => b.lastActivityAt - a.lastActivityAt)
	);
	// Thread yang disematkan diangkat ke grup "Disematkan" (urut pinnedAt DESC). Sisanya (unpinned)
	// dipisah recent/older dari BE (ThreadService.list `bucket`).
	const pinnedThreads = $derived(
		data.threads
			.filter((t) => t.pinnedAt != null)
			.sort((a, b) => (b.pinnedAt ?? 0) - (a.pinnedAt ?? 0))
	);
	const unpinnedThreads = $derived(sortedThreads.filter((t) => t.pinnedAt == null));
	const recentThreads = $derived(unpinnedThreads.filter((t) => t.bucket !== 'older'));
	const olderThreads = $derived(unpinnedThreads.filter((t) => t.bucket === 'older'));

	async function submitCreateWorkspace({ name }: { name: string }) {
		const workspaceId = await data.createWorkspace({ name });
		await goto(
			resolve('/app/(product)/workspaces/[workspaceId]', { workspaceId: String(workspaceId) })
		);
	}

	function runCreateThread() {
		commandOpen = false;
		void goto(resolve('/app/(product)'));
	}

	function runCreateWorkspace() {
		commandOpen = false;
		createDialogOpen = true;
	}

	function closeSidebar() {
		if (sidebar.isMobile) {
			sidebar.setOpenMobile(false);
			return;
		}
		sidebar.setOpen(false);
	}

	async function handleDeleteThread(thread: SidebarThread) {
		await data.removeThread({ threadId: thread.threadId });
		if (pathname === `/app/threads/${thread.threadId}`) {
			if (thread.workspaceId) {
				await goto(
					resolve('/app/(product)/workspaces/[workspaceId]', { workspaceId: thread.workspaceId })
				);
			} else {
				await goto(resolve('/app/(product)'));
			}
		}
	}

	async function handleTogglePin(thread: SidebarThread) {
		await data.togglePinThread({ threadId: thread.threadId, pinned: thread.pinnedAt == null });
	}

	function truncateCharacters(value: string, maxLength: number) {
		const trimmed = value.trim();
		if (trimmed.length <= maxLength) return trimmed;
		return `${trimmed.slice(0, maxLength - 1).trimEnd()}...`;
	}

	function handleShortcut(event: KeyboardEvent) {
		if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
			event.preventDefault();
			commandOpen = true;
		}
	}
</script>

<svelte:window onkeydown={handleShortcut} />

{#snippet workspaceEmojiGlyph(emoji: string | undefined, active: boolean)}
	<span
		aria-hidden="true"
		class={cn(
			'flex size-4 shrink-0 items-center justify-center rounded-[5px] text-[13px] leading-none',
			active ? 'bg-background/70' : 'bg-muted/35'
		)}
	>
		{emoji?.trim() || '📚'}
	</span>
{/snippet}

{#snippet workspaceRow(workspace: SidebarWorkspace)}
	{@const active = isWorkspaceRoute && workspace._id === selectedWorkspaceId}
	<Sidebar.MenuItem class="min-w-0 overflow-hidden">
		<Sidebar.MenuButton
			isActive={active}
			size="sm"
			class={cn(sidebarItemClass(active), 'w-full min-w-0 max-w-full overflow-hidden')}
		>
			{#snippet child({ props })}
				<a
					{...props}
					href={resolve('/app/(product)/workspaces/[workspaceId]', { workspaceId: workspace._id })}
					class="flex min-w-0 max-w-full items-center gap-2 overflow-hidden"
				>
					{@render workspaceEmojiGlyph(workspace.emoji, active)}
					<span class="min-w-0 flex-1 truncate font-normal">{workspace.name}</span>
				</a>
			{/snippet}
		</Sidebar.MenuButton>
	</Sidebar.MenuItem>
{/snippet}

{#snippet threadRow(thread: SidebarThread)}
	{@const active = thread.threadId === selectedThreadId}
	{@const isPinned = thread.pinnedAt != null}
	{@const deleteDescription = thread.workspaceId
		? 'Thread dan pesannya akan dihapus permanen dari workspace ini.'
		: 'Thread dan pesannya akan dihapus permanen.'}
	<Sidebar.MenuItem class="min-w-0 overflow-hidden">
		<Sidebar.MenuButton
			isActive={active}
			size="sm"
			class={cn(sidebarItemClass(active), 'w-full min-w-0 max-w-full overflow-hidden pr-8')}
		>
			{#snippet child({ props })}
				<a
					{...props}
					href={resolve('/app/(product)/threads/[threadId]', { threadId: thread.threadId })}
					aria-label={thread.title}
					title={thread.title}
					class="flex min-w-0 max-w-full items-center gap-2 overflow-hidden"
				>
					<Icon icon={MessageSquareIcon} class="size-3.5 shrink-0" />
					<span class="min-w-0 flex-1 truncate font-normal">
						{truncateCharacters(thread.title, MOBILE_THREAD_TITLE_MAX_CHARS)}
					</span>
					{#if isPinned}
						<Icon icon={PinIcon} class="size-3 shrink-0 text-primary/50" />
					{/if}
					{#if thread.status === 'streaming'}
						<span class="inline-flex size-1.5 shrink-0 rounded-full bg-primary"></span>
					{/if}
				</a>
			{/snippet}
		</Sidebar.MenuButton>
		<ThreadActionsMenu
			variant="sidebar-row"
			description={deleteDescription}
			onDelete={() => handleDeleteThread(thread)}
			{isPinned}
			onTogglePin={() => handleTogglePin(thread)}
		/>
	</Sidebar.MenuItem>
{/snippet}

<Sidebar.Root collapsible="offcanvas" variant="transparent">
	<Sidebar.Header class="gap-3 px-3 pb-3 pt-3.5">
		<div class="flex items-center gap-1.5 pl-1.5 pr-2.5">
			<button
				type="button"
				onclick={closeSidebar}
				class="flex size-6 items-center justify-center rounded-[6px] text-muted-foreground transition-[background-color,color] duration-150 ease-out hover:bg-primary/10 hover:text-primary"
				aria-label="Tutup sidebar kiri"
			>
				<Icon icon={PanelLeftIcon} class="size-3.5" />
			</button>
			<button
				type="button"
				onclick={() => (commandOpen = true)}
				class="flex size-6 items-center justify-center rounded-[6px] text-muted-foreground transition-[background-color,color] duration-150 ease-out hover:bg-primary/10 hover:text-primary"
				aria-label="Cari thread"
			>
				<Icon icon={SearchIcon} class="size-3.5" />
			</button>
		</div>

		<Sidebar.Menu class="gap-1">
			<Sidebar.MenuItem class="min-w-0 overflow-hidden">
				<Sidebar.MenuButton
					isActive={isHomeActive}
					size="sm"
					class={sidebarItemClass(isHomeActive)}
				>
					{#snippet child({ props })}
						<a {...props} href={resolve('/app/(product)')}>
							<Icon icon={HomeIcon} class="size-3.5 shrink-0" />
							<span>Home</span>
						</a>
					{/snippet}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
			<Sidebar.MenuItem class="min-w-0 overflow-hidden">
				<Sidebar.MenuButton
					isActive={isExploreActive}
					size="sm"
					class={sidebarItemClass(isExploreActive)}
				>
					{#snippet child({ props })}
						<a {...props} href={resolve('/app/(product)/explore')}>
							<Icon icon={TrendingUpIcon} class="size-3.5 shrink-0" />
							<span>Jelajahi</span>
						</a>
					{/snippet}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Header>

	<Sidebar.Content class="min-h-0 px-3 pb-3 pt-2">
		<div class="grid min-w-0 gap-5 overflow-hidden">
			<SidebarSection
				label="Workspaces"
				first
				collapsible
				storageKey={WORKSPACES_COLLAPSED_STORAGE_KEY}
			>
				{#snippet action()}
					<CreateWorkspacePopover onSubmit={submitCreateWorkspace} />
				{/snippet}
				{#if sortedWorkspaces.length > 0}
					<Sidebar.Menu class="min-w-0 gap-1 overflow-hidden">
						{#each sortedWorkspaces as workspace (workspace._id)}
							{@render workspaceRow(workspace)}
						{/each}
					</Sidebar.Menu>
				{:else}
					<div
						class="rounded-[8px] border border-dashed border-border/70 px-2.5 py-2 text-[11px] font-medium leading-5 text-muted-foreground"
					>
						Belum ada workspace.
					</div>
				{/if}
			</SidebarSection>

			<SidebarSection label="Threads" collapsible storageKey={THREADS_COLLAPSED_STORAGE_KEY}>
				{#snippet action()}
					<button
						type="button"
						onclick={runCreateThread}
						class="flex size-5 shrink-0 items-center justify-center rounded-[5px] text-muted-foreground transition-[background-color,color] duration-150 ease-out hover:bg-primary/10 hover:text-primary"
						aria-label="Thread baru"
					>
						<Icon icon={PlusIcon} class="size-3" />
					</button>
				{/snippet}
				{#if sortedThreads.length > 0}
					<div class="min-w-0 overflow-hidden">
						<Sidebar.Menu class="min-w-0 gap-1 overflow-hidden">
							{#if pinnedThreads.length > 0}
								<li role="presentation" aria-hidden="true" class="flex items-center gap-1 px-1">
									<Icon icon={PinIcon} class="size-3 shrink-0 text-primary/60" />
									<span
										class="min-w-0 flex-1 truncate text-[11px] font-medium text-muted-foreground"
									>
										Disematkan
									</span>
								</li>
								{#each pinnedThreads as thread (thread.threadId)}
									{@render threadRow(thread)}
								{/each}
							{/if}
							{#each recentThreads as thread (thread.threadId)}
								{@render threadRow(thread)}
							{/each}
						</Sidebar.Menu>
						{#if olderThreads.length > 0}
							<ThreadArchiveGroup threads={olderThreads} {selectedThreadId} {threadRow} />
						{/if}
					</div>
				{:else}
					<div
						class="rounded-[8px] border border-dashed border-border/70 px-2.5 py-2 text-[11px] font-medium leading-5 text-muted-foreground"
					>
						Belum ada thread.
					</div>
				{/if}
			</SidebarSection>
		</div>
	</Sidebar.Content>

	<Sidebar.Footer class="mt-auto gap-3 p-3">
		<NavUser />
	</Sidebar.Footer>
</Sidebar.Root>

<Command.Dialog bind:open={commandOpen}>
	<Command.Input placeholder="Cari atau buat..." />
	<Command.List>
		<Command.Empty>Tidak ada hasil.</Command.Empty>
		<Command.Group heading="Buat">
			<Command.Item onSelect={runCreateThread}>
				<Icon icon={MessageSquareIcon} class="size-4" />
				Chat baru
			</Command.Item>
			<Command.Item onSelect={runCreateWorkspace}>
				<Icon icon={LayoutGridIcon} class="size-4" />
				Workspace baru
			</Command.Item>
		</Command.Group>
		<Command.Group heading="Buka">
			<Command.Item
				value="buka-beranda"
				onSelect={() => {
					commandOpen = false;
					goto(resolve('/app/(product)'));
				}}
			>
				<Icon icon={HomeIcon} class="size-4" />
				Beranda
			</Command.Item>
			<Command.Item
				value="buka-jelajahi"
				onSelect={() => {
					commandOpen = false;
					goto(resolve('/app/(product)/explore'));
				}}
			>
				<Icon icon={TrendingUpIcon} class="size-4" />
				Jelajahi
			</Command.Item>
			<Command.Item
				value="buka-pengaturan"
				onSelect={() => {
					commandOpen = false;
					goto(resolve('/app/settings/overview'));
				}}
			>
				<Icon icon={SettingsIcon} class="size-4" />
				Pengaturan
			</Command.Item>
		</Command.Group>
		{#if sortedWorkspaces.length > 0}
			<Command.Group heading="Workspaces">
				{#each sortedWorkspaces as workspace (workspace._id)}
					<Command.Item
						value={`workspace-${workspace._id}`}
						keywords={[workspace.name]}
						onSelect={() => {
							commandOpen = false;
							goto(
								resolve('/app/(product)/workspaces/[workspaceId]', { workspaceId: workspace._id })
							);
						}}
					>
						{@render workspaceEmojiGlyph(workspace.emoji, false)}
						<span class="truncate">{workspace.name}</span>
					</Command.Item>
				{/each}
			</Command.Group>
		{/if}
		{#if sortedThreads.length > 0}
			<Command.Group heading="Threads">
				{#each sortedThreads as thread (thread.threadId)}
					<Command.Item
						value={`thread-${thread.threadId}`}
						keywords={[thread.title]}
						onSelect={() => {
							commandOpen = false;
							goto(resolve('/app/(product)/threads/[threadId]', { threadId: thread.threadId }));
						}}
					>
						<Icon icon={MessageSquareIcon} class="size-4" />
						<span class="truncate">{thread.title}</span>
					</Command.Item>
				{/each}
			</Command.Group>
		{/if}
	</Command.List>
</Command.Dialog>

<NameDialog
	open={createDialogOpen}
	onOpenChange={(open) => (createDialogOpen = open)}
	title="Workspace baru"
	description="Buat area riset personal."
	submitLabel="Buat"
	onSubmit={submitCreateWorkspace}
/>
