// apps/web/components/app-shell.tsx
"use client";

import { type CSSProperties, type ReactNode } from "react";
import { useParams, useRouter } from "next/navigation";

import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { useWorkspaceIndexData } from "@/features/workspaces/api/use-workspaces-data";

// Persistent shell for every authenticated product surface (threads, workspaces,
// explore). Hoisting the left navigation here — instead of re-rendering it inside
// each page shell — means the sidebar stays mounted across navigations (no
// remount/flicker, no layout shift) and the sidebar data is fetched once. Pages
// render only their content into SidebarInset, which is `relative` so the
// route-level `(product)/loading.tsx` boundary (AppLoadingOverlay
// variant="absolute") fills just the content area without covering the nav.
export function AppShell({
  defaultSidebarOpen,
  children,
}: {
  defaultSidebarOpen: boolean;
  children: ReactNode;
}) {
  const router = useRouter();
  const params = useParams<{ threadId?: string; workspaceId?: string }>();
  const { viewer, workspaces, threads, createWorkspace, removeThread, togglePinThread } =
    useWorkspaceIndexData();

  // Selected state is fully derivable from the URL. For a thread route we don't
  // know the owning workspace from the path alone, so resolve it from the
  // already-fetched thread list to keep the workspace row highlighted.
  const selectedThreadId = params?.threadId;
  const selectedWorkspaceId =
    params?.workspaceId ??
    (selectedThreadId
      ? undefined
      : undefined);

  return (
    <SidebarProvider
      defaultOpen={defaultSidebarOpen}
      style={
        {
          "--sidebar-width": "16.5rem",
          "--sidebar-width-mobile": "17.5rem",
        } as CSSProperties
      }
      className="min-h-svh"
    >
      <AppSidebar
        viewer={viewer}
        workspaces={workspaces}
        selectedWorkspaceId={selectedWorkspaceId}
        threads={threads}
        selectedThreadId={selectedThreadId}
        onCreateThread={() => router.push("/app")}
        createWorkspace={createWorkspace}
        removeThread={removeThread}
        togglePinThread={togglePinThread}
      />
      <SidebarInset className="relative min-h-svh bg-background text-foreground">
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}

// apps/svelte/src/lib/components/layout/AppShell.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import * as Sidebar from '$lib/components/ui/sidebar/index.js';
	import AppSidebar from './AppSidebar.svelte';

	/**
	 * Persistent shell for every authenticated product surface. Hoists the left navigation so it stays mounted
	 * across navigations (no remount/flicker). Pages render into `Sidebar.Inset`, which is
	 * `relative` so a route-level loading overlay (variant="absolute") fills just the content
	 * area, not the nav. `open` is the cookie-persisted initial state (read server-side in
	 * `routes/app/+layout.server.ts`); `Sidebar.Provider` writes the `sidebar_state` cookie on
	 * toggle. `--sidebar-width*` overrides set the rail width (16.5rem / 17.5rem mobile).
	 */
	let { open = true, children }: { open?: boolean; children: Snippet } = $props();
</script>

<Sidebar.Provider
	{open}
	style="--sidebar-width: 16.5rem; --sidebar-width-mobile: 17.5rem;"
	class="min-h-svh"
>
	<AppSidebar />
	<!-- No min-h here: the inset variant adds m-2, so the pane stretches to the provider's
	     min-h-svh row instead (margin-aware), avoiding a 100svh+margin overflow. -->
	<Sidebar.Inset class="relative bg-background text-foreground">
		{@render children()}
	</Sidebar.Inset>
</Sidebar.Provider>
