// apps/svelte/src/lib/features/discovery/components/SaveToWorkspaceButton.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner';
	import { Button, type ButtonSize, type ButtonVariant } from '@aqsha/ui-svelte/components/button';
	import * as Dialog from '@aqsha/ui-svelte/components/dialog';
	import { Icon, FolderIcon } from '$lib/icons';
	import { useSaveUrl } from '$lib/features/artifacts/api';
	import WorkspacePicker from '$lib/features/workspaces/components/WorkspacePicker.svelte';

	/**
	 * Save-to-Workspace button. Opens a workspace picker Dialog then saves the URL via `useSaveUrl` (picks
	 * a workspace only, no folder). `onSaved` fires on real success (discovery interest +1). Used by
	 * discovery cards (icon-only) and the paper reader (labelled).
	 */
	let {
		url,
		title,
		label = 'Simpan',
		ariaLabel,
		variant = 'outline',
		size = 'sm',
		class: className,
		onSaved
	}: {
		url: string;
		title?: string;
		label?: string;
		ariaLabel?: string;
		variant?: ButtonVariant;
		size?: ButtonSize;
		class?: string;
		onSaved?: () => void;
	} = $props();

	const save = useSaveUrl();
	let open = $state(false);
</script>

<Button
	{variant}
	{size}
	class={className}
	aria-label={ariaLabel}
	title={ariaLabel}
	onclick={() => (open = true)}
>
	<Icon icon={FolderIcon} />
	{label}
</Button>

<Dialog.Root bind:open>
	<Dialog.Content class="sm:max-w-sm">
		<Dialog.Header>
			<Dialog.Title>Simpan ke workspace</Dialog.Title>
			<Dialog.Description>Pilih workspace untuk menyimpan tautan ini.</Dialog.Description>
		</Dialog.Header>
		<WorkspacePicker
			disabled={save.isPending}
			onSelect={(workspaceId) =>
				save.mutate(
					{ workspaceId, url, title },
					{
						onSuccess: () => {
							toast.success('Disimpan ke workspace');
							open = false;
							onSaved?.();
						}
					}
				)}
		/>
	</Dialog.Content>
</Dialog.Root>

// apps/web/features/artifacts/components/save-to-workspace-button.tsx
"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@aqsha/ui/components/button";
import { FolderIcon } from "@aqsha/ui/icons";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { WorkspacePicker } from "@/features/workspaces/components/workspace-picker";
import { useSaveUrl } from "../api";

type ButtonVariant = "default" | "outline" | "ghost" | "secondary" | "destructive";
type ButtonSize = "default" | "sm" | "icon";

/**
 * Tombol Save-to-Workspace reusable (createUrl). Pilih workspace via picker → saveUrl.
 * Dipakai reader explore (P4) + mana pun yang punya URL+judul untuk disimpan.
 */
export function SaveToWorkspaceButton({
  url,
  title,
  label = "Simpan",
  ariaLabel,
  variant = "outline",
  size = "sm",
  className,
  onSaved,
}: {
  url: string;
  title?: string;
  label?: string;
  /** For icon-only use (empty label): accessible name + tooltip. */
  ariaLabel?: string;
  variant?: ButtonVariant;
  size?: ButtonSize;
  className?: string;
  /** Dipanggil setelah saveUrl sukses — mis. feed discovery menembak interest bump +1. */
  onSaved?: () => void;
}) {
  const save = useSaveUrl();
  const [open, setOpen] = useState(false);

  return (
    <>
      <Button
        variant={variant}
        size={size}
        className={className}
        aria-label={ariaLabel}
        title={ariaLabel}
        onClick={() => setOpen(true)}
      >
        <FolderIcon />
        {label}
      </Button>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Simpan ke workspace</DialogTitle>
            <DialogDescription>Pilih workspace untuk menyimpan tautan ini.</DialogDescription>
          </DialogHeader>
          <WorkspacePicker
            disabled={save.isPending}
            onSelect={(workspaceId) =>
              save.mutate(
                { workspaceId, url, title },
                {
                  onSuccess: () => {
                    toast.success("Disimpan ke workspace");
                    setOpen(false);
                    onSaved?.();
                  },
                },
              )
            }
          />
        </DialogContent>
      </Dialog>
    </>
  );
}
