// apps/web/components/ui/spinner.tsx
import { cn } from "@/lib/utils"
import { FlickerSpinner } from "./flicker-spinner"

// Canonical loading spinner. Renders the brand `FlickerSpinner` (a theme-aware
// dot-grid that self-animates and respects reduced-motion): color follows the
// `text-*` className via currentColor, size follows the `size-*` className.
function Spinner({ className }: { className?: string }) {
  return <FlickerSpinner className={cn("size-4", className)} />
}

export { Spinner }

// apps/svelte/src/lib/components/ui/spinner/spinner.svelte
<script lang="ts">
	import { cn } from '$lib/utils.js';
	import type { SVGAttributes } from 'svelte/elements';
	import { FlickerSpinner } from '$lib/components/ui/flicker-spinner/index.js';

	/**
	 * Canonical loading spinner. Renders the brand `FlickerSpinner` (theme-aware dot-grid; respects
	 * reduced-motion): color follows the `text-*` class via currentColor, size
	 * follows the `size-*` class (default `size-4`). Rest props (e.g. `data-icon`
	 * for button spacing) flow through to the SVG.
	 */
	let { class: className, ...restProps }: SVGAttributes<SVGSVGElement> = $props();
</script>

<FlickerSpinner class={cn('size-4', className)} {...restProps} />
