// apps/svelte/src/lib/components/ConfirmDialog.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import * as Dialog from '$lib/components/ui/dialog';
	import { Button } from '$lib/components/ui/button';
	import { readableApiErrorMessage } from '$lib/errors';

	/**
	 * Confirm dialog. Controlled `open`, runs an async `onConfirm`, shows a normalized error on
	 * failure and closes on success. `children` (optional) render extra body content between the
	 * description and the footer.
	 */
	let {
		open,
		title,
		description,
		confirmLabel,
		children,
		onOpenChange,
		onConfirm
	}: {
		open: boolean;
		title: string;
		description: string;
		confirmLabel: string;
		children?: Snippet;
		onOpenChange: (open: boolean) => void;
		onConfirm: () => Promise<unknown>;
	} = $props();

	let isSubmitting = $state(false);
	let error = $state<string | null>(null);

	async function handleConfirm() {
		isSubmitting = true;
		error = null;
		try {
			await onConfirm();
			onOpenChange(false);
			isSubmitting = false;
		} catch (submitError) {
			error = readableApiErrorMessage(submitError, 'Aksi gagal.');
			isSubmitting = false;
		}
	}
</script>

<Dialog.Root {open} {onOpenChange}>
	<Dialog.Content class="sm:max-w-md">
		<Dialog.Header>
			<Dialog.Title>{title}</Dialog.Title>
			<Dialog.Description>{description}</Dialog.Description>
		</Dialog.Header>
		{@render children?.()}
		{#if error}
			<p class="text-[12px] font-medium text-destructive">{error}</p>
		{/if}
		<Dialog.Footer>
			<Dialog.Close>
				{#snippet child({ props })}
					<Button type="button" variant="outline" disabled={isSubmitting} {...props}>Batal</Button>
				{/snippet}
			</Dialog.Close>
			<Button type="button" variant="destructive" disabled={isSubmitting} onclick={handleConfirm}>
				{confirmLabel}
			</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>

// apps/web/components/confirm-dialog.tsx
"use client";

import { type ReactNode, useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { readableApiErrorMessage } from "@/lib/api-error";

export function ConfirmDialog({
  open,
  title,
  description,
  confirmLabel,
  children,
  onOpenChange,
  onConfirm,
}: {
  open: boolean;
  title: string;
  description: string;
  confirmLabel: string;
  children?: ReactNode;
  onOpenChange: (open: boolean) => void;
  onConfirm: () => Promise<unknown>;
}) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleConfirm = async () => {
    setIsSubmitting(true);
    setError(null);
    try {
      await onConfirm();
      onOpenChange(false);
      setIsSubmitting(false);
    } catch (submitError) {
      setError(readableApiErrorMessage(submitError, "Aksi gagal."));
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
          <DialogDescription>{description}</DialogDescription>
        </DialogHeader>
        {children}
        {error ? (
          <p className="text-[12px] font-medium text-destructive">{error}</p>
        ) : null}
        <DialogFooter>
          <DialogClose asChild>
            <Button type="button" variant="outline" disabled={isSubmitting}>
              Batal
            </Button>
          </DialogClose>
          <Button
            type="button"
            variant="destructive"
            disabled={isSubmitting}
            onClick={handleConfirm}
          >
            {confirmLabel}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
