// apps/svelte/src/lib/features/threads/components/ElapsedLabel.svelte
<script lang="ts">
	import Shimmer from '$lib/components/ai-elements/Shimmer.svelte';

	/**
	 * "Working" label with a ticking elapsed time (appears after 10s). Deep research awaiting a
	 * task-mode subagent can sit idle for minutes with no event; a running timer reassures "still
	 * working", not frozen. `startedAt` (durable epoch-ms: `steps[id].startedAt` snapshot / user
	 * message `createdAt`) makes the timer survive refresh; without it, mount time. Clamped ≥0 for
	 * client/server clock skew.
	 */
	let { base, startedAt }: { base: string; startedAt?: number } = $props();

	const mountedAt = Date.now();
	let now = $state(mountedAt);
	$effect(() => {
		const timer = setInterval(() => (now = Date.now()), 1000);
		return () => clearInterval(timer);
	});

	const start = $derived(startedAt && startedAt > 0 ? startedAt : mountedAt);
	const secs = $derived(Math.max(0, Math.floor((now - start) / 1000)));
	const label = $derived.by(() => {
		const m = Math.floor(secs / 60);
		const s = secs % 60;
		return secs < 10 ? `${base}…` : `${base}… ${m > 0 ? `${m}m ` : ''}${s}s`;
	});
</script>

<Shimmer as="span" class="font-medium" text={label} />

// apps/web/features/threads/components/elapsed-label.tsx
"use client";

import { useEffect, useState } from "react";
import { Shimmer } from "@/components/ai-elements/shimmer";

/**
 * Label "bekerja" dengan elapsed yang berdetak (muncul setelah 10 dtk). Riset mendalam yang
 * menunggu subagent task-mode bisa diam bermenit-menit tanpa event (child stream tak di-stream
 * ke induk: `childSessionId` 0 baris); timer yang jalan meyakinkan "masih bekerja", bukan beku.
 * Terisolasi → hanya komponen ini yang re-render tiap detik.
 *
 * Dipakai blok "Proses" (`message-list`) DAN row subagent-call yang running (`tool-row`).
 * `startedAt` (epoch-ms durable: `steps[id].startedAt` snapshot `/deep` / `createdAt` pesan user)
 * menjadikan timer selamat-refresh; tanpa itu fallback waktu mount. Boleh tiba TERLAMBAT (poll
 * seed sesudah mount) → dihitung sebagai prop tiap render, bukan di-freeze useState. Clamp ≥0
 * mengantisipasi skew jam client vs server.
 */
export function ElapsedLabel({ base, startedAt }: { base: string; startedAt?: number }) {
  const [mountedAt] = useState(() => Date.now());
  const [now, setNow] = useState(mountedAt);
  useEffect(() => {
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, []);
  const start = startedAt && startedAt > 0 ? startedAt : mountedAt;
  const secs = Math.max(0, Math.floor((now - start) / 1000));
  const m = Math.floor(secs / 60);
  const s = secs % 60;
  const label = secs < 10 ? `${base}…` : `${base}… ${m > 0 ? `${m}m ` : ""}${s}s`;
  return (
    <Shimmer as="span" className="font-medium">
      {label}
    </Shimmer>
  );
}
