// apps/svelte/src/lib/features/threads/components/composer/SlashCommandPalette.svelte
<script lang="ts">
	import { DEEP_COMMAND_ID, type PromptCommand, type PromptCommandId } from '@aqsha/chat-core';
	import {
		type IconSvgElement,
		BookOpenIcon,
		ChartColumnIcon,
		CheckCircle2Icon,
		ExpandParagraphIcon,
		FileTextIcon,
		FlagIcon,
		GitBranchIcon,
		HelpCircleIcon,
		LayoutGridIcon,
		Library,
		MessageSquareIcon,
		NotebookIcon,
		PencilIcon,
		PenLineIcon,
		Quote,
		RotateCcwIcon,
		Scale,
		SearchIcon,
		ShieldCheckIcon,
		ShieldIcon,
		SparklesIcon,
		TableIcon,
		TelescopeIcon,
		TrendingUpIcon,
		WrenchIcon,
		FolderIcon
	} from '$lib/icons';
	import { useBillingCurrent } from '$lib/features/settings/api';
	import { deepRunsQuota } from '$lib/features/settings/lib/billing-derived';
	import ComposerPopoverShell from './ComposerPopoverShell.svelte';
	import ComposerPopoverHeader from './ComposerPopoverHeader.svelte';
	import ComposerPopoverList from './ComposerPopoverList.svelte';
	import ComposerPopoverGroup from './ComposerPopoverGroup.svelte';
	import ComposerPopoverItem from './ComposerPopoverItem.svelte';
	import ComposerPopoverEmpty from './ComposerPopoverEmpty.svelte';
	import ComposerPopoverBadge from './ComposerPopoverBadge.svelte';

	let {
		commands,
		highlightedIndex,
		onHighlight,
		onSelect
	}: {
		commands: PromptCommand[];
		highlightedIndex: number;
		onHighlight: (index: number) => void;
		onSelect: (command: PromptCommand) => void;
	} = $props();

	const promptCommandGroups = [
		'Metodologi',
		'Olah Data',
		'Penulisan Bab',
		'Literatur',
		'Bahasa & Sitasi',
		'Pertahanan',
		'Workspace'
	] as const;

	const promptCommandIconMap: Record<PromptCommandId, IconSvgElement> = {
		kuantitatif: TrendingUpIcon,
		kualitatif: MessageSquareIcon,
		campuran: GitBranchIcon,
		rnd: WrenchIcon,
		analisis: ChartColumnIcon,
		latarbelakang: FileTextIcon,
		rumusanmasalah: HelpCircleIcon,
		tujuan: FlagIcon,
		hipotesis: Scale,
		kerangka: LayoutGridIcon,
		pembahasan: PenLineIcon,
		kesimpulan: CheckCircle2Icon,
		abstrak: BookOpenIcon,
		gap: SearchIcon,
		matriks: TableIcon,
		terdahulu: Library,
		deep: TelescopeIcon,
		akademik: SparklesIcon,
		puebi: ShieldCheckIcon,
		sitasi: Quote,
		parafrase: RotateCcwIcon,
		expand: ExpandParagraphIcon,
		summarize: FileTextIcon,
		sidang: ShieldIcon,
		reviewer: PencilIcon,
		artifact: NotebookIcon,
		workspace: FolderIcon
	};

	// Deep Research quota overlaid on the `/deep` item (app-wide cache, no extra fetch).
	const billing = useBillingCurrent();

	// Flat index across groups (matches keyboard nav order in TokenizedPromptInput).
	const layout = $derived.by(() => {
		let flat = 0;
		return promptCommandGroups
			.map((group) => {
				const groupCommands = commands.filter((item) => item.group === group);
				const startIndex = flat;
				flat += groupCommands.length;
				return { group, groupCommands, startIndex };
			})
			.filter((g) => g.groupCommands.length > 0);
	});
</script>

<ComposerPopoverShell>
	<ComposerPopoverHeader title="Perintah" count={commands.length} />
	<ComposerPopoverList id="composer-slash-commands">
		{#if commands.length === 0}
			<ComposerPopoverEmpty title="Tidak ada perintah yang cocok">
				{#snippet hint()}
					Coba kata kunci lain, mis. <span class="font-mono">kuantitatif</span> atau
					<span class="font-mono">matriks</span>.
				{/snippet}
			</ComposerPopoverEmpty>
		{:else}
			{#each layout as { group, groupCommands, startIndex } (group)}
				<ComposerPopoverGroup label={group}>
					{#each groupCommands as item, index (item.id)}
						{@const itemIndex = startIndex + index}
						<ComposerPopoverItem
							icon={promptCommandIconMap[item.id as PromptCommandId] ?? LayoutGridIcon}
							title={item.label}
							description={item.description}
							active={itemIndex === highlightedIndex}
							onSelect={() => onSelect(item)}
							onMouseEnter={() => onHighlight(itemIndex)}
						>
							{#snippet meta()}
								{#if item.id === DEEP_COMMAND_ID && billing.data}
									{@const quota = deepRunsQuota(billing.data)}
									{#if quota.unlimited}
										<ComposerPopoverBadge tone="muted">tanpa batas</ComposerPopoverBadge>
									{:else}
										<ComposerPopoverBadge tone={quota.remaining > 0 ? 'accent' : 'muted'}>
											{quota.remaining} tersisa
										</ComposerPopoverBadge>
									{/if}
								{/if}
								<span class="font-mono text-[10.5px] text-muted-foreground/70">{item.slug}</span>
							{/snippet}
						</ComposerPopoverItem>
					{/each}
				</ComposerPopoverGroup>
			{/each}
		{/if}
	</ComposerPopoverList>
</ComposerPopoverShell>

// apps/web/features/threads/components/slash-command-palette.tsx
"use client";

import { DEEP_COMMAND_ID, type PromptCommand, type PromptCommandId } from "@aqsha/chat-core";
import {
  BookOpenIcon,
  ChartColumnIcon,
  CheckCircle2Icon,
  ExpandParagraphIcon,
  FileTextIcon,
  FlagIcon,
  FolderIcon,
  GitBranchIcon,
  HelpCircleIcon,
  LayoutGridIcon,
  Library,
  MessageSquareIcon,
  NotebookIcon,
  PencilIcon,
  PenLineIcon,
  Quote,
  RotateCcwIcon,
  Scale,
  SearchIcon,
  ShieldCheckIcon,
  ShieldIcon,
  SparklesIcon,
  TableIcon,
  TelescopeIcon,
  TrendingUpIcon,
  WrenchIcon,
} from "@aqsha/ui/icons";
import type { ComponentType, ReactNode } from "react";
import { useBillingCurrent } from "@/features/settings/api";
import { deepRunsQuota } from "@/features/settings/lib/billing-derived";
import {
  ComposerPopoverBadge,
  ComposerPopoverEmpty,
  ComposerPopoverGroup,
  ComposerPopoverHeader,
  ComposerPopoverItem,
  ComposerPopoverList,
  ComposerPopoverShell,
} from "./composer-popover";

const promptCommandGroups = [
  "Metodologi",
  "Olah Data",
  "Penulisan Bab",
  "Literatur",
  "Bahasa & Sitasi",
  "Pertahanan",
  "Workspace",
] as const;

const promptCommandIconMap: Record<PromptCommandId, ComponentType<{ className?: string }>> = {
  kuantitatif: TrendingUpIcon,
  kualitatif: MessageSquareIcon,
  campuran: GitBranchIcon,
  rnd: WrenchIcon,
  analisis: ChartColumnIcon,
  latarbelakang: FileTextIcon,
  rumusanmasalah: HelpCircleIcon,
  tujuan: FlagIcon,
  hipotesis: Scale,
  kerangka: LayoutGridIcon,
  pembahasan: PenLineIcon,
  kesimpulan: CheckCircle2Icon,
  abstrak: BookOpenIcon,
  gap: SearchIcon,
  matriks: TableIcon,
  terdahulu: Library,
  deep: TelescopeIcon,
  akademik: SparklesIcon,
  puebi: ShieldCheckIcon,
  sitasi: Quote,
  parafrase: RotateCcwIcon,
  expand: ExpandParagraphIcon,
  summarize: FileTextIcon,
  sidang: ShieldIcon,
  reviewer: PencilIcon,
  artifact: NotebookIcon,
  workspace: FolderIcon,
};

/** Badge kuota Deep Research untuk item `/deep` — sisa run bulanan (∞ = unlimited). */
function renderDeepQuotaBadge(
  data: { deepRunsUsed: number; deepRunsLimit: number } | undefined,
): ReactNode {
  if (!data) return null;
  const { unlimited, remaining } = deepRunsQuota(data);
  if (unlimited) {
    return <ComposerPopoverBadge tone="muted">tanpa batas</ComposerPopoverBadge>;
  }
  return (
    <ComposerPopoverBadge tone={remaining > 0 ? "accent" : "muted"}>
      {remaining} tersisa
    </ComposerPopoverBadge>
  );
}

export function SlashCommandPalette({
  commands,
  highlightedIndex,
  onHighlight,
  onSelect,
}: {
  commands: PromptCommand[];
  highlightedIndex: number;
  onHighlight: (index: number) => void;
  onSelect: (command: PromptCommand) => void;
}) {
  // Kuota Deep Research ditumpangkan pada item `/deep` (cache app-wide, tanpa fetch ekstra).
  const billing = useBillingCurrent();
  let flatIndex = 0;

  return (
    <ComposerPopoverShell>
      <ComposerPopoverHeader title="Perintah" count={commands.length} />
      <ComposerPopoverList id="composer-slash-commands">
        {commands.length === 0 ? (
          <ComposerPopoverEmpty
            title="Tidak ada perintah yang cocok"
            hint={
              <>
                Coba kata kunci lain, mis. <span className="font-mono">kuantitatif</span> atau{" "}
                <span className="font-mono">matriks</span>.
              </>
            }
          />
        ) : (
          promptCommandGroups.map((group) => {
            const groupCommands = commands.filter((item) => item.group === group);
            if (groupCommands.length === 0) {
              return null;
            }
            const startIndex = flatIndex;
            flatIndex += groupCommands.length;
            return (
              <ComposerPopoverGroup key={group} label={group}>
                {groupCommands.map((item, index) => {
                  const itemIndex = startIndex + index;
                  const ItemIcon =
                    promptCommandIconMap[item.id as PromptCommandId] ?? LayoutGridIcon;
                  const deepBadge =
                    item.id === DEEP_COMMAND_ID ? renderDeepQuotaBadge(billing.data) : null;
                  return (
                    <ComposerPopoverItem
                      key={item.id}
                      value={item.id}
                      icon={ItemIcon}
                      title={item.label}
                      description={item.description}
                      active={itemIndex === highlightedIndex}
                      onSelect={() => onSelect(item)}
                      onMouseEnter={() => onHighlight(itemIndex)}
                      meta={
                        <>
                          {deepBadge}
                          <span className="font-mono text-[10.5px] text-muted-foreground/70">
                            {item.slug}
                          </span>
                        </>
                      }
                    />
                  );
                })}
              </ComposerPopoverGroup>
            );
          })
        )}
      </ComposerPopoverList>
    </ComposerPopoverShell>
  );
}
