// apps/svelte/src/lib/features/workspaces/components/WorkspaceUploadToast.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner';
	import { MAX_UPLOAD_BYTES, MAX_UPLOAD_MB } from '../utils/artifact-upload-limits';
	import {
		MAX_WORKSPACE_UPLOAD_FILES,
		type WorkspaceUploadProgressEvent,
		type WorkspaceUploadResult
	} from '$lib/features/workspaces/utils/workspace-file-upload';
	import {
		isRetryableUploadItem,
		type UploadQueueItem
	} from '$lib/features/workspaces/components/workspace-upload-toast-model';
	import WorkspaceUploadToastView from './WorkspaceUploadToastView.svelte';

	/**
	 * Upload-queue controller — port of the `useWorkspaceUploadToast` hook in
	 * `apps/web/features/workspaces/components/workspace-upload-toast.tsx`. Renders nothing itself;
	 * it owns the queue state, drives a persistent sonner toast (`WorkspaceUploadToastView`), and
	 * exposes `enqueue(files, folderId)` via `bind:this`. `isUploadActive` is a bindable mirror of
	 * the React hook's returned `isUploadActive`.
	 */
	type UploadFiles = (
		files: File[],
		folderId: 'root' | string,
		options?: {
			onFileChange?: (event: WorkspaceUploadProgressEvent) => void;
		}
	) => Promise<WorkspaceUploadResult[]>;

	let {
		onUploadFiles,
		isUploadActive = $bindable(false)
	}: {
		onUploadFiles: UploadFiles;
		isUploadActive?: boolean;
	} = $props();

	const toastId = 'workspace-upload-queue';
	const completeDismissDelayMs = 5000;

	let items = $state<UploadQueueItem[]>([]);
	let isCollapsed = $state(false);

	// Synchronous guard mirror of the React `activeRef` (state lands a tick late, so a ref keeps
	// `enqueue`/`retryFailedUploads` from double-firing) + the delayed dismiss timer.
	let activeRef = false;
	let dismissTimer: ReturnType<typeof setTimeout> | null = null;

	const hasItems = $derived(items.length > 0);
	const hasFailed = $derived(items.some((item) => item.status === 'failed'));
	const allComplete = $derived(hasItems && items.every((item) => item.status === 'complete'));

	function clearDismissTimer() {
		if (dismissTimer) {
			clearTimeout(dismissTimer);
			dismissTimer = null;
		}
	}

	function updateItem(id: string, patch: Partial<UploadQueueItem>) {
		items = items.map((item) => (item.id === id ? { ...item, ...patch } : item));
	}

	async function runUpload(queueItems: UploadQueueItem[]) {
		if (queueItems.length === 0) return;

		activeRef = true;
		isUploadActive = true;
		clearDismissTimer();

		const ids = queueItems.map((item) => item.id);
		await onUploadFiles(
			queueItems.map((item) => item.file),
			queueItems[0]?.folderId ?? 'root',
			{
				onFileChange: (event) => {
					const id = ids[event.index];
					if (!id) return;
					updateItem(id, {
						status: event.status,
						progress: event.progress,
						error: event.error
					});
				}
			}
		);

		activeRef = false;
		isUploadActive = false;
	}

	export function enqueue(files: File[], folderId: 'root' | string) {
		if (files.length === 0) return;
		if (activeRef) {
			toast.error('Tunggu upload berjalan selesai sebelum menambahkan file lagi.');
			return;
		}
		if (files.length > MAX_WORKSPACE_UPLOAD_FILES) {
			toast.error(`Maksimal ${MAX_WORKSPACE_UPLOAD_FILES} file dalam satu upload.`);
			return;
		}

		const queueItems = files.map((file): UploadQueueItem => {
			const isOversized = file.size > MAX_UPLOAD_BYTES;
			return {
				id: createUploadItemId(),
				file,
				folderId,
				status: isOversized ? 'failed' : 'queued',
				progress: 0,
				error: isOversized ? `${file.name} melebihi batas ${MAX_UPLOAD_MB} MB.` : undefined
			};
		});
		items = queueItems;
		isCollapsed = false;

		const uploadable = queueItems.filter((item) => item.status !== 'failed');
		void runUpload(uploadable);
	}

	function dismissToast() {
		clearDismissTimer();
		items = [];
		isCollapsed = false;
		isUploadActive = false;
		activeRef = false;
		toast.dismiss(toastId);
	}

	function retryFailedUploads() {
		if (activeRef) return;
		const failed = items.filter(isRetryableUploadItem);
		if (failed.length === 0) return;

		items = items.map((item) =>
			isRetryableUploadItem(item)
				? { ...item, status: 'queued', progress: 0, error: undefined }
				: item
		);
		const queueItems = failed.map((item) => ({
			...item,
			status: 'queued' as const,
			progress: 0,
			error: undefined
		}));
		const ids = queueItems.map((item) => item.id);
		activeRef = true;
		isUploadActive = true;
		clearDismissTimer();
		void onUploadFiles(
			queueItems.map((item) => item.file),
			queueItems[0]?.folderId ?? 'root',
			{
				onFileChange: (event) => {
					const id = ids[event.index];
					if (!id) return;
					updateItem(id, {
						status: event.status,
						progress: event.progress,
						error: event.error
					});
				}
			}
		).finally(() => {
			activeRef = false;
			isUploadActive = false;
		});
	}

	function createUploadItemId() {
		if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
			return crypto.randomUUID();
		}
		return Math.random().toString(36).slice(2);
	}

	// Re-publish the sonner toast whenever queue/collapse/active state changes (mirror of the React
	// render `useEffect`). Re-calling `toast.custom` with the same id updates the live toast.
	$effect(() => {
		if (!hasItems) return;
		toast.custom(WorkspaceUploadToastView, {
			id: toastId,
			componentProps: {
				items,
				isUploadActive,
				isCollapsed,
				onDismiss: dismissToast,
				onToggleCollapsed: () => (isCollapsed = !isCollapsed),
				onRetryFailed: retryFailedUploads
			},
			class: '!w-auto !border-0 !bg-transparent !p-0 !shadow-none !ring-0',
			closeButton: false,
			duration: Number.POSITIVE_INFINITY,
			dismissible: false
		});
	});

	// Auto-dismiss the queue a few seconds after everything lands cleanly.
	$effect(() => {
		clearDismissTimer();
		if (!allComplete || hasFailed) return;
		dismissTimer = setTimeout(() => {
			items = [];
			isCollapsed = false;
			isUploadActive = false;
			activeRef = false;
			toast.dismiss(toastId);
		}, completeDismissDelayMs);
		return () => clearDismissTimer();
	});
</script>

// apps/web/features/workspaces/components/workspace-upload-toast.tsx
"use client";

import { useEffect, useReducer, useRef } from "react";
import { toast } from "sonner";
import { MAX_UPLOAD_BYTES, MAX_UPLOAD_MB } from "@aqsha/convex/artifact-upload-limits";
import {
  MAX_WORKSPACE_UPLOAD_FILES,
  type WorkspaceUploadProgressEvent,
  type WorkspaceUploadResult,
} from "../utils/workspace-file-upload";
import {
  isRetryableUploadItem,
  type UploadQueueItem,
} from "./workspace-upload-toast-model";
import { WorkspaceUploadToast } from "./workspace-upload-toast-view";

type UploadFiles = (
  files: File[],
  folderId: "root" | string,
  options?: {
    onFileChange?: (event: WorkspaceUploadProgressEvent) => void;
  },
) => Promise<WorkspaceUploadResult[]>;

const toastId = "workspace-upload-queue";
const completeDismissDelayMs = 5000;

type UploadToastState = {
  items: UploadQueueItem[];
  isUploadActive: boolean;
  isCollapsed: boolean;
};

type UploadToastAction =
  | { type: "enqueue"; items: UploadQueueItem[] }
  | { type: "reset" }
  | { type: "set-collapsed"; value: boolean }
  | { type: "set-upload-active"; value: boolean }
  | { type: "update-item"; id: string; patch: Partial<UploadQueueItem> }
  | { type: "mark-retryable-queued" };

const initialUploadToastState: UploadToastState = {
  items: [],
  isUploadActive: false,
  isCollapsed: false,
};

function uploadToastReducer(
  state: UploadToastState,
  action: UploadToastAction,
): UploadToastState {
  switch (action.type) {
    case "enqueue":
      return {
        items: action.items,
        isUploadActive: state.isUploadActive,
        isCollapsed: false,
      };
    case "reset":
      return initialUploadToastState;
    case "set-collapsed":
      return { ...state, isCollapsed: action.value };
    case "set-upload-active":
      return { ...state, isUploadActive: action.value };
    case "update-item":
      return {
        ...state,
        items: state.items.map((item) =>
          item.id === action.id ? { ...item, ...action.patch } : item,
        ),
      };
    case "mark-retryable-queued":
      return {
        ...state,
        items: state.items.map((item) =>
          isRetryableUploadItem(item)
            ? { ...item, status: "queued", progress: 0, error: undefined }
            : item,
        ),
      };
  }
}

export function useWorkspaceUploadToast({
  onUploadFiles,
}: {
  onUploadFiles: UploadFiles;
}) {
  const [{ items, isUploadActive, isCollapsed }, dispatch] = useReducer(
    uploadToastReducer,
    initialUploadToastState,
  );
  const activeRef = useRef(false);
  const dismissTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const clearDismissTimer = () => {
    if (dismissTimerRef.current) {
      clearTimeout(dismissTimerRef.current);
      dismissTimerRef.current = null;
    }
  };

  const updateItem = (id: string, patch: Partial<UploadQueueItem>) => {
    dispatch({ type: "update-item", id, patch });
  };

  const runUpload = async (queueItems: UploadQueueItem[]) => {
      if (queueItems.length === 0) return;

      activeRef.current = true;
      dispatch({ type: "set-upload-active", value: true });
      clearDismissTimer();

      const ids = queueItems.map((item) => item.id);
      await onUploadFiles(
        queueItems.map((item) => item.file),
        queueItems[0]?.folderId ?? "root",
        {
          onFileChange: (event) => {
            const id = ids[event.index];
            if (!id) return;
            updateItem(id, {
              status: event.status,
              progress: event.progress,
              error: event.error,
            });
          },
        },
      );

      activeRef.current = false;
      dispatch({ type: "set-upload-active", value: false });
    };

  const enqueue = (files: File[], folderId: "root" | string) => {
      if (files.length === 0) return;
      if (activeRef.current) {
        toast.error("Tunggu upload berjalan selesai sebelum menambahkan file lagi.");
        return;
      }
      if (files.length > MAX_WORKSPACE_UPLOAD_FILES) {
        toast.error(`Maksimal ${MAX_WORKSPACE_UPLOAD_FILES} file dalam satu upload.`);
        return;
      }

      const queueItems = files.map<UploadQueueItem>((file) => {
        const isOversized = file.size > MAX_UPLOAD_BYTES;
        return {
          id: createUploadItemId(),
          file,
          folderId,
          status: isOversized ? "failed" : "queued",
          progress: 0,
          error: isOversized
            ? `${file.name} melebihi batas ${MAX_UPLOAD_MB} MB.`
            : undefined,
        };
      });
      dispatch({ type: "enqueue", items: queueItems });

      const uploadable = queueItems.filter((item) => item.status !== "failed");
      void runUpload(uploadable);
    };

  const hasItems = items.length > 0;
  const hasFailed = items.some((item) => item.status === "failed");
  const allComplete = hasItems && items.every((item) => item.status === "complete");

  useEffect(() => {
    if (!hasItems) return;

    const dismissToast = () => {
      if (dismissTimerRef.current) {
        clearTimeout(dismissTimerRef.current);
        dismissTimerRef.current = null;
      }
      dispatch({ type: "reset" });
      activeRef.current = false;
      toast.dismiss(toastId);
    };

    const retryFailedUploads = () => {
      if (activeRef.current) return;
      const failed = items.filter(isRetryableUploadItem);
      if (failed.length === 0) return;

      dispatch({ type: "mark-retryable-queued" });
      const queueItems = failed.map((item) => ({
        ...item,
        status: "queued" as const,
        progress: 0,
        error: undefined,
      }));
      const ids = queueItems.map((item) => item.id);
      activeRef.current = true;
      dispatch({ type: "set-upload-active", value: true });
      if (dismissTimerRef.current) {
        clearTimeout(dismissTimerRef.current);
        dismissTimerRef.current = null;
      }
      void onUploadFiles(
        queueItems.map((item) => item.file),
        queueItems[0]?.folderId ?? "root",
        {
          onFileChange: (event) => {
            const id = ids[event.index];
            if (!id) return;
            dispatch({
              type: "update-item",
              id,
              patch: {
                status: event.status,
                progress: event.progress,
                error: event.error,
              },
            });
          },
        },
      ).finally(() => {
        activeRef.current = false;
        dispatch({ type: "set-upload-active", value: false });
      });
    };

    toast.custom(
      () => (
        <WorkspaceUploadToast
          items={items}
          isUploadActive={isUploadActive}
          isCollapsed={isCollapsed}
          onDismiss={dismissToast}
          onToggleCollapsed={() =>
            dispatch({ type: "set-collapsed", value: !isCollapsed })
          }
          onRetryFailed={retryFailedUploads}
        />
      ),
      {
        id: toastId,
        className: "!w-auto !border-0 !bg-transparent !p-0 !shadow-none !ring-0",
        closeButton: false,
        duration: Infinity,
        dismissible: false,
      },
    );
  }, [hasItems, isCollapsed, isUploadActive, items, onUploadFiles]);

  useEffect(() => {
    if (dismissTimerRef.current) {
      clearTimeout(dismissTimerRef.current);
      dismissTimerRef.current = null;
    }
    if (!allComplete || hasFailed) return;

    dismissTimerRef.current = setTimeout(() => {
      dispatch({ type: "reset" });
      activeRef.current = false;
      toast.dismiss(toastId);
    }, completeDismissDelayMs);
    return () => {
      if (dismissTimerRef.current) {
        clearTimeout(dismissTimerRef.current);
        dismissTimerRef.current = null;
      }
    };
  }, [allComplete, hasFailed]);

  return {
    enqueue,
    isUploadActive,
  };
}

function createUploadItemId() {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return Math.random().toString(36).slice(2);
}
