// apps/web/src/lib/features/workspaces/components/WorkspacePicker.svelte
<script lang="ts">
	import { Icon, Loader2Icon } from '$lib/icons';
	import { getAuthState } from '$lib/auth';
	import { cn } from '@aqsha/ui-svelte/utils';
	import { useWorkspacesList } from '../api';
	import { workspaceEmoji } from '../utils/workspace-emoji';

	/**
	 * Reusable active-workspace picker. Lists active workspaces (excludes `excludeId`), fetches its own
	 * data via `useWorkspacesList`. Picks a workspace only (no folder step). Consumed by the
	 * save-to-workspace Dialog (discovery) and Popover (chat artifact card).
	 */
	let {
		excludeId,
		onSelect,
		disabled = false
	}: {
		excludeId?: string;
		onSelect: (workspaceId: string) => void;
		disabled?: boolean;
	} = $props();

	const auth = getAuthState();
	const list = useWorkspacesList(
		() => false,
		() => auth.isSignedIn
	);
	const items = $derived(
		(list.data?.pages ?? []).flatMap((page) => page.items).filter((w) => w.id !== excludeId)
	);
</script>

{#if list.isPending}
	<div class="flex items-center justify-center py-6 text-muted-foreground">
		<Icon icon={Loader2Icon} class="animate-spin" />
	</div>
{:else if items.length === 0}
	<p class="py-6 text-center text-sm text-muted-foreground">Tidak ada workspace lain yang aktif.</p>
{:else}
	<div class="grid max-h-64 gap-1 overflow-y-auto">
		{#each items as workspace (workspace.id)}
			<button
				type="button"
				{disabled}
				onclick={() => onSelect(workspace.id)}
				class={cn(
					'flex items-center gap-2 rounded-md px-2 py-2 text-left text-sm hover:bg-accent disabled:opacity-50'
				)}
			>
				<span class="text-lg">{workspaceEmoji(workspace.emoji)}</span>
				<span class="truncate">{workspace.name}</span>
			</button>
		{/each}
	</div>
{/if}

// apps/web/features/workspaces/components/workspace-picker.tsx
"use client";

import { Loader2Icon } from "@aqsha/ui/icons";
import { cn } from "@/lib/utils";
import { useWorkspacesList } from "../api";
import { workspaceEmoji } from "../utils/workspace-emoji";

/**
 * Picker workspace aktif reusable (mis. target pindah folder). Mengecualikan
 * `excludeId` (workspace asal). Dipakai ulang di Fase 3+ (pindah artifact).
 */
export function WorkspacePicker({
  excludeId,
  onSelect,
  disabled = false,
}: {
  excludeId?: string;
  onSelect: (workspaceId: string) => void;
  disabled?: boolean;
}) {
  const { data, isPending } = useWorkspacesList(false);
  const items = (data?.pages.flatMap((p) => p.items) ?? []).filter((w) => w.id !== excludeId);

  if (isPending) {
    return (
      <div className="flex items-center justify-center py-6 text-muted-foreground">
        <Loader2Icon className="animate-spin" />
      </div>
    );
  }
  if (items.length === 0) {
    return (
      <p className="py-6 text-center text-sm text-muted-foreground">
        Tidak ada workspace lain yang aktif.
      </p>
    );
  }

  return (
    <div className="grid max-h-64 gap-1 overflow-y-auto">
      {items.map((w) => (
        <button
          key={w.id}
          type="button"
          disabled={disabled}
          onClick={() => onSelect(w.id)}
          className={cn(
            "flex items-center gap-2 rounded-md px-2 py-2 text-left text-sm hover:bg-accent disabled:opacity-50",
          )}
        >
          <span className="text-lg">{workspaceEmoji(w.emoji)}</span>
          <span className="truncate">{w.name}</span>
        </button>
      ))}
    </div>
  );
}
