// packages/ui/src/selia/badge.tsx
'use client';

import { cn } from '../lib/cn';
import { cva, type VariantProps } from 'class-variance-authority';

export const badgeVariants = cva(
  'inline-flex items-center gap-1.5 border border-transparent',
  {
    variants: {
      variant: {
        primary: 'bg-primary/15 text-primary',
        'primary-outline': 'border-primary text-primary',
        secondary: 'bg-secondary/50 text-secondary-foreground',
        'secondary-outline': 'border-secondary text-secondary-foreground',
        tertiary: 'bg-tertiary/15 text-tertiary',
        'tertiary-outline': 'border-tertiary text-tertiary',
        success: 'bg-success/15 text-success',
        'success-outline': 'border-success text-success',
        info: 'bg-info/15 text-info',
        'info-outline': 'border-info text-info',
        warning: 'bg-warning/15 text-warning',
        'warning-outline': 'border-warning text-warning',
        danger: 'bg-danger/15 text-danger',
        'danger-outline': 'border-danger text-danger',
      },
      size: {
        sm: 'px-1 h-5 rounded-sm text-xs [&_svg:not([class*=size-])]:size-3',
        md: 'px-1.5 h-5.5 rounded-sm text-sm [&_svg:not([class*=size-])]:size-3.5',
        lg: 'px-2 h-6 rounded-sm [&_svg:not([class*=size-])]:size-4',
      },
      pill: {
        true: 'rounded-full',
      },
    },
    defaultVariants: {
      variant: 'secondary',
      size: 'md',
    },
  },
);

export function Badge({
  variant,
  size,
  pill,
  className,
  ...props
}: React.ComponentProps<'span'> & VariantProps<typeof badgeVariants>) {
  return (
    <span
      data-slot="badge"
      {...props}
      className={cn(badgeVariants({ variant, size, pill, className }))}
    />
  );
}

// apps/svelte/src/lib/components/ui/badge/badge.svelte
<script lang="ts" module>
	import { type VariantProps, tv } from 'tailwind-variants';

	export const badgeVariants = tv({
		base: 'group/badge inline-flex h-5 w-fit shrink-0 items-center justify-center gap-1 overflow-hidden rounded-4xl border border-transparent px-2 py-0.5 text-xs font-medium whitespace-nowrap transition-all focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none [&>svg]:size-3!',
		variants: {
			variant: {
				default: 'bg-primary text-primary-foreground [a]:hover:bg-primary/80',
				secondary: 'bg-secondary text-secondary-foreground [a]:hover:bg-secondary/80',
				destructive:
					'bg-destructive/10 [a]:hover:bg-destructive/20 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 text-destructive dark:bg-destructive/20',
				outline: 'border-border text-foreground [a]:hover:bg-muted [a]:hover:text-muted-foreground',
				ghost: 'hover:bg-muted hover:text-muted-foreground dark:hover:bg-muted/50',
				link: 'text-primary underline-offset-4 hover:underline'
			}
		},
		defaultVariants: {
			variant: 'default'
		}
	});

	export type BadgeVariant = VariantProps<typeof badgeVariants>['variant'];
</script>

<script lang="ts">
	import type { HTMLAnchorAttributes } from 'svelte/elements';
	import { cn, type WithElementRef } from '$lib/utils.js';

	let {
		ref = $bindable(null),
		href,
		class: className,
		variant = 'default',
		children,
		...restProps
	}: WithElementRef<HTMLAnchorAttributes> & {
		variant?: BadgeVariant;
	} = $props();
</script>

<svelte:element
	this={href ? 'a' : 'span'}
	bind:this={ref}
	data-slot="badge"
	data-variant={variant}
	{href}
	class={cn(badgeVariants({ variant }), className)}
	{...restProps}
>
	{@render children?.()}
</svelte:element>
