// packages/ui/src/selia/progress.tsx
'use client';

import { Progress as BaseProgress } from '@base-ui/react/progress';
import { cn } from '../lib/cn';

export function Progress({
  className,
  children,
  ...props
}: React.ComponentProps<typeof BaseProgress.Root>) {
  return (
    <BaseProgress.Root
      data-slot="progress"
      {...props}
      className={cn('flex flex-wrap gap-1.5 justify-between', className)}
    >
      {children}
      <BaseProgress.Track className="h-1.5 w-full rounded-full bg-track">
        <BaseProgress.Indicator className="rounded-full bg-primary transition-all duration-500" />
      </BaseProgress.Track>
    </BaseProgress.Root>
  );
}

export function ProgressLabel({
  className,
  ...props
}: React.ComponentProps<typeof BaseProgress.Label>) {
  return (
    <BaseProgress.Label
      data-slot="progress-label"
      {...props}
      className={cn('font-medium text-foreground', className)}
    />
  );
}

export function ProgressValue({
  className,
  ...props
}: React.ComponentProps<typeof BaseProgress.Value>) {
  return (
    <BaseProgress.Value
      data-slot="progress-value"
      {...props}
      className={cn('text-sm text-dimmed', className)}
    />
  );
}

// apps/svelte/src/lib/components/ui/progress/progress.svelte
<script lang="ts">
	import { Progress as ProgressPrimitive } from 'bits-ui';
	import { cn, type WithoutChildrenOrChild } from '$lib/utils.js';

	// Radix Progress via bits-ui. `value` is 0–100; the indicator slides in via translateX.
	let {
		ref = $bindable(null),
		class: className,
		max = 100,
		value = 0,
		...restProps
	}: WithoutChildrenOrChild<ProgressPrimitive.RootProps> = $props();
</script>

<ProgressPrimitive.Root
	bind:ref
	data-slot="progress"
	class={cn('bg-secondary relative h-4 w-full overflow-hidden rounded-full', className)}
	{value}
	{max}
	{...restProps}
>
	<div
		data-slot="progress-indicator"
		class="bg-primary h-full w-full flex-1 transition-all"
		style="transform: translateX(-{100 - (value ?? 0)}%)"
	></div>
</ProgressPrimitive.Root>
