// apps/web-v2/features/workspaces/components/artifact-detail-header.tsx
"use client";

import { CheckIcon, ChevronRightIcon } from "@aqsha/ui/icons";
import Link from "next/link";
import { type FormEvent, type ReactNode, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { readableConvexErrorMessage } from "@/lib/convex-error";

export function ArtifactDetailHeader({
  artifactTitle,
  onRenameArtifact,
  workspaceId,
  workspaceName,
  trailing,
}: {
  artifactTitle: string;
  onRenameArtifact: (name: string) => Promise<unknown>;
  workspaceId: string;
  workspaceName?: string;
  trailing?: ReactNode;
}) {
  return (
    <header className="sticky top-0 z-30 flex h-11 items-center justify-between gap-2 bg-background/70 px-5 backdrop-blur-xl sm:gap-4 sm:px-7">
      <nav
        aria-label="Breadcrumb"
        className="flex min-w-0 items-center gap-1.5 text-[13px]"
      >
        <Link
          href={`/app/workspaces/${workspaceId}`}
          className="hidden max-w-[12rem] shrink-0 truncate font-medium text-muted-foreground transition-colors hover:text-foreground sm:block"
        >
          {workspaceName ?? "Workspace"}
        </Link>
        <ChevronRightIcon className="hidden size-3.5 shrink-0 text-muted-foreground/60 sm:block" />
        <ArtifactTitleBreadcrumb title={artifactTitle} onRename={onRenameArtifact} />
      </nav>
      {trailing ? (
        <div className="flex shrink-0 items-center gap-0.5 sm:gap-1">{trailing}</div>
      ) : null}
    </header>
  );
}

export function ArtifactTitleBreadcrumb({
  title,
  onRename,
}: {
  title: string;
  onRename: (name: string) => Promise<unknown>;
}) {
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleOpenChange = (nextOpen: boolean) => {
    setOpen(nextOpen);
    setError(null);
    if (nextOpen) {
      setName(title);
    }
  };

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const nextName = name.trim();
    if (!nextName || nextName === title.trim()) {
      setOpen(false);
      return;
    }
    setIsSubmitting(true);
    setError(null);
    try {
      await onRename(nextName);
      setOpen(false);
    } catch (submitError) {
      setError(readableConvexErrorMessage(submitError, "We couldn't save the name."));
    }
    setIsSubmitting(false);
  };

  return (
    <Popover open={open} onOpenChange={handleOpenChange}>
      <PopoverTrigger asChild>
        <button
          type="button"
          aria-current="page"
          title={title}
          className="block min-w-0 max-w-[55ch] truncate rounded-[4px] text-left font-medium text-foreground outline-none transition-colors hover:text-foreground/70 focus-visible:ring-2 focus-visible:ring-ring/40"
          aria-label="Edit artifact name"
        >
          {title}
        </button>
      </PopoverTrigger>
      <PopoverContent align="start" className="w-72 p-3">
        <form className="grid gap-2.5" onSubmit={handleSubmit}>
          <Input
            autoFocus
            value={name}
            onChange={(event) => setName(event.target.value)}
            placeholder="Artifact name"
          />
          {error ? (
            <p className="text-[12px] font-medium text-destructive">{error}</p>
          ) : null}
          <div className="flex justify-end gap-2">
            <Button
              type="button"
              variant="ghost"
              size="sm"
              disabled={isSubmitting}
              onClick={() => setOpen(false)}
            >
              Cancel
            </Button>
            <Button type="submit" size="sm" disabled={!name.trim() || isSubmitting}>
              <CheckIcon className="size-3.5" />
              Save
            </Button>
          </div>
        </form>
      </PopoverContent>
    </Popover>
  );
}

// apps/svelte/src/lib/features/workspaces/components/ArtifactDetailHeader.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { resolve } from '$app/paths';
	import * as Popover from '@aqsha/ui-svelte/components/popover';
	import { Button } from '@aqsha/ui-svelte/components/button';
	import { Input } from '@aqsha/ui-svelte/components/input';
	import { Icon, CheckIcon, ChevronRightIcon } from '$lib/icons';
	import { readableApiErrorMessage } from '$lib/errors';

	/**
	 * Sticky artifact-reader breadcrumb header. Workspace crumb → editable title crumb (a controlled
	 * rename popover, formerly `ArtifactTitleBreadcrumb`, inlined here) → optional `trailing` actions.
	 */
	let {
		artifactTitle,
		onRenameArtifact,
		workspaceId,
		workspaceName,
		trailing
	}: {
		artifactTitle: string;
		onRenameArtifact: (name: string) => Promise<unknown>;
		workspaceId: string;
		workspaceName?: string;
		trailing?: Snippet;
	} = $props();

	let open = $state(false);
	let name = $state('');
	let isSubmitting = $state(false);
	let error = $state<string | null>(null);
	let inputEl = $state<HTMLInputElement | null>(null);

	function handleOpenChange(nextOpen: boolean) {
		open = nextOpen;
		error = null;
		if (nextOpen) {
			name = artifactTitle;
			requestAnimationFrame(() => inputEl?.focus());
		}
	}

	async function handleSubmit(event: SubmitEvent) {
		event.preventDefault();
		const nextName = name.trim();
		if (!nextName || nextName === artifactTitle.trim()) {
			open = false;
			return;
		}
		isSubmitting = true;
		error = null;
		try {
			await onRenameArtifact(nextName);
			open = false;
		} catch (submitError) {
			error = readableApiErrorMessage(submitError, "We couldn't save the name.");
		}
		isSubmitting = false;
	}
</script>

<header
	class="sticky top-0 z-30 flex h-11 items-center justify-between gap-2 bg-background/70 px-5 backdrop-blur-xl sm:gap-4 sm:px-7"
>
	<nav aria-label="Breadcrumb" class="flex min-w-0 items-center gap-1.5 text-[13px]">
		<a
			href={resolve('/app/(product)/workspaces/[workspaceId]', { workspaceId })}
			class="hidden max-w-[12rem] shrink-0 truncate font-medium text-muted-foreground transition-colors hover:text-foreground sm:block"
		>
			{workspaceName ?? 'Workspace'}
		</a>
		<Icon
			icon={ChevronRightIcon}
			class="hidden size-3.5 shrink-0 text-muted-foreground/60 sm:block"
		/>
		<Popover.Root {open} onOpenChange={handleOpenChange}>
			<Popover.Trigger>
				{#snippet child({ props })}
					<button
						{...props}
						type="button"
						aria-current="page"
						title={artifactTitle}
						class="block min-w-0 max-w-[55ch] truncate rounded-[4px] text-left font-medium text-foreground transition-colors outline-none hover:text-foreground/70 focus-visible:ring-2 focus-visible:ring-ring/40"
						aria-label="Edit artifact name"
					>
						{artifactTitle}
					</button>
				{/snippet}
			</Popover.Trigger>
			<Popover.Content align="start" class="w-72 p-3">
				<form class="grid gap-2.5" onsubmit={handleSubmit}>
					<Input bind:ref={inputEl} bind:value={name} placeholder="Artifact name" />
					{#if error}
						<p class="text-[12px] font-medium text-destructive">{error}</p>
					{/if}
					<div class="flex justify-end gap-2">
						<Button
							type="button"
							variant="ghost"
							size="sm"
							disabled={isSubmitting}
							onclick={() => (open = false)}
						>
							Cancel
						</Button>
						<Button type="submit" size="sm" disabled={!name.trim() || isSubmitting}>
							<Icon icon={CheckIcon} class="size-3.5" />
							Save
						</Button>
					</div>
				</form>
			</Popover.Content>
		</Popover.Root>
	</nav>
	{#if trailing}
		<div class="flex shrink-0 items-center gap-0.5 sm:gap-1">
			{@render trailing()}
		</div>
	{/if}
</header>
