// apps/web/features/workspaces/components/workspace-detail-client.tsx
"use client";

import { buildWorkspaceMentionLabel, type ContextRef } from "@aqsha/chat-core";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { DetailSplitLayout } from "@/components/layout/detail-split-layout";
import { ResponsiveSidePanel } from "@/components/layout/responsive-side-panel";
import { useSidebar } from "@/components/ui/sidebar";
import {
  ComposerMentionsProvider,
  usePanelContextSelection,
} from "@/features/thread-experience/components/composer-context-mentions";
import {
  useWorkspaceDetailData,
  type WorkspaceLibraryData,
} from "@/features/workspaces/api/use-workspaces-data";
import { AppLoadingOverlay } from "@/components/app-loading-overlay";
import { WorkspaceMissing } from "@/features/workspaces/components/workspace-chat-side-panel";
import { WorkspaceLibrarySurface } from "@/features/workspaces/components/workspace-library-surface";
import { WorkspaceSidePanel } from "@/features/workspaces/components/workspace-side-panel";
import {
  useWorkspacePanel,
  WorkspacePanelProvider,
} from "@/features/workspaces/components/workspace-panel-context";
import { useWorkspaceLibraryDialogState } from "@/features/workspaces/hooks/use-workspace-library-dialogs";

export function WorkspaceDetailClient({ workspaceId }: { workspaceId: string }) {
  const data = useWorkspaceDetailData(workspaceId);

  return (
    <WorkspacePanelProvider>
      <WorkspaceDetailMain workspaceId={workspaceId} data={data} />
    </WorkspacePanelProvider>
  );
}

function WorkspaceDetailMain({
  workspaceId,
  data,
}: {
  workspaceId: string;
  data: ReturnType<typeof useWorkspaceDetailData>;
}) {
  const router = useRouter();
  const leftSidebar = useSidebar();
  // Buka/tutup panel diturunkan dari nuqs `panel` (WorkspacePanelProvider) —
  // menggantikan state lokal `chatPanelOpen` (deep link `?panel=cite` jalan).
  const panel = useWorkspacePanel();
  const [panelThreadId, setPanelThreadId] = useState<string | null>(null);

  // Auto-mention: workspace yang sedang dibuka → token `@Workspace` di composer panel chat.
  const workspaceName = data.workspace?.name;
  const ambientContextRefs = useMemo<ContextRef[]>(
    () =>
      workspaceName
        ? [{ kind: "workspace", workspaceId, label: buildWorkspaceMentionLabel(workspaceName) }]
        : [],
    [workspaceId, workspaceName],
  );

  const handlePanelThreadChange = (threadId: string | null) => {
    setPanelThreadId(threadId);
    if (threadId !== null) {
      panel.openChat();
    }
  };

  const isLeftSidebarOpen = leftSidebar.isMobile
    ? leftSidebar.openMobile
    : leftSidebar.open;

  return (
    <main className="flex h-svh min-h-0 flex-col overflow-hidden bg-background">
      {data.isLoading ? (
        <AppLoadingOverlay variant="absolute" />
      ) : data.workspace === null ? (
        <WorkspaceMissing />
      ) : data.workspace ? (
        <ComposerMentionsProvider
          threadId={panelThreadId ?? undefined}
          ambientWorkspaceId={workspaceId}
          ambientContextRefs={ambientContextRefs}
        >
          <DetailSplitLayout
            sideOpen={panel.isOpen}
            onSideOpenChange={panel.setOpen}
            main={
              <WorkspaceLibraryMain
                workspaceId={workspaceId}
                workspaceName={data.workspace.name}
                libraryData={data}
                panelOpen={panel.isOpen}
                onOpenPanel={() => panel.setOpen(true)}
                showLeftSidebarTrigger={!isLeftSidebarOpen}
                onToggleLeftSidebar={leftSidebar.toggleSidebar}
                onAfterArchive={() => router.push("/app/workspaces")}
              />
            }
            side={
              <ResponsiveSidePanel open={panel.isOpen}>
                <WorkspaceSidePanel
                  workspaceId={workspaceId}
                  activeThreadId={panelThreadId}
                  onActiveThreadIdChange={handlePanelThreadChange}
                  threads={data.workspaceThreads}
                  rateStatus={data.rateStatus}
                />
              </ResponsiveSidePanel>
            }
          />
        </ComposerMentionsProvider>
      ) : null}
    </main>
  );
}

function WorkspaceLibraryMain({
  workspaceId,
  workspaceName,
  libraryData,
  panelOpen,
  onOpenPanel,
  showLeftSidebarTrigger,
  onToggleLeftSidebar,
  onAfterArchive,
}: {
  workspaceId: string;
  workspaceName: string;
  libraryData: WorkspaceLibraryData;
  panelOpen: boolean;
  onOpenPanel: () => void;
  showLeftSidebarTrigger: boolean;
  onToggleLeftSidebar: () => void;
  onAfterArchive: () => void;
}) {
  const panel = useWorkspacePanel();
  const dialogState = useWorkspaceLibraryDialogState();
  const titleById = (() => {
    const map = new Map<string, string>();
    for (const artifact of libraryData.artifacts) {
      map.set(artifact._id, artifact.title);
    }
    return map;
  })();
  const contextSelection = usePanelContextSelection({
    workspaceId,
    workspaceName,
    titleById,
  });

  return (
    <WorkspaceLibrarySurface
      workspaceId={workspaceId}
      workspaceName={workspaceName}
      libraryData={libraryData}
      dialogState={dialogState}
      getArtifactSelected={contextSelection.getArtifactSelected}
      onToggleArtifactContext={contextSelection.onToggleArtifactContext}
      onSetArtifactContextSelection={contextSelection.onSetArtifactContextSelection}
      contextCount={contextSelection.contextCount}
      onAfterArchive={onAfterArchive}
      chatPanelOpen={panelOpen}
      onToggleChatPanel={onOpenPanel}
      showLeftSidebarTrigger={showLeftSidebarTrigger}
      onToggleLeftSidebar={onToggleLeftSidebar}
      onCitationAdded={(citationId) => panel.openCitationDetail(citationId)}
    />
  );
}

// apps/svelte/src/lib/features/workspaces/components/WorkspaceDetailClient.svelte
<script lang="ts">
	import { buildWorkspaceMentionLabel } from '@aqsha/chat-core';
	import { untrack } from 'svelte';
	import { goto } from '$app/navigation';
	import { SvelteMap } from 'svelte/reactivity';
	import * as Sidebar from '$lib/components/ui/sidebar/index.js';
	import DetailSplitLayout from '$lib/components/layout/DetailSplitLayout.svelte';
	import ResponsiveSidePanel from '$lib/components/layout/ResponsiveSidePanel.svelte';
	import AppLoadingOverlay from '$lib/components/layout/AppLoadingOverlay.svelte';
	import {
		ComposerMentions,
		getComposerMentions,
		panelContextSelection,
		setComposerMentions
	} from '$lib/features/threads/state/composer-mentions.svelte';
	import { useWorkspaceDetailData } from '../api/use-workspaces-data';
	import { WorkspaceLibraryDialogState } from '../hooks/use-workspace-library-dialogs.svelte';
	import { setWorkspacePanel, WorkspacePanelController } from './workspace-panel-context.svelte';
	import WorkspaceLibrarySurface from './WorkspaceLibrarySurface.svelte';
	import WorkspaceSidePanel from './WorkspaceSidePanel.svelte';

	/**
	 * Workspace detail — Svelte port of `workspace-detail-client.tsx`. Provides the per-tree
	 * `ComposerMentions` (with the `@Workspace` ambient pill) + `WorkspacePanelController` (URL `?panel=`),
	 * then renders the library surface (main) + the tabbed `Chat · Sitasi` side panel inside a
	 * `DetailSplitLayout`. GOTCHA (memory): the split layout needs a fixed-height `h-svh` ancestor or its
	 * inner `overflow-y-auto` dies — hence the bounded `<main>`.
	 */
	let { workspaceId }: { workspaceId: string } = $props();

	const data = useWorkspaceDetailData(() => workspaceId);

	// Per-tree channels (never module singletons, §3.5).
	setComposerMentions(new ComposerMentions());
	const mentions = getComposerMentions();
	const panel = setWorkspacePanel(new WorkspacePanelController());
	const dialogState = new WorkspaceLibraryDialogState();

	let panelThreadId = $state<string | null>(null);

	function handlePanelThreadChange(threadId: string | null) {
		panelThreadId = threadId;
		if (threadId !== null) panel.openChat();
	}

	// Auto-mention: the open workspace → an `@Workspace` ambient pill in the panel chat composer.
	$effect(() => {
		const name = data.workspace?.name;
		mentions.syncAmbientFromPage(
			name ? [{ kind: 'workspace', workspaceId, label: buildWorkspaceMentionLabel(name) }] : []
		);
	});

	// Library "click-once = context" selection channel (shared with the composer pins). `titleById`
	// and the workspace name are read fresh per call so labels reflect the loaded workspace.
	const titleById = () => {
		const map = new SvelteMap<string, string>();
		for (const artifact of data.artifacts) map.set(artifact._id, artifact.title);
		return map;
	};
	const contextSelection = untrack(() =>
		panelContextSelection(mentions, {
			workspaceId,
			workspaceName: data.workspace?.name ?? '',
			titleById
		})
	);

	const workspace = $derived(data.workspace);
	const leftSidebar = Sidebar.useSidebar();
	const isLeftSidebarOpen = $derived(
		leftSidebar.isMobile ? leftSidebar.openMobile : leftSidebar.open
	);
</script>

<main class="flex h-svh min-h-0 flex-col overflow-hidden bg-background">
	{#if data.isLoading}
		<AppLoadingOverlay variant="absolute" />
	{:else if data.workspace === null}
		<div class="grid min-h-svh place-items-center px-4 text-center">
			<div class="grid gap-3">
				<h1 class="font-heading text-2xl font-semibold">Workspace tidak tersedia.</h1>
				<p class="text-[13px] font-medium text-muted-foreground">
					Workspace ini tidak ditemukan untuk akun yang sedang masuk.
				</p>
			</div>
		</div>
	{:else if workspace}
		<DetailSplitLayout sideOpen={panel.isOpen} onSideOpenChange={(open) => panel.setOpen(open)}>
			{#snippet main()}
				<WorkspaceLibrarySurface
					{workspaceId}
					workspaceName={workspace.name}
					libraryData={data}
					{dialogState}
					getArtifactSelected={contextSelection.getArtifactSelected}
					onToggleArtifactContext={contextSelection.onToggleArtifactContext}
					onSetArtifactContextSelection={contextSelection.onSetArtifactContextSelection}
					contextCount={contextSelection.contextCount}
					onAfterArchive={() => goto('/app/workspaces')}
					chatPanelOpen={panel.isOpen}
					onToggleChatPanel={() => panel.setOpen(true)}
					showLeftSidebarTrigger={!isLeftSidebarOpen}
					onToggleLeftSidebar={() => leftSidebar.toggle()}
					onCitationAdded={(citationId) => panel.openCitationDetail(citationId)}
				/>
			{/snippet}
			{#snippet side()}
				<ResponsiveSidePanel open={panel.isOpen}>
					<WorkspaceSidePanel
						{workspaceId}
						activeThreadId={panelThreadId}
						onActiveThreadIdChange={handlePanelThreadChange}
						threads={data.workspaceThreads}
					/>
				</ResponsiveSidePanel>
			{/snippet}
		</DetailSplitLayout>
	{/if}
</main>
