// apps/app/features/settings/components/settings-header.tsx
import { settingsItemForPath, type SettingsKey } from "../lib/settings-menu";

export function SettingsHeader({
  section,
  title,
}: {
  section: SettingsKey;
  title?: string;
}) {
  const item = settingsItemForPath(`/settings/${section}`);
  const heading = title ?? item.label;

  return (
    <header className="mb-1">
      <h1 className="font-heading text-[1.75rem] font-bold tracking-tight text-foreground sm:text-[2rem]">
        {heading}
      </h1>
      {item.description ? (
        <p className="mt-1.5 max-w-xl text-[13px] leading-relaxed text-muted-foreground">
          {item.description}
        </p>
      ) : null}
    </header>
  );
}

// apps/svelte/src/lib/features/settings/components/SettingsHeader.svelte
<script lang="ts">
	import { settingsItemForPath, type SettingsKey } from '../lib/settings-menu';

	/**
	 * Page header (title + subtitle). `description === null` hides the subtitle; `undefined` falls back
	 * to the menu item's description.
	 */
	let {
		section,
		title,
		description
	}: { section: SettingsKey; title?: string; description?: string | null } = $props();

	const item = $derived(settingsItemForPath(`/app/settings/${section}`));
	const heading = $derived(title ?? item.label);
	const sub = $derived(description === undefined ? item.description : description);
</script>

<header class="mb-1">
	<h1 class="font-heading text-[1.75rem] font-bold tracking-tight text-foreground sm:text-[2rem]">
		{heading}
	</h1>
	{#if sub}
		<p class="mt-1.5 max-w-xl text-[13px] leading-relaxed text-muted-foreground">{sub}</p>
	{/if}
</header>
