// packages/ui-svelte/src/components/checkbox/checkbox.svelte
<script lang="ts">
	import { Checkbox as CheckboxPrimitive } from 'bits-ui';
	import { cn, type WithoutChildrenOrChild } from '../../utils.js';
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import { Tick02Icon } from '@hugeicons/core-free-icons';
	import { MinusSignIcon } from '@hugeicons/core-free-icons';

	let {
		ref = $bindable(null),
		checked = $bindable(false),
		indeterminate = $bindable(false),
		class: className,
		...restProps
	}: WithoutChildrenOrChild<CheckboxPrimitive.RootProps> = $props();
</script>

<CheckboxPrimitive.Root
	bind:ref
	data-slot="checkbox"
	class={cn(
		'border-border bg-card lip-static data-[state=checked]:bg-mint-strong data-[state=checked]:border-mint-strong data-[state=checked]:text-white data-[state=checked]:[--lip-color:color-mix(in_oklch,var(--mint-strong)_62%,black_38%)] aria-invalid:border-destructive dark:aria-invalid:border-destructive/50 focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 flex size-6 items-center justify-center rounded-sm border-2 transition-colors group-has-disabled/field:opacity-50 focus-visible:ring-3 aria-invalid:ring-3 peer relative shrink-0 outline-none after:absolute after:-inset-x-3 after:-inset-y-2 disabled:cursor-not-allowed disabled:opacity-50',
		className
	)}
	bind:checked
	bind:indeterminate
	{...restProps}
>
	{#snippet children({ checked, indeterminate })}
		<div
			data-slot="checkbox-indicator"
			class="[&>svg]:size-4 grid place-content-center text-current transition-none"
		>
			{#if checked}
				<HugeiconsIcon icon={Tick02Icon} strokeWidth={2} />
			{:else if indeterminate}
				<HugeiconsIcon icon={MinusSignIcon} strokeWidth={2} />
			{/if}
		</div>
	{/snippet}
</CheckboxPrimitive.Root>

// packages/ui/src/selia/checkbox.tsx
'use client';

import { Checkbox as BaseCheckbox } from '@base-ui/react/checkbox';
import { useRender } from '@base-ui/react/use-render';
import { CheckboxGroup as BaseCheckboxGroup } from '@base-ui/react/checkbox-group';
import { cn } from '../lib/cn';

export function CheckboxGroup({
  className,
  ...props
}: React.ComponentProps<typeof BaseCheckboxGroup>) {
  return (
    <BaseCheckboxGroup
      data-slot="checkbox-group"
      {...props}
      className={cn('flex flex-col gap-2.5', className)}
    />
  );
}

export function CheckboxGroupLabel({
  render,
  ...props
}: useRender.ComponentProps<'span'>) {
  return useRender({
    defaultTagName: 'span',
    render,
    props: {
      'data-slot': 'checkbox-group-label',
      className: cn('text-foreground font-medium', props.className),
      ...props,
    },
  });
}

export function Checkbox({
  ...props
}: React.ComponentProps<typeof BaseCheckbox.Root>) {
  return (
    <BaseCheckbox.Root
      data-slot="checkbox"
      {...props}
      className={cn(
        'size-4 shrink-0 flex items-center justify-center rounded-xs border border-input-border bg-input shadow-input cursor-pointer',
        'focus:outline-0 focus-visible:outline-2 focus-visible:outline-offset-2 outline-primary',
        'data-[checked]:bg-primary data-[checked]:border-primary',
        'transition-colors duration-75 hover:border-input-accent-border',
        'data-disabled:cursor-not-allowed data-disabled:opacity-50',
        props.className,
      )}
    >
      <BaseCheckbox.Indicator
        className="data-[unchecked]:hidden flex"
        render={(props, state) => (
          <span {...props}>
            {state.indeterminate ? (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="3"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="size-3"
              >
                <line x1="5" y1="12" x2="19" y2="12" />
              </svg>
            ) : (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="none"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="3"
                className="size-3 text-primary-foreground"
                viewBox="0 0 24 24"
              >
                <path d="M20 6 9 17l-5-5"></path>
              </svg>
            )}
          </span>
        )}
      />
    </BaseCheckbox.Root>
  );
}
