// packages/ui-svelte/src/components/toggle-group/toggle-group.svelte
<script lang="ts" module>
	import { getContext, setContext } from 'svelte';
	import type { VariantProps } from 'tailwind-variants';
	import { toggleVariants } from '../toggle/index.js';

	type ToggleVariants = VariantProps<typeof toggleVariants>;

	interface ToggleGroupContext extends ToggleVariants {
		spacing?: number;
		orientation?: 'horizontal' | 'vertical';
	}

	export function setToggleGroupCtx(props: ToggleGroupContext) {
		setContext('toggleGroup', props);
	}

	export function getToggleGroupCtx() {
		return getContext<ToggleGroupContext>('toggleGroup');
	}
</script>

<script lang="ts">
	import { ToggleGroup as ToggleGroupPrimitive } from 'bits-ui';
	import { cn } from '../../utils.js';

	let {
		ref = $bindable(null),
		value = $bindable(),
		class: className,
		size = 'default',
		spacing = 1.5,
		orientation = 'horizontal',
		variant = 'default',
		...restProps
	}: ToggleGroupPrimitive.RootProps &
		ToggleVariants & {
			spacing?: number;
			orientation?: 'horizontal' | 'vertical';
		} = $props();

	setToggleGroupCtx({
		get variant() {
			return variant;
		},
		get size() {
			return size;
		},
		get spacing() {
			return spacing;
		},
		get orientation() {
			return orientation;
		}
	});
</script>

<!--
Discriminated Unions + Destructing (required for bindable) do not
get along, so we shut typescript up by casting `value` to `never`.
-->
<ToggleGroupPrimitive.Root
	bind:value={value as never}
	bind:ref
	{orientation}
	data-slot="toggle-group"
	data-variant={variant}
	data-size={size}
	data-spacing={spacing}
	style={`--gap: ${spacing}`}
	class={cn(
		'border-border rounded-md border-2 p-[5px] group/toggle-group flex w-fit flex-row items-center gap-[--spacing(var(--gap))] data-[orientation=vertical]:flex-col data-[orientation=vertical]:items-stretch',
		className
	)}
	{...restProps}
/>

// packages/ui/src/selia/toggle-group.tsx
'use client';

import { ToggleGroup as BaseToggleGroup } from '@base-ui/react/toggle-group';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../lib/cn';

export const toggleGroupVariants = cva(
  [
    'flex items-center gap-0.5 ring rounded p-0.5',
    '*:data-[slot=toggle]:shadow-none',
    '*:data-[slot=toggle]:ring-0',
  ],
  {
    variants: {
      variant: {
        default: 'ring-border shadow',
        outline: 'ring-border',
        plain: 'ring-transparent',
      },
      size: {
        sm: [
          '*:data-[slot=toggle]:px-3',
          '*:data-[slot=toggle]:h-[calc(var(--spacing)*8.5-4px)]',
          '*:data-[slot=toggle]:min-w-[calc(var(--spacing)*8.5-4px)]',
        ],
        'sm-icon': [
          '*:data-[slot=toggle]:size-8.5',
          '*:data-[slot=toggle]:px-0',
          'not-[[data-variant=plain]]:*:data-[slot=toggle]:size-[calc(var(--spacing)*8.5-4px)]',
          'not-[[data-variant=plain]]:*:data-[slot=toggle]:min-w-[calc(var(--spacing)*8.5-4px)]',
        ],
        md: [
          '*:data-[slot=toggle]:h-[calc(var(--spacing)*9.5-4px)]',
          '*:data-[slot=toggle]:min-w-[calc(var(--spacing)*9.5-4px)]',
        ],
        'md-icon': [
          '*:data-[slot=toggle]:size-9.5',
          '*:data-[slot=toggle]:px-0',
          'not-[[data-variant=plain]]:*:data-[slot=toggle]:size-[calc(var(--spacing)*9.5-4px)]',
          'not-[[data-variant=plain]]:*:data-[slot=toggle]:min-w-[calc(var(--spacing)*9.5-4px)]',
        ],
      },
      orientation: {
        horizontal: 'flex-row',
        vertical: 'flex-col',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  },
);

export function ToggleGroup({
  className,
  orientation,
  size,
  variant,
  ...props
}: React.ComponentProps<typeof BaseToggleGroup> &
  VariantProps<typeof toggleGroupVariants>) {
  return (
    <BaseToggleGroup
      data-slot="toggle-group"
      data-variant={variant}
      data-size={size}
      orientation={orientation}
      className={cn(
        toggleGroupVariants({ variant, orientation, size, className }),
      )}
      {...props}
    />
  );
}
