// apps/web-v2/components/ai-elements/shimmer.tsx
"use client";

 

import { cn } from "@/lib/utils";
import type { MotionProps } from "motion/react";
import { m } from "motion/react";
import { createElement } from "react";
import type { CSSProperties, ElementType, JSX } from "react";
type MotionHTMLProps = MotionProps & Record<string, unknown>;

// Cache motion components at module level to avoid creating during render.
const motionComponentCache = new Map<
  keyof JSX.IntrinsicElements,
  React.ComponentType<MotionHTMLProps>
>();

const getMotionComponent = (element: keyof JSX.IntrinsicElements) => {
  let component = motionComponentCache.get(element);
  if (!component) {
    component = m.create(element);
    motionComponentCache.set(element, component);
  }
  return component;
};

export interface TextShimmerProps {
  children: string;
  as?: ElementType;
  className?: string;
  duration?: number;
  spread?: number;
}

const ShimmerComponent = ({
  children,
  as: Component = "p",
  className,
  duration = 2,
  spread = 2,
}: TextShimmerProps) => {
  const motionComponent = getMotionComponent(
    Component as keyof JSX.IntrinsicElements
  );

  const dynamicSpread = (children?.length ?? 0) * spread;

  return createElement(
    motionComponent,
    {
      animate: { backgroundPosition: "0% center" },
      className: cn(
        "relative inline-block bg-[length:250%_100%,auto] bg-clip-text text-transparent",
        "[--bg:linear-gradient(90deg,#0000_calc(50%-var(--spread)),var(--color-background),#0000_calc(50%+var(--spread)))] [background-repeat:no-repeat,padding-box]",
        className
      ),
      initial: { backgroundPosition: "100% center" },
      style: {
        "--spread": `${dynamicSpread}px`,
        backgroundImage:
          "var(--bg), linear-gradient(var(--color-muted-foreground), var(--color-muted-foreground))",
      } as CSSProperties,
      transition: {
        duration,
        ease: "linear",
        repeat: Number.POSITIVE_INFINITY,
      },
    } as MotionHTMLProps,
    children,
  );
};

export const Shimmer = ShimmerComponent;

// apps/svelte/src/lib/components/ai-elements/Shimmer.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { cn } from '$lib/utils';

	/**
	 * Text shimmer — a moving highlight sweeping across the text (Astra "working" labels). Pure CSS
	 * keyframe (`--spread` scales with text length) so it needs no motion runtime and honours
	 * `prefers-reduced-motion` (the animation is disabled under reduced motion via the utility class).
	 */
	let {
		children,
		as = 'p',
		class: className,
		text,
		spread = 2
	}: {
		children?: Snippet;
		as?: 'p' | 'span' | 'div';
		class?: string;
		/** Text content (used to size the shimmer spread); pass when not using the children snippet. */
		text?: string;
		spread?: number;
	} = $props();

	const dynamicSpread = $derived((text?.length ?? 8) * spread);
</script>

<svelte:element
	this={as}
	class={cn('aqsha-shimmer relative inline-block', className)}
	style="--spread: {dynamicSpread}px"
>
	{#if children}{@render children()}{:else}{text}{/if}
</svelte:element>

<style>
	:global(.aqsha-shimmer) {
		background-image:
			linear-gradient(
				90deg,
				transparent calc(50% - var(--spread)),
				var(--color-background),
				transparent calc(50% + var(--spread))
			),
			linear-gradient(var(--color-muted-foreground), var(--color-muted-foreground));
		background-repeat: no-repeat, padding-box;
		background-size:
			250% 100%,
			auto;
		background-clip: text;
		color: transparent;
		animation: aqsha-shimmer-move 2s linear infinite;
	}

	@keyframes aqsha-shimmer-move {
		from {
			background-position: 100% center;
		}
		to {
			background-position: 0% center;
		}
	}

	@media (prefers-reduced-motion: reduce) {
		:global(.aqsha-shimmer) {
			animation: none;
		}
	}
</style>
