// apps/svelte/src/lib/features/changelog/components/CategoryBadge.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import { Icon } from '$lib/icons';
	import { CATEGORY_META } from '../lib/categories';
	import type { ChangelogCategory } from '../types';

	let { category }: { category: ChangelogCategory } = $props();

	const meta = $derived(CATEGORY_META[category]);
</script>

{#if meta}
	<span
		class={cn(
			'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-xs font-medium leading-none',
			meta.className
		)}
	>
		<Icon icon={meta.icon} class="size-3" aria-hidden="true" />
		{meta.label}
	</span>
{/if}

// apps/web/features/changelog/components/category-badge.tsx
import { cn } from "@/lib/utils";
import { CATEGORY_META } from "@/features/changelog/lib/categories";
import type { ChangelogCategory } from "@/features/changelog/types";

/** Pill kategori changelog (baru / peningkatan / perbaikan) — ikon + label. */
export function CategoryBadge({ category }: { category: ChangelogCategory }) {
  const meta = CATEGORY_META[category];
  if (!meta) return null;

  const { label, Icon, className } = meta;
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-xs font-medium leading-none",
        className,
      )}
    >
      <Icon className="size-3" aria-hidden />
      {label}
    </span>
  );
}
