// apps/svelte/src/lib/features/changelog/components/ChangelogDateline.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import { formatDateId } from '$lib/dates';
	import type { ChangelogEntry } from '../types';

	let { entry, class: className }: { entry: ChangelogEntry; class?: string } = $props();
</script>

<!-- Tanggal terbit + versi opsional dengan aksen token `text-chart-1`. Ukuran/margin via `class`. -->
<p class={cn('font-medium text-chart-1', className)}>
	<time datetime={entry.publishedAt}>{formatDateId(entry.publishedAt)}</time>
	{#if entry.version}<span class="text-chart-1/70"> · v{entry.version}</span>{/if}
</p>

// apps/web/features/changelog/components/changelog-dateline.tsx
import { cn } from "@/lib/utils";
import { formatDateId } from "@/lib/dates";
import type { ChangelogEntry } from "@/features/changelog/types";

/**
 * Tanggal terbit + versi opsional dengan aksen token `text-chart-1`. Satu sumber
 * dipakai kartu timeline & header halaman detail (ukuran/margin via `className`).
 */
export function ChangelogDateline({
  entry,
  className,
}: {
  entry: ChangelogEntry;
  className?: string;
}) {
  return (
    <p className={cn("font-medium text-chart-1", className)}>
      <time dateTime={entry.publishedAt}>{formatDateId(entry.publishedAt)}</time>
      {entry.version && <span className="text-chart-1/70"> · v{entry.version}</span>}
    </p>
  );
}
