// apps/svelte/src/lib/features/changelog/components/ChangelogCard.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import CategoryBadge from './CategoryBadge.svelte';
	import ChangelogDateline from './ChangelogDateline.svelte';
	import ChangelogPreview from './ChangelogPreview.svelte';
	import type { ChangelogEntry } from '../types';

	let { entry }: { entry: ChangelogEntry } = $props();
</script>

<!-- Kartu changelog compact (1 kolom, horizontal di desktop): thumbnail kiri, lalu tanggal (aksen) +
     judul + ringkasan + badge di kanan. Seluruh kartu link ke detail — body MDX lengkap di sana. -->
<a
	href={resolve('/(marketing)/changelog/[slug]', { slug: entry.slug })}
	class="group flex flex-col overflow-hidden rounded-2xl border border-border/60 bg-card transition-colors hover:border-border sm:min-h-[8.5rem] sm:flex-row"
>
	<ChangelogPreview
		{entry}
		class="aspect-[16/9] border-b border-border/60 sm:aspect-auto sm:w-52 sm:shrink-0 sm:border-r sm:border-b-0"
	/>

	<div class="flex-1 p-5">
		<ChangelogDateline {entry} class="text-xs" />

		<h2
			class="mt-1.5 text-base font-semibold leading-snug text-foreground transition-colors group-hover:text-foreground/70"
		>
			{entry.title}
		</h2>

		{#if entry.excerpt}
			<p class="mt-1.5 line-clamp-2 text-sm leading-6 text-muted-foreground">
				{entry.excerpt}
			</p>
		{/if}

		{#if entry.categories.length > 0}
			<div class="mt-3 flex flex-wrap gap-1.5">
				{#each entry.categories as category (category)}
					<CategoryBadge {category} />
				{/each}
			</div>
		{/if}
	</div>
</a>

// apps/web/features/changelog/components/changelog-card.tsx
import Link from "next/link";

import { CategoryBadge } from "@/features/changelog/components/category-badge";
import { ChangelogDateline } from "@/features/changelog/components/changelog-dateline";
import { ChangelogPreview } from "@/features/changelog/components/changelog-preview";
import type { ChangelogEntry } from "@/features/changelog/types";

/**
 * Kartu changelog compact (1 kolom, horizontal di desktop): thumbnail di kiri,
 * lalu tanggal (aksen) + judul + ringkasan singkat + badge di kanan. Seluruh
 * kartu link ke halaman detail — body MDX lengkap hidup di sana, bukan di kartu.
 */
export function ChangelogCard({ entry }: { entry: ChangelogEntry }) {
  return (
    <Link
      href={entry.url}
      className="group flex flex-col overflow-hidden rounded-2xl border border-border/60 bg-card transition-colors hover:border-border sm:min-h-[8.5rem] sm:flex-row"
    >
      <ChangelogPreview
        entry={entry}
        className="aspect-[16/9] border-b border-border/60 sm:aspect-auto sm:w-52 sm:shrink-0 sm:border-r sm:border-b-0"
      />

      <div className="flex-1 p-5">
        <ChangelogDateline entry={entry} className="text-xs" />

        <h2 className="mt-1.5 text-base font-semibold leading-snug text-foreground transition-colors group-hover:text-foreground/70">
          {entry.title}
        </h2>

        {entry.excerpt && (
          <p className="mt-1.5 line-clamp-2 text-sm leading-6 text-muted-foreground">
            {entry.excerpt}
          </p>
        )}

        {entry.categories.length > 0 && (
          <div className="mt-3 flex flex-wrap gap-1.5">
            {entry.categories.map((category) => (
              <CategoryBadge key={category} category={category} />
            ))}
          </div>
        )}
      </div>
    </Link>
  );
}
