// apps/web/components/ai-elements/conversation-scroll-button.tsx
"use client";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { ArrowDownIcon } from "@aqsha/ui/icons";
import type { ComponentProps } from "react";
import { useStickToBottomContext } from "use-stick-to-bottom";

export type ConversationScrollButtonProps = ComponentProps<typeof Button>;

export const ConversationScrollButton = ({
  className,
  ...props
}: ConversationScrollButtonProps) => {
  const { isAtBottom, scrollToBottom } = useStickToBottomContext();

  const scrollConversationToBottom = () => {
    scrollToBottom();
  };

  return (
    !isAtBottom && (
      <Button
        className={cn(
          "absolute bottom-4 left-[50%] translate-x-[-50%] rounded-full dark:bg-background dark:hover:bg-muted",
          className
        )}
        onClick={scrollConversationToBottom}
        size="icon"
        type="button"
        variant="outline"
        {...props}
      >
        <ArrowDownIcon className="size-4" />
      </Button>
    )
  );
};

// apps/web/src/lib/components/ai-elements/ConversationScrollButton.svelte
<script lang="ts">
	import { cn } from '@aqsha/ui-svelte/utils';
	import { Button } from '@aqsha/ui-svelte/components/button';
	import { Icon, ArrowDownIcon } from '$lib/icons';
	import { getStickToBottom } from './conversation-state.svelte';

	// Floating "jump to latest" button, shown ONLY while not at the bottom (reads `isAtBottom` from the
	// follow-bottom context). Place inside `Conversation`'s `overlay` snippet.

	let { class: klass }: { class?: string } = $props();

	const stick = getStickToBottom();
</script>

{#if !stick.isAtBottom}
	<Button
		type="button"
		variant="outline"
		size="icon"
		onclick={() => stick.scrollToBottom()}
		class={cn(
			'absolute bottom-4 left-[50%] translate-x-[-50%] rounded-full dark:bg-background dark:hover:bg-muted',
			klass
		)}
	>
		<Icon icon={ArrowDownIcon} class="size-4" />
	</Button>
{/if}
