// apps/svelte/src/lib/features/settings/pages/AccountPage.svelte
<script lang="ts">
	import * as Dialog from '@aqsha/ui-svelte/components/dialog';
	import { Button } from '@aqsha/ui-svelte/components/button';
	import { Input } from '@aqsha/ui-svelte/components/input';
	import { Icon, Loader2Icon, Trash2Icon } from '$lib/icons';
	import { getSignOut } from '$lib/auth';
	import { useDeleteAccount, useProfile, useUpdateDisplayName } from '../api';
	import SettingsHeader from '../components/SettingsHeader.svelte';
	import {
		SettingsPanel,
		SettingsPanelBody,
		SettingsPanelFooter,
		SettingsPanelHeader,
		SettingsRow
	} from '../components/settings-card';

	const profile = useProfile();
	const update = useUpdateDisplayName();
	const del = useDeleteAccount(getSignOut());

	let name = $state<string | null>(null);
	let confirm = $state('');
	let deleteOpen = $state(false);
	const canDelete = $derived(confirm.trim() === 'HAPUS');

	function onDeleteOpenChange(open: boolean) {
		deleteOpen = open;
		if (!open) confirm = '';
	}

	// Initialise the field from the profile once data arrives (derived, not effect).
	const value = $derived(name ?? profile.data?.name ?? '');
	const dirty = $derived(name !== null && name.trim() !== (profile.data?.name ?? ''));

	function onSubmit(event: SubmitEvent) {
		event.preventDefault();
		const trimmed = value.trim();
		if (!trimmed) return;
		update.mutate(trimmed);
	}
</script>

<SettingsHeader section="account" title="Akun" description="Kelola profil dan identitas kamu." />

<SettingsPanel>
	<SettingsPanelHeader title="Nama tampilan" description="Nama yang muncul di seluruh aplikasi." />
	<form onsubmit={onSubmit}>
		<SettingsPanelBody>
			<Input
				{value}
				oninput={(event) => (name = (event.currentTarget as HTMLInputElement).value)}
				maxlength={120}
				placeholder="Nama kamu"
				disabled={profile.isPending || update.isPending}
				class="max-w-md"
			/>
		</SettingsPanelBody>
		<SettingsPanelFooter class="justify-end">
			<Button type="submit" size="sm" disabled={!dirty || !value.trim() || update.isPending}>
				{#if update.isPending}
					<Icon icon={Loader2Icon} class="size-4 animate-spin" />
				{/if}
				Simpan
			</Button>
		</SettingsPanelFooter>
	</form>
</SettingsPanel>

<SettingsPanel>
	<SettingsPanelHeader title="Detail akun" description="Email dan foto profil kamu." />
	<div class="divide-y divide-border/60">
		<SettingsRow label="Email">
			<span class="text-muted-foreground">{profile.data?.email ?? '—'}</span>
		</SettingsRow>
		<SettingsRow label="Foto profil" description="Ubah di menu profil pojok aplikasi." />
	</div>
</SettingsPanel>

<SettingsPanel class="border-destructive/30">
	<SettingsPanelHeader
		title="Hapus akun"
		description="Menghapus permanen seluruh data kamu (workspace, artifact, chat, feed, billing). Tindakan ini tidak bisa dibatalkan."
		class="border-destructive/20"
	/>
	<SettingsPanelFooter class="justify-end border-destructive/20 bg-destructive/[0.03]">
		<Dialog.Root open={deleteOpen} onOpenChange={onDeleteOpenChange}>
			<Dialog.Trigger>
				{#snippet child({ props })}
					<Button variant="destructive" size="sm" disabled={del.isPending} {...props}>
						<Icon icon={Trash2Icon} class="size-4" />
						Hapus akun saya
					</Button>
				{/snippet}
			</Dialog.Trigger>
			<Dialog.Content class="sm:max-w-md">
				<Dialog.Header>
					<Dialog.Title>Hapus akun permanen?</Dialog.Title>
					<Dialog.Description>
						Menghapus seluruh data kamu (workspace, artifact, chat, feed, billing). Tindakan ini
						tidak bisa dibatalkan.
					</Dialog.Description>
				</Dialog.Header>
				<div class="grid gap-2">
					<label for="confirm-delete" class="text-[13px] font-medium text-foreground">
						Ketik <span class="font-semibold">HAPUS</span> untuk konfirmasi
					</label>
					<Input
						id="confirm-delete"
						value={confirm}
						oninput={(event) => (confirm = (event.currentTarget as HTMLInputElement).value)}
						placeholder="HAPUS"
						disabled={del.isPending}
						{@attach (node) => node.focus()}
					/>
				</div>
				<Dialog.Footer>
					<Dialog.Close>
						{#snippet child({ props })}
							<Button variant="outline" size="sm" disabled={del.isPending} {...props}>Batal</Button>
						{/snippet}
					</Dialog.Close>
					<Button
						variant="destructive"
						size="sm"
						disabled={!canDelete || del.isPending}
						onclick={() => del.mutate()}
					>
						{#if del.isPending}
							<Icon icon={Loader2Icon} class="size-4 animate-spin" />
						{:else}
							<Icon icon={Trash2Icon} class="size-4" />
						{/if}
						Hapus permanen
					</Button>
				</Dialog.Footer>
			</Dialog.Content>
		</Dialog.Root>
	</SettingsPanelFooter>
</SettingsPanel>

// apps/app/features/settings/pages/account-page.tsx
"use client";

import { useState, type FormEvent } from "react";
import { Loader2Icon, MailCheckIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { authClient } from "@/lib/auth-client";
import { useSettingsAccountData } from "../api/use-settings-account-data";
import { LoadingSettingsPage } from "../components/loading-settings-page";
import { DisplayNamePanel } from "../components/display-name-field";
import { ProfileAvatarPicker } from "../components/profile-avatar-picker";
import {
  SettingsField,
  SettingsPanel,
  SettingsPanelBody,
  SettingsPanelHeader,
  SettingsReadonlyValue,
} from "../components/settings-card";
import { SettingsHeader } from "../components/settings-header";

export function SettingsAccountPage() {
  const { viewer } = useSettingsAccountData();
  if (!viewer) return <LoadingSettingsPage />;

  const name = viewer.name || "Pengguna Aqsha";
  const email = viewer.email || "Belum masuk";

  return (
    <>
      <SettingsHeader section="account" />

      <SettingsPanel>
        <SettingsPanelHeader
          title="Profil"
          description="Informasi yang ditampilkan di sidebar dan menu pengguna."
        />
        <SettingsPanelBody>
          <div className="flex items-center gap-4">
            <ProfileAvatarPicker name={name} email={email} image={viewer.image} />
            <div className="min-w-0">
              <p className="truncate text-[15px] font-semibold text-foreground">{name}</p>
              <p className="mt-0.5 truncate text-[13px] text-muted-foreground">{email}</p>
            </div>
          </div>
        </SettingsPanelBody>
      </SettingsPanel>

      <SettingsPanel>
        <SettingsPanelHeader
          title="Email kamu"
          description="Perubahan email dikonfirmasi lewat email lama sebelum alamat baru aktif."
        />
        <SettingsPanelBody className="grid gap-5">
          <SettingsField label="Alamat email">
            <SettingsReadonlyValue value={viewer.email ?? "Belum diisi"} />
          </SettingsField>
          <div className="flex flex-wrap items-center gap-2 text-[12px] text-muted-foreground">
            <span className="inline-flex items-center gap-1.5 rounded-full border border-border/60 bg-muted/50 px-2.5 py-1">
              <MailCheckIcon className="size-3" />
              {viewer.emailVerified ? "Terverifikasi" : "Belum terverifikasi"}
            </span>
          </div>
          <ChangeEmailForm currentEmail={viewer.email} />
        </SettingsPanelBody>
      </SettingsPanel>

      <SettingsPanel>
        <SettingsPanelHeader
          title="Detail akun"
          description="Identitas disimpan oleh penyedia autentikasi."
        />
        <DisplayNamePanel savedName={viewer.name} />
      </SettingsPanel>
    </>
  );
}

function ChangeEmailForm({ currentEmail }: { currentEmail: string | null }) {
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isPending, setIsPending] = useState(false);

  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const nextEmail = email.trim();
    if (!nextEmail || nextEmail === currentEmail) return;

    setIsPending(true);
    setError(null);
    setStatus(null);
    try {
      const result = await authClient.changeEmail({
        newEmail: nextEmail,
        callbackURL: `${window.location.origin}/settings/account`,
      });
      if (result.error) {
        throw new Error(result.error.message ?? "Gagal mengubah email.");
      }
      setEmail("");
      setStatus("Cek email lama kamu untuk mengonfirmasi perubahan alamat.");
    } catch (changeError) {
      setError(readableAuthError(changeError, "Gagal mengubah email."));
    } finally {
      setIsPending(false);
    }
  };

  return (
    <form onSubmit={submit} className="grid gap-3 rounded-xl border border-border/60 bg-muted/20 p-4">
      <div className="grid gap-2">
        <Label htmlFor="new-email" className="text-[13px] font-medium">
          Email baru
        </Label>
        <Input
          id="new-email"
          type="email"
          autoComplete="email"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          placeholder="nama@email.com"
          className="h-[42px] rounded-lg text-[13px]"
        />
      </div>
      {status ? <p className="text-[12px] text-mint-foreground">{status}</p> : null}
      {error ? <p className="text-[12px] text-coral-foreground">{error}</p> : null}
      <Button
        type="submit"
        variant="outline"
        disabled={isPending || !email.trim() || email.trim() === currentEmail}
        className="h-9 w-fit rounded-lg text-[13px]"
      >
        {isPending ? <Loader2Icon className="size-3.5 animate-spin" /> : null}
        Kirim konfirmasi
      </Button>
    </form>
  );
}

function readableAuthError(error: unknown, fallback: string) {
  if (error instanceof Error && error.message) return error.message;
  return fallback;
}
